- README.md
- src/interpreter.rs
Hey, I just wanted to get it to compile. Seemed like an easy fix :smile:
> Update to Rust Nightly 2016-04-11

- .travis.yml
- README.md
Fixes some stuff that is apparent now that I had some coffee!
> Fix travis stuff

- src/interpreter.rs
- src/memory.rs
Just some readability nits, but may be useful nonetheless.
> Fixed some clippy warnings

- benches/fibonacci.rs
- benches/fibonacci_helper.rs
- benches/fibonacci_helper_iterative.rs
- benches/miri_helper.rs
- benches/smoke.rs
- benches/smoke_helper.rs
- src/interpreter.rs
I decided on benchmarking the running time of the interpreter and skipping the startup time of rustc + parsing, typeck, MIR generation. There's a commented out benchmark that uses the miri executable instead of directly calling the interpreter. It's really slow, who would've thought ;)
results on fibonacci:
```
test fib           ... bench:         117 ns/iter (+/- 2)
test fib_iter      ... bench:           1 ns/iter (+/- 0)
test fib_iter_miri ... bench:   8,444,820 ns/iter (+/- 470,079)
test fib_miri      ... bench:   5,431,379 ns/iter (+/- 320,989)
```
The iterative fibonacci is probably slower because MIR is not optimized. So the for-loop is calling loads of functions, which is bad for miri-performance.
results on running an empty function:
```
test noop                  ... bench: …
```
> benchmarks

- Cargo.toml
- src/error.rs
- src/interpreter.rs
- src/memory.rs
- src/primval.rs
- tests/compile-fail/errors.rs
- tests/compiletest.rs
- tests/run-pass/strings.rs
Right now this expects the target and host to be linux. I haven't figured out how to make compiletest not actually compile the run-pass tests (since we don't need to run them, miri runs during compilation).
We could add them as compile-fail tests and have the miri executable generate a "miri succeeded" error
Once that works, it would be possible to automatically detects all installed targets and run miri for all of them.
The commits should probably be read one by one. I can split them into multiple PRs if preferred and/or remove some of them (like the indentation hack with a `static mut`).
> 4 byte pointers + tests

- Cargo.lock
- Cargo.toml
- src/bin/miri.rs
- src/interpreter.rs
- src/lib.rs
- tests/run-fail/inception.rs
The `MIRI_LOG` env var can now be used to change the logging granularity.
Example output:
```
DEBUG:miri::interpreter| Interpreting: out_of_bounds_read
TRACE:miri::interpreter|  // bb0
TRACE:miri::interpreter|  tmp3 = Box([u8; 2])
TRACE:miri::interpreter|  (*tmp3) = [const 1u8, const 2u8]
TRACE:miri::interpreter|  tmp2 = tmp3
TRACE:miri::interpreter|  tmp1 = tmp2 as Box<[u8]> (Unsize)
TRACE:miri::interpreter|  var0 = std::slice::<impl [T]><u8>::into_vec(tmp1) -> [return: bb5, unwind: bb4]
TRACE:miri::interpreter|   // bb0
TRACE:miri::interpreter|   var0 = arg0
TRACE:miri::interpreter|   tmp1 = var0
TRACE:miri::interpreter|   return = std::slice::hack::into_vec::<T>(tmp1) -> [return: bb5, unwind: bb4]
TRACE:miri::interpreter|    // bb0
TRACE:miri::interpreter|    var0 = arg0 …
```
> use the `log` crate + `env_logger`

- src/bin/miri.rs
- src/interpreter/mod.rs
- src/interpreter/stepper.rs
- src/lib.rs
see the individual commit messages for what's going on.
> various fixes and refactorings

- .travis.yml
- Cargo.lock
- Cargo.toml
- src/bin/miri.rs
- tests/compiletest.rs
compiletest doesn't give us this kind of pass, so I created one...
now I can miri-run windows-tests on linux:
```
running tests for target x86_64-pc-windows-gnu
test [miri-pass] tests/run-pass/loops.rs
test [miri-pass] tests/run-pass/arrays.rs
```
The test suite automatically checks for installed targets and runs miri on them.
Also I hope the travis changes now actually break the CI if the tests fail.
I needed compiletest 2.0 for `compiletest::procsrv::dylib_env_var()`
> create a miri-pass test that allows us to run miri for arbitrary targets

- src/error.rs
- src/interpreter/mod.rs
- src/memory.rs
- src/primval.rs
- tests/compile-fail/option_eq.rs
- tests/run-pass/char.rs
> implement char handling

- src/error.rs
- src/interpreter/mod.rs
- src/interpreter/terminator.rs
- src/memory.rs
- tests/compile-fail/invalid_enum_discriminant.rs
- tests/compile-fail/match_char.rs
- tests/compiletest.rs
> use ty::layout::Size and ty::layout::TargetDataLayout

- src/interpreter/mod.rs
- src/memory.rs
I had to paper over the const int -> pointer transformation, because values smaller than the pointer size on big endian systems were written as if they were a pointer sized integer.
We can get rid of the extension traits by inlining the endianess match. This will cause minor code duplication for `read_ptr` (which already contains some duplication b/c of the checks that pointers should not be read as bytes)
This was the first time I used [priroda](https://github.com/oli-obk/miri/tree/priroda) to find a bug in miri xD.
> Use target byte order instead of host byteorder

- src/interpreter/step.rs
This might create confusion, because attempting to execute a statement can cause
arbitrary stackframes to be added for the constants/statics/promoteds required by that
statement. Before this commit, the first statement of the last added stackframe was
executed immediately. Thus there was no way to inspect the state before that first
statement.
> don't execute the first statement of a constant/static/promoted right away

- src/interpreter/mod.rs
- tests/compile-fail/env_args.rs
previously we had something like `std::$insert_mangle_garbage_here$::env::vars`
> use the item path printer that prints user friendly textual paths

- src/interpreter/mod.rs
- src/lib.rs
- src/memory.rs
I thought I'd upstream these changes so I don't need to patch anything when I do a miri update.
> things priroda needs to be public or changed

- src/interpreter/terminator.rs
- src/memory.rs
- tests/compile-fail/out_of_bounds_read.rs
- tests/compile-fail/out_of_bounds_read2.rs
- tests/run-pass/zst.rs
fixes #19
Visual confirmation in priroda. You can see that all the `alloc_id`s are `0` for zsts
> optimize all ZST allocations into one single allocation

- src/interpreter/mod.rs
- src/memory.rs
- src/primval.rs
- tests/run-pass/floats.rs
We can't possibly hope to emulate all target architectures' float quirks. Let's just assert that anyone depending on the minuscule differences between architectures deserves their code to be broken when run through miri.
Instead of running on the host architecture, we can also use one of the following crates for deterministic behaviour not depending on the host architecture
* [exact-float](https://crates.io/crates/exact-float) (a fraction of bignums)
* [accurate](https://crates.io/crates/accurate) (some software based float algorithms)
* [decimal](https://crates.io/crates/decimal) (128 bit soft floats)
Only `accurate` will emulate the computation closely. The other two are much more precise and will thus differ from running the code on the target.
fixes #35
> implement floats by running the ops on the host architecture

- src/bin/miri.rs
- src/error.rs
- src/interpreter/mod.rs
- src/interpreter/step.rs
- src/interpreter/terminator.rs
- src/memory.rs
- tests/compile-fail/oom.rs
- tests/compile-fail/oom2.rs
- tests/compile-fail/stack_limit.rs
- tests/compile-fail/timeout.rs
> limit stack size, memory size and execution time

- Cargo.lock
- src/bin/miri.rs
- src/interpreter/mod.rs
- src/interpreter/step.rs
- src/interpreter/terminator.rs
- src/memory.rs
- src/primval.rs
- tests/compile-fail/oom.rs
- tests/compile-fail/oom2.rs
- tests/compile-fail/stack_limit.rs
- tests/compile-fail/timeout.rs
fixes #32 
I didn't touch the `unimplemented!`, since these probably need to go away by being implememented before moving miri into rustc.
> replace all `unreachable!` and `panic!` calls with `bug!`

- src/interpreter/mod.rs
- src/interpreter/step.rs
- src/interpreter/terminator.rs
- tests/compile-fail/cast_fn_ptr.rs
- tests/compile-fail/execute_memory.rs
- tests/compile-fail/oom.rs
previously we moved to the target block *before* calling a function, so when inspecting
the stack, it appeared as if we were in the first statement of the next block.
this also improves the error spans for some errors
> change the block and stmt position after a function call returns

- src/error.rs
- src/interpreter/cast.rs
- src/interpreter/mod.rs
- src/interpreter/terminator.rs
- src/memory.rs
not sure if this is all of #26
> implement more casts

- src/interpreter/terminator/mod.rs
- tests/run-pass/function_pointers.rs
- tests/run-pass/overloaded-calls-simple.rs
running on rustc run-pass right now to detect regressions
> only split the Fn* arguments in case of closures and function pointers

- src/error.rs
- src/interpreter/cast.rs
- src/interpreter/mod.rs
- src/interpreter/terminator/intrinsics.rs
- src/memory.rs
- src/primval.rs
- tests/compile-fail/null_pointer_deref.rs
- tests/compile-fail/wild_pointer_deref.rs
- tests/compile-fail/zst.rs
- tests/run-pass/cast-rfc0401-vtable-kinds.rs
- tests/run-pass/dst-irrefutable-bind.rs
- tests/run-pass/dst-raw.rs
- tests/run-pass/dst-struct-sole.rs
- tests/run-pass/issue-23261.rs
- tests/run-pass/issue-36278-prefix-nesting.rs
- tests/run-pass/mir_fat_ptr.rs
- tests/run-pass/traits.rs
- tests/run-pass/zst.rs
`size_of_val` is transcribed from rustc and should also be used for `align_of_val`
> enable A<Struct> -> A<Trait> downcasting where `A<Trait>` is a fat pointer

- Cargo.lock
- Cargo.toml
- src/bin/miri.rs
- src/interpreter/mod.rs
- src/interpreter/step.rs
- src/interpreter/terminator/intrinsics.rs
- src/interpreter/terminator/mod.rs
- src/memory.rs
- tests/run-pass/deriving-associated-types.rs
- tests/run-pass/enums.rs
- tests/run-pass/intrinsics-integer.rs
previously enum variants were indexed once to get over the discriminant and again to get the field, but when I wrote the field indexing, I forgot about the discriminant, so the second field was offset by the discrimanant size. It's now done properly and should also be easier to use once https://github.com/rust-lang/rfcs/pull/1450 comes through, since that requires that a downcast doesn't change the pointer.
> fix multi field enum variants and some intrinsics + rustup

- src/interpreter/mod.rs
now only `Arc<T>` -> `Arc<Trait>` casts require an allocation, which is basically the same reason field accesses require allocations.
> don't force allocations for most casts

- src/interpreter/mod.rs
- src/interpreter/terminator/intrinsics.rs
- src/interpreter/terminator/mod.rs
- src/interpreter/vtable.rs
- src/primval.rs
- tests/compile-fail/tag-align-dyn-u64.rs
- tests/run-pass/call_drop_on_array_elements.rs
- tests/run-pass/call_drop_on_fat_ptr_array_elements.rs
- tests/run-pass/call_drop_through_owned_slice.rs
- tests/run-pass/call_drop_through_trait_object.rs
- tests/run-pass/call_drop_through_trait_object_rc.rs
- tests/run-pass/move-arg-2-unique.rs
- tests/run-pass/regions-lifetime-nonfree-late-bound.rs
I haven't touched `TyClosure` and `TyAnon`, not even sure where to start for those...
`TyAnon` could probably be solved by a `MirPass` that replaces all of them with the actual type
Fixes #79
> implement more drop stuff

- src/interpreter/terminator/mod.rs
- tests/run-pass/negative_discriminant.rs
This ensures it gets sign extended correctly.
Fixes #78
> Read discriminant as a signed integer.

- src/error.rs
- src/interpreter/cast.rs
- src/interpreter/mod.rs
- src/interpreter/terminator/intrinsics.rs
- src/interpreter/terminator/mod.rs
- src/interpreter/value.rs
- src/interpreter/vtable.rs
- src/memory.rs
- src/primval.rs
- tests/compile-fail/cast_box_int_to_fn_ptr.rs
- tests/compile-fail/cast_fn_ptr.rs
- tests/compile-fail/cast_int_to_fn_ptr.rs
- tests/compiletest.rs
- tests/run-pass/assume_bug.rs
- tests/run-pass/binops.rs
- tests/run-pass/enum-nullable-const-null-with-fields.rs
- tests/run-pass/issue-30530.rs
- tests/run-pass/last-use-in-cap-clause.rs
- tests/run-pass/sendable-class.rs
- tests/run-pass/simd-intrinsic-generic-elements.rs
- tests/run-pass/small_enum_size_bug.rs
- tests/run-pass/unique-send.rs
> ensure that integers cast to pointers will never point at a valid alloc, not even the zst alloc

- src/error.rs
- src/interpreter/mod.rs
- src/interpreter/step.rs
- src/interpreter/terminator/mod.rs
- src/memory.rs
- tests/compile-fail/modifying_constants.rs
- tests/run-pass/move-arg-3-unique.rs
This should be pretty cool for const eval, since at the end all one has to do is traverse the allocation list and create llvm allocs for all frozen allocations. As long as something is reachable, it gets frozen, everything else is gone.
fixes #83
> deallocate all locals on function exit and transitively freeze constants through pointers

- src/interpreter/mod.rs
Just a leftover piece of code. Right above it we already freeze that memory location
> don't freeze globals twice

- src/interpreter/cast.rs
- src/interpreter/mod.rs
- src/interpreter/terminator/intrinsics.rs
- src/interpreter/terminator/mod.rs
- src/memory.rs
- src/primval.rs
- tests/compiletest.rs
@oli-obk @eddyb I wrote this code a month ago, but just today rebased it over @oli-obk's many changes (:heart:). All the tests are passing, but the code is not fresh in my mind and some nonsense might have crept in with the rebase, so I'd like some external code review before merging.
----
This is a refactoring we've wanted to do for quite a while, ever since @eddyb suggested the current `PrimVal` representation to me. In a future PR I think we will want to go further and remove `PrimValKind` entirely, making all choices based on `Ty`s instead.
I think there are also some more simplifications this refactoring enables that I haven't done yet, e.g. in the casting code.
> Remove PrimValKind field from PrimVal.

- src/bin/miri.rs
- src/error.rs
- src/memory.rs
- src/terminator/intrinsic.rs
- src/terminator/mod.rs
- tests/compiletest.rs
- tests/run-pass/aux_test.rs
- tests/run-pass/auxiliary/dep.rs
Due to `always_encode_mir` we can now run tests that require auxiliary builds.
> rustup to rustc 1.15.0-dev (ace092f56 2016-12-13)

- src/bin/miri.rs
- src/error.rs
- src/memory.rs
- src/terminator/intrinsic.rs
- src/terminator/mod.rs
- tests/compiletest.rs
- tests/run-pass/aux_test.rs
- tests/run-pass/auxiliary/dep.rs
Reverts solson/miri#93 until the required changes end up in a rust nightly release.
> Revert "rustup to rustc 1.15.0-dev (ace092f56 2016-12-13)"

- .gitignore
- Cargo.lock
- Cargo.toml
- src/bin/miri.rs
- src/cast.rs
- src/error.rs
- src/eval_context.rs
- src/lib.rs
- src/memory.rs
- src/operator.rs
- src/step.rs
- src/terminator/intrinsic.rs
- src/terminator/mod.rs
- src/value.rs
as promised, smaller PRs.
This is the rustup extracted from #96
> rustup (i128)

- .gitignore
- .travis.yml
- Cargo.lock
- Cargo.toml
- cargo-miri-test/Cargo.lock
- cargo-miri-test/Cargo.toml
- cargo-miri-test/src/main.rs
- cargo-miri-test/tests/foo.rs
- src/bin/cargo-miri.rs
- src/bin/miri.rs
most code stolen from clippy.
`cargo miri` runs the project through miri instead of on the host machine
`cargo miri test` runs all tests, output is still wonky though (includes build hash and item index)
> add cargo-miri subcommand

- Cargo.lock
- src/eval_context.rs
- src/lib.rs
- src/lvalue.rs
- src/memory.rs
- src/step.rs
- tests/compile-fail/reference_to_packed.rs
- tests/compile-fail/reference_to_packed_unsafe.rs
- tests/run-pass/packed_struct.rs
This is a little roundabout. We mark memory as "packed" or "unaligned" for a single statement, and clear the marking afterwards. This has the advantage over the below mentioned solution, that in the case where no packed structs are present, it's just a single emptyness check of a set instead of heavily influencing all memory access code.
Not sure how to do this better.
We could add some flag to the `Lvalue` type that is set when we encounter some packed struct. But for reading from a packed struct, I'm not sure how to do that properly. Also that would require us to modify all the code related to writing and reading from memory, modifying the alignment checks...
One disadvantage of this solution is the fact that you can cast a pointer to a packed struct to a pointer to a normal struct and …
> implement packed struct field access

- src/terminator/mod.rs
- tests/run-pass/issue-15063.rs
clike enums can't have any fields, so nothing to do here.
> fix drop impls for clike enums

- src/error.rs
- src/eval_context.rs
- src/memory.rs
- src/step.rs
- src/vtable.rs
- tests/compile-fail/modifying_constants.rs
- tests/run-pass/const-vec-of-fns.rs
- tests/run-pass/recursive_static.rs
- tests/run-pass/static_mut.rs
fixes #90
fixes #118
fixes #120
> fix `static mut` dealloc or freeze

- src/eval_context.rs
- src/lvalue.rs
- src/memory.rs
- src/vtable.rs
- tests/run-pass/issue-31267-additional.rs
- tests/run-pass/issue-5917.rs
We can probably expect a static to always be initialized at some point, and thus simply remove the field and test the value for `PrimVal::Undef`, but I wanted to be on the safe side and add a field that has no interaction with other code.
> prevent more deallocations of statics

- src/error.rs
- src/terminator/mod.rs
- tests/compile-fail/env_args.rs
- tests/compile-fail/panic.rs
- tests/compile-fail/unimplemented.rs
This solution is a hack of course, but it allows better testing until we get a handle on generating libstd with full MIR.
~~1638 success, 554 mir not found, 205 crate not found, 141 failed~~
1863 success, 211 mir not found, 205 crate not found, 259 failed
The failures are
```
67 error: miri does not support threading
31 error: miri does not support program arguments
16 error: the evaluated program panicked
14 error: main function not found
10 error: cannot evaluate inline assembly
10 error: a raw memory access tried to access part of a pointer value as raw bytes
8 error: reached the configured maximum execution time
6 error: tried to access memory through an invalid pointer
6 error: can't handle function with PlatformIntrinsic ABI
4 error: can't call C ABI function: …
```
> ignore `print!`, turn `panic!` into a EvalError

- src/terminator/intrinsic.rs
- tests/run-pass/issue-35815.rs
I synced the code with
https://github.com/rust-lang/rust/blob/9c8cdb2923a69177017165a4cdb0e1ea673fc49f/src/librustc_trans/glue.rs#L296
but it wasn't any functional change. Instead, my size calculation was wrong.
> fix size of dst in size_of_val intrinsic

- src/memory.rs
- src/terminator/drop.rs
- src/terminator/mod.rs
- src/vtable.rs
- tests/run-pass/box_box_trait.rs
- tests/run-pass/dst-field-align.rs
fixes #129
the commits are best viewed each on its own
> refactor drop glue and fix Box<Box<Struct>> as Box<Trait>

- tests/compiletest.rs
> It'd be nice to split the "error" count in the OP into true errors and "unsupported", so things like lack of threading don't inflate the error count. I'd also prefer to have them in separate lists if possible.
see updated output in #55
> autogenerate markdown for rustc test suite result

- src/eval_context.rs
- src/lvalue.rs
- src/step.rs
- src/terminator/drop.rs
best reviewed without whitespace: https://github.com/solson/miri/pull/138/files?w=1
> refactor lvalue field projection handling to prepare for fewer `force_allocation`s

- src/eval_context.rs
- src/lvalue.rs
- src/terminator/intrinsic.rs
I ran this on the rustc test suite and found no regressions, but your changes also came in there (and reduced the number of errors significantly), so maybe I don't see something.
more groundwork towards
> src/value.rs:99: expected ptr and vtable, got ByVal(Ptr(Pointer { alloc_id: AllocId(6), offset: 0 }))
> lvalue references into fields of ValPair locals

- src/eval_context.rs
- src/lvalue.rs
- src/terminator/mod.rs
no regressions on rustc test suite detected
We treat arrays like structures with homogeneous fields.
> deduplicate field access logic

- src/terminator/drop.rs
- src/terminator/intrinsic.rs
- src/traits.rs
> move all code accessing vtable internals into the `trait` module

- src/terminator/intrinsic.rs
Oops... I copied-and-pasted from [this comment](https://github.com/solson/miri/pull/148#discussion_r105805697) and apparently did not run the full test suite before pushing.
> fix argument order on check_align()

- src/error.rs
- src/eval_context.rs
- src/lvalue.rs
- src/memory.rs
- src/step.rs
- src/terminator/drop.rs
- src/terminator/mod.rs
- src/traits.rs
- tests/compile-fail/cast_fn_ptr.rs
- tests/run-pass/non_capture_closure_to_fn_ptr.rs
- tests/run-pass/recursive_static.rs
- tests/run-pass/rfc1623.rs
We can now turn non-capturing closures into function pointers (and then back into `Fn` trait objects)
Diff best viewed [without whitespace changes](https://github.com/solson/miri/pull/147/files?w=1)
> rustup to rustc 1.17.0-nightly (60a0edc6c 2017-02-26)

- src/error.rs
- src/eval_context.rs
- src/lvalue.rs
- src/memory.rs
- src/operator.rs
- src/step.rs
- src/terminator/drop.rs
- src/terminator/intrinsic.rs
- src/terminator/mod.rs
- src/traits.rs
- tests/compile-fail/cast_fn_ptr.rs
- tests/compile-fail/overflowing-rsh-6.rs
- tests/run-pass/atomic-access-bool.rs
- tests/run-pass/atomic-compare_exchange.rs
- tests/run-pass/intrinsics-math.rs
- tests/run-pass/non_capture_closure_to_fn_ptr.rs
- tests/run-pass/recursive_static.rs
- tests/run-pass/rfc1623.rs
> Intrinsics and overflow

- src/bin/miri.rs
This takes care of the breakage introduced by https://github.com/rust-lang/rust/pull/40346.
It does not take care of new test failures due to https://github.com/rust-lang/rust/pull/39628,
which is causing infinite `drop_in_place()` recursion.
> partially update for latest rustc nightly

- src/lib.rs
On `rustc 1.17.0-nightly (cab4bff3d 2017-03-21)` I see these warnings:
```
warning: this feature has been stable since 1.17.0. Attribute no longer needed
--> src/lib.rs:5:5
|
5 |     pub_restricted,
|     ^^^^^^^^^^^^^^
|
= note: #[warn(stable_features)] on by default
warning: this feature has been stable since 1.17.0. Attribute no longer needed
--> src/lib.rs:2:5
|
2 |     btree_range,
|     ^^^^^^^^^^^
|
= note: #[warn(stable_features)] on by default
warning: unused or unknown feature
--> src/lib.rs:3:5
|
3 |     collections,
|     ^^^^^^^^^^^
|
= note: #[warn(unused_features)] on by default
```
> remove feature opt-ins that are no longer needed

- src/eval_context.rs
- src/step.rs
- src/terminator/intrinsic.rs
Accounts for the changes in https://github.com/rust-lang/rust/pull/41349.
> update for latest rustc nightly

- tests/compiletest.rs
see updated list of tests in #55
> Also test subdirectories of `rust/src/test/run-pass`

- src/step.rs
Failing a test because of https://github.com/rust-lang/rust/issues/41697
Manually running miri without `-Z dump-mir=all` works fine.
> Update to rustc 1.19.0-nightly (777ee2079 2017-05-01)

- src/eval_context.rs
- tests/run-pass/union.rs
Fixes breakage from https://github.com/rust-lang/rust/pull/41293 and https://github.com/rust-lang/rust/pull/41926.
Still does not pass all tests, due to https://github.com/rust-lang/rust/issues/41697.
> update for latest rustc

- src/terminator/mod.rs
- tests/run-pass/vecs.rs
After https://github.com/rust-lang/rust/pull/40409, we need to implement `__rust_allocate_zeroed()` in order to support vectors constructed like `vec![0; 10]`.
> implement __rust_allocate_zeroed C ABI function

- src/eval_context.rs
- src/step.rs
- src/terminator/intrinsic.rs
Fixes breakage from https://github.com/rust-lang/rust/pull/42015.
> update for upstream changes with ty::ParamEnv

- README.md
The command as given in the README fails with cargo complaining that there are two binaries and it does not know which one to run.
> fix 'cargo run' in README

- src/eval_context.rs
- tests/run-pass/non_capture_closure_to_fn_ptr.rs
Fixes breakage from https://github.com/rust-lang/rust/pull/41917 and https://github.com/rust-lang/rust/pull/42162.
> update for latest nightly rustc

- README.md
- src/bin/miri.rs
- src/error.rs
- src/eval_context.rs
- src/lvalue.rs
- src/memory.rs
- src/step.rs
- src/terminator/mod.rs
- tests/compile-fail/cast_fn_ptr2.rs
- tests/compile-fail/env_args.rs
- tests/compile-fail/oom.rs
- tests/compile-fail/oom2.rs
- tests/compile-fail/stack_limit.rs
- tests/run-pass/aux_test.rs
- tests/run-pass/cast_fn_ptr.rs
- tests/run-pass/catch.rs
- tests/run-pass/format.rs
- tests/run-pass/hello.rs
- tests/run-pass/thread-local-no-dtor.rs
- tests/run-pass/zst.rs
- xargo/Cargo.lock
- xargo/Cargo.toml
- xargo/Xargo.toml
This makes `println!("String literal")` mostly work when miri has a libstd with full MIR at its hands. It still complains about things not being deallocated when miri terminates; that may be related to thread-local dtors not running.
`println!("{}", foo)` still doesn't work because that code does some crazy casts which are currently rejected by miri.
Also I figured out how to use xargo to build a MIR-libstd, so I documented that. Now there's "just" some bugs to be fixed that currently break xargo's libstd support...
> Work with MIR-libstd

- tests/run-pass/send-is-not-static-par-for.rs
- tests/run-pass/thread-local-no-dtor.rs
The `//ignore-windows-gnu` line accomplishes its goal because compiletest [searches for a match of `ignore-windows`](https://github.com/laumann/compiletest-rs/blob/904ec75edeeb67f892c29bf6c7d9ca0b9a809acf/src/header.rs#L57); the `-gnu` part has no effect.
See also, for example, [this rustc test](https://github.com/rust-lang/rust/blob/fd7b44b78e39c71e5049a210a0c84a8931835cc3/src/test/run-pass/i128-ffi.rs#L15) that is ignored on Windows.
> remove unneeded '-gnu' suffix from compiletest ignore directives

- .travis.yml
- README.md
- src/bin/cargo-miri.rs
- src/bin/miri.rs
- tests/compile-fail/stack_limit.rs
- tests/compiletest.rs
I have zero experience with Travis, so I will see whether my script makes any sense when Travis checks this PR. Also, I don't think this entire multi-platform-testing stuff will work out here and I am not sure what is the best way to fix that.
Someone should look at the situation with these two environment variables (RUST_SYSROOT vs. SYSROOT).
> run test suite also against libstd with full MIR 

- src/error.rs
- src/eval_context.rs
- src/lvalue.rs
- src/step.rs
(This is work-in-progress, test suite currently fails.)
This changes the stack slots to be of type `Option<Value>`, where `None` represents the case of a "dead" stack slot. `StorageLive`/`StorageDead` mark slots as live/dead. So this also effectively defines the semantics of these commands. Right now, the semantics are as follows:
* When a function is called, miri checks which local variables have StorageLive/StorageDead call on them. The ones that do are initialized as "dead", while the ones that don't are initialized as "live (undef value)".
* When a local variable is accessed (read from or written to), and it is dead, that's an error.
* When StorageLive is run, and the variable is already live, that's an error. Otherwise, the variable becomes live.
* When StorageDead is run, the …
> interpret StorageLive & StorageDead, and check dead stack slots are not used

- src/eval_context.rs
- src/step.rs
- src/terminator/intrinsic.rs
- src/traits.rs
Fixes breakage from https://github.com/rust-lang/rust/pull/42189.
> update for upstream ParamEnv changes

- src/error.rs
- src/eval_context.rs
- src/lvalue.rs
- src/memory.rs
- src/operator.rs
- src/terminator/intrinsic.rs
- src/terminator/mod.rs
- src/traits.rs
- src/value.rs
- tests/compile-fail/out_of_bounds_ptr_1.rs
- tests/compile-fail/out_of_bounds_ptr_2.rs
- tests/compile-fail/out_of_bounds_read.rs
- tests/compile-fail/out_of_bounds_read2.rs
- tests/compile-fail/overflowing-lsh-neg.rs
- tests/compile-fail/pointer_byte_read_1.rs
- tests/compile-fail/pointer_byte_read_2.rs
- tests/compile-fail/ptr_bitops.rs
- tests/compile-fail/ptr_offset_overflow.rs
- tests/run-pass/aux_test.rs
- tests/run-pass/drop_empty_slice.rs
- tests/run-pass/hashmap.rs
- tests/run-pass/iter_slice.rs
- tests/run-pass/ptr_arith_offset.rs
- tests/run-pass/ptr_arith_offset_overflow.rs
- tests/run-pass/ptr_int_casts.rs
- tests/run-pass/ptr_offset.rs
- tests/run-pass/u128.rs
This started out with the intention of making the following test case pass:
```rust
fn eq_ref<T>(x: &T, y: &T) -> bool {
x as *const _ == y as *const _
}
fn main() {
// int-ptr-int
assert_eq!(1 as *const i32 as usize, 1);
{   // ptr-int-ptr
let x = 13;
let y = &x as *const _ as usize;
let y = y as *const _;
assert!(eq_ref(&x, unsafe { &*y }));
}
}
```
However, various other pointer-related things came up, and they are now also in this PR. Specifically:
* Offset and the offset intrinsic do bounds checks. There's a special case here ti always permit offsetting by 0, mostly because rustc relies on this being allowed. The discussion whether that is true did not reach a firm conclusion yet.
* Test that pointer bytes cannot be observed via pointer casts.
* Fix arith_offset, which forgot to …
> Various pointer-related things

- .travis.yml
- README.md
This means we can remove the work-around of manually marking things as executable.
> Rustup 1.4 fixed the permissions of the extracted files

- tests/run-pass/rc.rs
This uses some pointer arithmetic based on field offsets.
> Test the Rc::{into,from}_raw roundtrip

- Cargo.lock
- tests/run-pass/aux_test.rs
https://github.com/laumann/compiletest-rs/issues/65 is fixed in the latest release. (Thanks @laumann!)
> update compiletest and remove obsolete comment

- src/step.rs
Fixes breakage from https://github.com/rust-lang/rust/pull/39409.
> handle EndRegion as no-op

- src/cast.rs
- src/error.rs
- src/eval_context.rs
- src/lvalue.rs
- src/memory.rs
- src/operator.rs
- src/step.rs
- src/terminator/drop.rs
- src/terminator/intrinsic.rs
- src/terminator/mod.rs
- src/traits.rs
- src/value.rs
- tests/compile-fail/cast_box_int_to_fn_ptr.rs
- tests/compile-fail/cast_int_to_fn_ptr.rs
- tests/compile-fail/null_pointer_deref.rs
- tests/compile-fail/wild_pointer_deref.rs
- tests/run-pass/loop-break-value.rs
- tests/run-pass/slice-of-zero-size-elements.rs
- tests/run-pass/union-overwrite.rs
- tests/run-pass/zero-sized-binary-heap-push.rs
> Get rid of the integer allocation

- README.md
vecs.rs got moved in https://github.com/solson/miri/pull/200
> update xargo usage example for new location of vecs.rs

- src/error.rs
- src/eval_context.rs
- src/terminator/mod.rs
- tests/compile-fail/pointers_to_different_allocations_are_unorderable.rs
Do not allow offset-by-0 on other out-of-bounds or dangling pointers.
> Allow any offset on integer and ZST pointers

- src/eval_context.rs
- src/lvalue.rs
- src/step.rs
- src/terminator/intrinsic.rs
- tests/compile-fail/pointer_byte_read_1.rs
Undoes #146 and #139 because this was just a lot of overhead working with the field accesses. They also only "helped" when the lvalue that was produced was immediately read again.
We should move to doing an lvalue-read operation similar to https://github.com/solson/miri/pull/139/files#diff-3596aeeadedc2ed352f2c376852f8fb7L117 which optimizes through those cases where you don't want to have a pointer in the end, but only a primval. So basically primval rvalues?
I did not reinstate the mentioned lvalue-read, since i want to get this PR through first and then write a more advanced version that supports more cases.
> Remove the `field` field from `Lvalue::Local`

- src/eval_context.rs
- src/terminator/mod.rs
Fixes breakage from https://github.com/rust-lang/rust/pull/42417.
> update for upstream changes to TyFnDef

- cargo-miri-test/Cargo.lock
- cargo-miri-test/Cargo.toml
- cargo-miri-test/src/main.rs
- src/bin/cargo-miri.rs
Fixes #229.
For dependencies, invokes plain `rustc` with `-Z always-encode-mir`.
Also removes `dep_path`, as in https://github.com/Manishearth/rust-clippy/commit/8f88ead7d65ad9a80fa2535dfce83458efda3a7b.
> get cargo-miri to work

- Cargo.lock
Pulls in https://github.com/laumann/compiletest-rs/pull/68 which fixes breakage from https://github.com/rust-lang/rust/pull/42219.
> update compiletest dependency

- src/eval_context.rs
- src/lvalue.rs
- src/memory.rs
- src/terminator/intrinsic.rs
- src/terminator/mod.rs
- src/value.rs
Before we also checked whether pointers had alloc_ids when we created rvalue references
fixes #228
> Only check pointers when dereferencing

- src/error.rs
- src/eval_context.rs
- src/lib.rs
- src/lvalue.rs
- src/memory.rs
- src/operator.rs
- src/step.rs
- src/terminator/drop.rs
- src/terminator/intrinsic.rs
- src/terminator/mod.rs
- src/traits.rs
- src/value.rs
I renamed the pointers to allocations as `MemoryPointer` and created a wrapper type `Pointer` around  `PrimVal` to be used wherever we currently use `PrimVal` but named the variable `ptr`.
> Use a wrapper type to differentiate between `PrimVal` and pointers

- src/terminator/mod.rs
since <https://github.com/rust-lang/rust/pull/43072> was merged. So we can remove a horrible hack. :)
> hooking mmap is no longer needed

- src/memory.rs
- tests/compile-fail/reading_half_a_pointer.rs
Three uses of `get_bytes_unchecked`, one of them got it wrong. ;)
> Memory::read_ptr has to check for relocations on the edges

- src/eval_context.rs
- src/lvalue.rs
- src/memory.rs
- src/step.rs
- src/terminator/drop.rs
- src/terminator/intrinsic.rs
- src/terminator/mod.rs
- src/value.rs
- tests/run-pass/packed_struct.rs
We now track in the lvalue whether what we computed is expected to be aligend or not, and then set some state in the memory system accordingly to make it (not) do alignment checks. Note that I did not understand the old handling completely, so I am not sure if this is correct -- but from the part that I did understand, this should actually improve things because alignment checks are disabled on a much more fine-grained basis.
Furthermore, I'd like to know if you are willing to accept this trick I am using that avoids passing "is_aligned" to every single function on the memory: Instead, store such things in the state. This is certainly less clean, but may still overall be nicer. If you *are* willing to accept this, I will probably also use this in my MIR validation branch where each memory …
> Re-do packed memory accesses

- src/value.rs
The only remaining `unsafe` in miri is `copy_nonoverlapping` :)
> use libstd methods for floating-point <-> bytes conversion

- src/memory.rs
- tests/compile-fail/reallocate-dangling.rs
This was mentioned but not fixed in #245.
> Remove reundant dangling checks in {r,d}eallocate

- src/cast.rs
- src/eval_context.rs
- src/memory.rs
- tests/compile-fail/int_ptr_cast.rs
- tests/compile-fail/int_ptr_cast2.rs
- tests/compile-fail/reference_to_packed.rs
- tests/compile-fail/unaligned_ptr_cast.rs
- tests/compile-fail/unaligned_ptr_cast2.rs
This breaks creating unaligned raw pointers via `&packed.field as *const _`, which needs to be legal.
Also it doesn't seem like LLVM still relies on this, see
* https://github.com/solson/miri/issues/244#issuecomment-315563640
* https://internals.rust-lang.org/t/rules-for-alignment-and-non-nullness-of-references/5430/16
We probably want to handle this invariant like the others that validation is concerned with, and only
check it on function boundaries for now.
> No longer check aligment and non-NULLness on `&`

- src/lvalue.rs
- tests/compile-fail/never_say_never.rs
Funny enough, the correspond test still fails -- thanks to miri checking the storage liveness annotations. ;)
Fixes #261
> remove ad-hoc 'never' type check in read_lvalue

- rustc_tests/Cargo.lock
- rustc_tests/Cargo.toml
- rustc_tests/src/main.rs
- tests/compiletest.rs
- tests/run-pass/traits.rs
This lets us do "cargo test miri" to skip the rustc tests -- less waiting. :)
Unfortunately, "cargo run" will run different tests in parallel, messing up the output. That makes this less useful than it should be. One can set `RUST_TEST_TASKS=1` to "fix" this, but that's not great.
So, this PR is more a "up for discussion" kind of thing right now. Let me know what you think.
> Split up test suite

- src/memory.rs
- src/terminator/intrinsic.rs
- src/terminator/mod.rs
- tests/compile-fail/unaligned_ptr_cast_zst.rs
- tests/run-pass-fullmir/vecs.rs
We still skip alignment and non-NULL tests for `copy` and `write_bytes` intrinsics when nothing is copied/written. There is code in libstd that relies on this. Also, considering that these are intrinsics rather than "primitive" loads/stores, LLVM may also be more relaxed there.
Ideally, we'd know which LLVM intrinsics these rustc intrinsics lower to and what exactly the contract is for these.
> Always test alignment in memory.rs

- src/librustc_mir/interpret/cast.rs
- src/librustc_mir/interpret/eval_context.rs
- src/librustc_mir/interpret/lvalue.rs
- src/librustc_mir/interpret/memory.rs
- src/librustc_mir/interpret/operator.rs
- src/librustc_mir/interpret/step.rs
- src/librustc_mir/interpret/terminator/mod.rs
- src/librustc_mir/interpret/traits.rs
- src/librustc_mir/interpret/value.rs
- tests/run-pass/ptr_int_casts.rs
`(-1i32) as usize as *const i32 as usize` would yield 0xff. That's clearly wrong. Not it yields what we would expect.
I also did some more refactoring of casting in general as I wasn't satisfied with how pointers were handled.
> Fix ptr-int-casts

- src/librustc_mir/interpret/eval_context.rs
- tests/run-pass-fullmir/unsized-tuple-impls.rs
I don't actually know what I am doing when I touch this unsized types code, but it makes the test suite pass. ;)
> fix size_of_val on unsized tuples

- miri/bin/miri.rs
- src/librustc_mir/interpret/eval_context.rs
- src/librustc_mir/interpret/memory.rs
- src/librustc_mir/interpret/step.rs
- src/librustc_mir/interpret/validation.rs
- src/librustc_mir/interpret/value.rs
- tests/compile-fail/cast_box_int_to_fn_ptr.rs
- tests/compile-fail/cast_int_to_fn_ptr.rs
- tests/compile-fail/execute_memory.rs
- tests/compile-fail/fn_ptr_offset.rs
- tests/compile-fail/invalid_enum_discriminant.rs
- tests/compile-fail/memleak_rc.rs
- tests/compile-fail/panic.rs
- tests/compile-fail/static_memory_modification2.rs
- tests/compile-fail/zst2.rs
- tests/compile-fail/zst3.rs
- tests/compiletest.rs
- tests/run-pass-fullmir/regions-mock-trans.rs
- tests/run-pass/rc.rs
- tests/run-pass/recursive_static.rs
- tests/run-pass/send-is-not-static-par-for.rs
- tests/run-pass/std.rs
- xargo/build.sh
Once the next nightly has <https://github.com/rust-lang/rust/pull/43403>, this PR should make things compile again. :)
> Update MIR validation and test it

- Cargo.lock
- miri/lib.rs
- src/librustc_mir/Cargo.toml
- src/librustc_mir/interpret/error.rs
- src/librustc_mir/interpret/eval_context.rs
Only collect backtrace when RUST_BACKTRACE is non-empty. Also, resolve symbols lazily when printing.
> Backtrace performance

- miri/fn_call.rs
- miri/intrinsic.rs
- miri/lib.rs
- miri/memory.rs
- src/librustc_mir/interpret/const_eval.rs
- src/librustc_mir/interpret/error.rs
- src/librustc_mir/interpret/eval_context.rs
- src/librustc_mir/interpret/lvalue.rs
- src/librustc_mir/interpret/machine.rs
- src/librustc_mir/interpret/memory.rs
- src/librustc_mir/interpret/mod.rs
- src/librustc_mir/interpret/operator.rs
- src/librustc_mir/interpret/step.rs
- src/librustc_mir/interpret/terminator/drop.rs
- src/librustc_mir/interpret/terminator/mod.rs
- src/librustc_mir/interpret/traits.rs
- src/librustc_mir/interpret/validation.rs
- src/librustc_mir/interpret/value.rs
- tests/compile-fail/fn_ptr_offset.rs
- tests/run-pass/packed_static.rs
I did this for functions, since they were already separate. I decided on simply using the first two bits of the `u64` in `AllocId` to distinguish between locals (or heap), statics and functions. That still leaves `2^62 - 1` local allocations before we run into trouble.
Also statics can't be `ByVal` anymore, which found a bug in the `sysconf` code.
cc #285
> Prepare for splitting off static alloc ids from local alloc ids

- .travis.yml
- Cargo.toml
1. Speeds up the common compilation path (no serde in the dependency tree)
2. Stage 1 rustc is enough (no serde -> no custom derive)
fixes #293
Sadly doesn't change anything about #166
> Make cargo_miri a feature

- tests/compiletest.rs
I had to weave some env vars over from rustc, but it works now both within rustc and here.
> Get the test suite working inside the rustc test suite

- src/librustc_mir/interpret/memory.rs
- src/librustc_mir/interpret/value.rs
- tests/run-pass-fullmir/integer-ops.rs
- tests/run-pass/pointers.rs
- tests/run-pass/thread-local.rs
Now that <https://github.com/rust-lang/rust/pull/43748> has been merged, we can enable validation in this test. (However, we have to wait for the next nightly.)
> enable a test that waited for a rustc fix

- src/librustc_mir/interpret/eval_context.rs
- tests/run-pass/closure-field-ty.rs
> Handle closures in get_field_ty

- miri/fn_call.rs
- miri/intrinsic.rs
- miri/lib.rs
- src/librustc_mir/interpret/const_eval.rs
- src/librustc_mir/interpret/eval_context.rs
- src/librustc_mir/interpret/lvalue.rs
- src/librustc_mir/interpret/machine.rs
- src/librustc_mir/interpret/mod.rs
- src/librustc_mir/interpret/operator.rs
- src/librustc_mir/interpret/terminator/drop.rs
- src/librustc_mir/interpret/terminator/mod.rs
This is a pure refactoring and does not touch any logic.
It is a prerequisite for getting rid of our handrolled boilerplate around closure and drop calls.
I also think it makes the "interesting" cases where we fiddle with values' types more explicit.
> Refactoring: Couple values and types into an object when passed around together

- src/librustc_mir/interpret/eval_context.rs
The miri code for `fulfill_obligation()` was copied from librustc_trans, which at the time did not expose the function. As of https://github.com/rust-lang/rust/pull/41355, the function has been moved into librustc and is exposed, so we should switch to using it.
> use rustc version of fulfill_obligation now that we can

- Cargo.lock
- miri/bin/miri.rs
- miri/fn_call.rs
- miri/intrinsic.rs
- rustc_tests/Cargo.lock
- rustc_tests/src/main.rs
- src/librustc_mir/interpret/cast.rs
- src/librustc_mir/interpret/eval_context.rs
- src/librustc_mir/interpret/memory.rs
- src/librustc_mir/interpret/mod.rs
- src/librustc_mir/interpret/step.rs
- src/librustc_mir/interpret/terminator/mod.rs
- src/librustc_mir/interpret/traits.rs
- src/librustc_mir/interpret/validation.rs
- src/librustc_mir/interpret/value.rs
- tests/compile-fail/null_pointer_deref.rs
- tests/compile-fail/wild_pointer_deref.rs
- tests/compiletest.rs
- tests/run-pass-fullmir/integer-ops.rs
As described in <https://github.com/solson/miri/pull/309#issuecomment-324705299>.
Notice that while the specialized read/write methods for float and bool were more correct in terms of alignment, the write methods were not actually used -- so we already did not handle that correctly. We should find another solution. I guess we could either pass alignment to `{read,write}_primval`, or at some point check that the platform ABI satisfies our assumptions.
I am not very happy with the writing part of this. In `eval_context`, reading and writing are strangely asymmetric. Reading has `try_read_value`, which looks at the type and then makes the right decision. Writing, on the other hand, has nothing like that -- leading to the hack I had to add in `write_value_to_ptr`. I don't know `eval_context` …
> Memory API refactoring

- src/librustc_mir/interpret/eval_context.rs
- src/librustc_mir/interpret/memory.rs
- src/librustc_mir/interpret/validation.rs
- tests/run-pass/dst-field-align.rs
- tests/run-pass/mir_coercions.rs
- tests/run-pass/non_capture_closure_to_fn_ptr.rs
- tests/run-pass/subslice_array.rs
- tests/run-pass/tuple_like_enum_variant_constructor_pointer_opt.rs
Fixes breakage from https://github.com/rust-lang/rust/commit/8bdfd8a0036d3594efd9c90a328afa41a1ba359d.
> update for upstream rename: CodeExtent -> Scope

- miri/intrinsic.rs
- tests/run-pass-fullmir/from_utf8.rs
> Implement `align_offset` intrinsic and thus enabling `from_utf8`

- src/librustc_mir/interpret/eval_context.rs
- src/librustc_mir/interpret/lvalue.rs
- src/librustc_mir/interpret/memory.rs
- src/librustc_mir/interpret/mod.rs
- src/librustc_mir/interpret/validation.rs
- src/librustc_mir/lib.rs
- tests/compile-fail/panic.rs
- tests/compile-fail/validation_lock_confusion.rs
- tests/compile-fail/zst2.rs
- tests/compile-fail/zst3.rs
- tests/run-pass-fullmir/hashmap.rs
- tests/run-pass/btreemap.rs
- tests/run-pass/many_shr_bor.rs
- tests/run-pass/zst2.rs
> Valiation: Identify write locks using an abstract lvalue

- miri/lib.rs
- src/librustc_mir/interpret/const_eval.rs
- src/librustc_mir/interpret/machine.rs
- src/librustc_mir/interpret/step.rs
> Remove `#[linkage(foo)]` statics from core miri

- appveyor.yml
- miri/fn_call.rs
- tests/compiletest.rs
- tests/run-pass-fullmir/catch.rs
- tests/run-pass-fullmir/foreign-fn-linkname.rs
- tests/run-pass-fullmir/format.rs
- tests/run-pass-fullmir/from_utf8.rs
- tests/run-pass-fullmir/hashmap.rs
- tests/run-pass-fullmir/heap.rs
- tests/run-pass-fullmir/hello.rs
- tests/run-pass-fullmir/integer-ops.rs
- tests/run-pass-fullmir/issue-15080.rs
- tests/run-pass-fullmir/issue-3794.rs
- tests/run-pass-fullmir/loop-break-value.rs
- tests/run-pass-fullmir/move-arg-2-unique.rs
- tests/run-pass-fullmir/regions-mock-trans.rs
- tests/run-pass-fullmir/u128.rs
- tests/run-pass-fullmir/unsized-tuple-impls.rs
- tests/run-pass-fullmir/vecs.rs
- tests/run-pass/issue-17877.rs
We seriously need to give compiletest a `compile-pass` test kind... These hacks are getting out of hand
> Windows support in the test suite + appveyor

- README.md
However, AppVeyor URL <https://ci.appveyor.com/project/solson/miri> does not work for me:
> Project not found or access denied.
Same problem for clippy. Is the URL wrong, or are the permissions broken?
> README: show AppVeyor status

- miri/fn_call.rs
- miri/lib.rs
- src/librustc_mir/interpret/const_eval.rs
- src/librustc_mir/interpret/eval_context.rs
- src/librustc_mir/interpret/lvalue.rs
- src/librustc_mir/interpret/machine.rs
- src/librustc_mir/interpret/step.rs
- tests/compile-fail/oom2.rs
This turns out to work even for mir-free libstd.
> Call exchange_malloc for box stmt

- Cargo.toml
Miri does not need to maintain a workspace anymore. Also, keeping miri a
workspace conflicts with rustc's own workspace.
> Remove the [workspace] section.

- miri/bin/miri.rs
- miri/fn_call.rs
- miri/lib.rs
> Alloc api fix and tmp disable validation_op because of ICE

- miri/fn_call.rs
- miri/lib.rs
that function has been removed
> [LOCKSTEP UPGRADE #45525] stop using Instance::def_ty

- src/bin/miri.rs
- tests/run-pass/aux_test.rs
- tests/run-pass/auxiliary/dep.rs
I think that's really not miri's job. If we really want to keep these inter-crate tests, I think we should either (a) make them `cargo-miri` tests, and let cargo handle the other crates, or (b) attempt to fix compiletest so that one can run different binaries for auxiliary builds than for the final build.
Fixes #357
> stop producing binaries

- rustc_tests/Cargo.lock
- rustc_tests/src/main.rs
- src/bin/miri.rs
This should fix the breakage incurred by the next to-be-relased nightly.
> fix for latest rust nightly

- src/bin/miri.rs
Previously it would print `need to specify RUST_SYSROOT env var or use rustup or multirust`, even when one did `RUST_SYSROOT=... path/to/binary/miri`. Not very helpful.
> clarify error message when sysroot was not found

- Cargo.toml
- build.rs
- src/bin/cargo-miri.rs
@shepmaster does this look right?
```
$ target/debug/cargo-miri --version
miri 0.1.0 (f925e5d 2018-09-16)
```
I am having some trouble triggering a rebuild when the commit changes ([it doesn't really trigger](https://github.com/rustyhorde/vergen/issues/7)), but that should not be a problem for playground which always does a clean build.
Fixes https://github.com/solson/miri/issues/452
> cargo miri: show version number

- src/bin/miri.rs
- src/lib.rs
- tests/compiletest.rs
- tests/run-pass/btreemap.rs
- tests/run-pass/call_drop_through_owned_slice.rs
- tests/run-pass/issue-29746.rs
- tests/run-pass/rc.rs
- tests/run-pass/ref-invalid-ptr.rs
- tests/run-pass/sendable-class.rs
- tests/run-pass/unique-send.rs
But add a flag to disable it and use that for some run-pass tests. compile-fail does not do validation yet.
NOTE: This is a PR against the rustup branch, because it's based on top of that branch.
> Enable enforcing the validity invariant per default

- src/bin/cargo-miri.rs
In #482 there was some question about what my argument-handling logic was doing. This adds comments to explain it.
> add some comments to clarify command-line argument munging in #482

- .travis.yml
- cargo-miri-test/run-test.py
Also enable all the stuff again that I accidentally disabled with the last PR...
> rewrite cargo-miri test in Python

- .travis.yml
- Cargo.toml
- README.md
- appveyor.yml
- cargo-miri-test/run-test.py
- src/bin/cargo-miri.rs
- src/lib.rs
- xargo/Cargo.lock
- xargo/Cargo.toml
- xargo/Xargo.toml
- xargo/build.sh
Cc https://github.com/solson/miri/issues/520
> Automatically build libstd

- src/bin/cargo-miri.rs
This should fix https://github.com/integer32llc/rust-playground/issues/438
> do not even look for cargo metadata in 'cargo miri setup'

- src/bin/cargo-miri.rs
We want libstd to be as stripped-down as we can make it.
Currently, this does not make a difference, but it might in the future (e.g. when/if https://github.com/rust-lang/rust/pull/56435 lands).
> build libstd with minimal features

- src/lib.rs
With https://github.com/rust-lang/rust/pull/56275 landed, we don't need a whitelist any more. :) (with the next nightly, anyway)
> We don't need no whitelist

- tests/run-pass/stacked-borrows.rs
Also see https://github.com/rust-lang/rust/issues/56604
> add FIXME test for coercing &mut to *const

- .travis.yml
- README.md
- tests/compiletest.rs
Target auto-detection is pretty fragile (as e.g. #556 shows), and in a recent change to support the fact that xargo's foreign sysroot contains a native target (but not compiled with our flags), I broke running the test suite against a locally compiled rustc.
Instead of being smart, let the user specify the target to run the test suite against.
> do not auto-detect the targets in the sysroot, instead specify target manually through env var

- Cargo.toml
This is necessary for miri to play nice with feature selection of dependencies in the rust repo.
cc @alexcrichton
> Add rustc-workspace-hack.

- tests/run-pass/function_pointers.rs
- tests/run-pass/mir_coercions.rs
So... This is how we'd have to change the tests if we're keeping with `main as fn() != main as fn()`. If we want the original behaviour back in miri, but not const eval, I can also change our comparison code to special case function pointers.
> Adjust tests for funciton pointer changes

- Cargo.toml
Otherwise we get
```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/r/src/rust/rustc.3/src/tools/miri/Cargo.toml
workspace: /home/r/src/rust/rustc.3/Cargo.toml
```
> we can't have profiles because we are also in the rustc worksapce

- Cargo.toml
This should fix the fallout from https://github.com/rust-lang/rust/pull/58689.
> the stable part of compiletest_rs is enough

- tests/run-pass/2phase.rs
The compiler now rejects one of the examples with #![feature(nll)].
Use edition:2018 and suppress the lint.
> Use edition flag for 2phase test

- tests/run-pass/async-fn.rs
to let https://github.com/rust-lang/rust/pull/59119 land
> temporarily ignore async fn test

- Cargo.toml
- benches/helpers/miri_helper.rs
- src/bin/miri-rustc-tests.rs
- src/bin/miri.rs
- src/fn_call.rs
- src/lib.rs
- tests/compile-fail/getrandom.rs
- tests/run-pass/hashmap.rs
Part of #653
This allows us to properly implement getrandom(),
which unlocks the default HashMap type (e.g. HashMap<K, V>)
with RandomState)
This commit adds a new '-Zmiri-seed=<seed>' option. When present,
this option takes a 64-bit hex value, which is used as the seed
to an internal PRNG. This PRNG is used to implement the 'getrandom()'
syscall.
When '-Zmiri-seed' is not passed, 'getrandom()' will be disabled.
> Implement non-deterministc mode

- src/operator.rs
- tests/compile-fail/ptr_eq_integer.rs
- tests/run-pass/vecs.rs
Allow comparing "real" pointers with whatever gets returned from `NonNull::dangling` (and make it not equal). Such comparisons regularly arise in real code, so this makes Miri more useful.
@oli-obk what do you think?
We should revisit this once https://github.com/rust-lang/miri/issues/224 is done.
> be pragmatic about ptr-int comparisons, for now

- src/fn_call.rs
- test-cargo-miri/run-test.py
- test-cargo-miri/tests/test.rs
- travis.sh
This should help users of `rand`. It doesn't help for `HashMap` though, see https://github.com/rust-lang/rust/pull/60156 for that.
> implement SecRandomCopyBytes for macOS RNG

- README.md
Also separate definite bugs from stacked-borrows-is-not-yet-official bugs.
(I considered turning a shared ref into a mutable a definite bug, as that is a principle that seems fairly unambiguous.)
> trophy case: add rand

- src/stacked_borrows.rs
This should fix an issue in one of @matthewjasper's experimental branches.
> SharedReadOnly reborrows are never weak

- tests/compile-fail/stacked_borrows/illegal_write6.rs
Add the example from https://github.com/rust-lang/unsafe-code-guidelines/issues/87, just to be sure.
> add arielby's example

- src/stacked_borrows.rs
- test-cargo-miri/test.stdout.ref
- test-cargo-miri/test.stdout.ref2
- test-cargo-miri/tests/test.rs
- tests/compile-fail/stacked_borrows/deallocate_against_barrier.rs
- tests/compile-fail/stacked_borrows/interior_mut1.rs
- tests/run-pass/stacked-borrows/interior_mutability.rs
This gives up on "two-phase borrows as weak reborrows", which is nice because then we can remove the entire idea of "weak granting/reborrows", and the double-reborrowing upon creating a two-phase borrow.
However, this also makes two-phase borrows even weaker: they now basically allow any aliasing references. This is probably weaker than what we want.
> test and support two-phase reborrows of raw pointers

- src/stacked_borrows.rs
I synced all impls except for the one that only drops elements that match a filter
> Use `drain` instead of manually rolling it ourselves

- test-cargo-miri/Cargo.lock
- test-cargo-miri/Cargo.toml
- test-cargo-miri/src/main.rs
- test-cargo-miri/tests/test.rs
Currently fails, blocked on https://github.com/rust-random/rand/issues/779
> test rand a bit more

- src/fn_call.rs
- tests/run-pass/intrinsics-math.rs
Implements missing cbrt/hypot function calls as per #667. 
Note that this PR is in progress -- I still need to determine what other function calls are missing.
> [WIP] Implement cbrt and hypot function calls

- src/intrinsic.rs
- tests/compile-fail/div-by-zero-3.rs
- tests/compile-fail/exact_div1.rs
- tests/compile-fail/exact_div2.rs
- tests/compile-fail/exact_div3.rs
- tests/compile-fail/exact_div4.rs
- tests/compile-fail/unchecked_add1.rs
- tests/compile-fail/unchecked_add2.rs
- tests/compile-fail/unchecked_mul1.rs
- tests/compile-fail/unchecked_mul2.rs
- tests/compile-fail/unchecked_sub1.rs
- tests/compile-fail/unchecked_sub2.rs
- tests/run-pass/intrinsics-integer.rs
Also test that we detect the UB in unchecked intrinsics.
>  implement unchecked_{add,sub,mul} intrinsics 

- .appveyor.yml
- .travis.yml
With this, we should run the Travis tests (Linux+macOS) in PRs, and run that plus AppVeyor in bors.
> adapt CI for bors

- miri
Before, running `./miri` without arguments gave
'./miri: 92: shift: can't shift that many' if run with /bin/sh,
or no output at all when run with bash (because of the `set -e` at the top).
Although that gives some indication of the error, it's not as helpful as
showing the usage.
> Show usage if run without arguments

- src/eval.rs
- src/fn_call.rs
- src/intptrcast.rs
- src/machine.rs
- tests/compile-fail/intptrcast_alignment_check.rs
- Make `align_addr` not offset by `align` for no reason.
- Add some random slack between allocations to give them the chance to not be aligned.
Cc @christianpoveda 
Fixes https://github.com/rust-lang/miri/issues/791
> tweak inttoptr allocation behavior

- src/fn_call.rs
- src/intptrcast.rs
- src/lib.rs
- src/machine.rs
- test-cargo-miri/Cargo.lock
- test-cargo-miri/Cargo.toml
- test-cargo-miri/run-test.py
- test-cargo-miri/src/main.rs
- test-cargo-miri/test.stdout.ref
- test-cargo-miri/test.stdout.ref2
- test-cargo-miri/tests/test.rs
Also make some magic numbers into proper global constants.
> support num_cpus crate and test that

- tests/run-pass/issue-30530.rs
After https://github.com/rust-lang/rust/pull/62228, this will be linted against (and causes the test to fail). (This blocks https://github.com/rust-lang/rust/pull/62228.)
> Fix `unused_must_use` inside `Box`

- src/operator.rs
- src/shims/foreign_items.rs
Also avoid Memory::get if we just need to know align/size.
I audited all uses of `alloc_id`; the rest should be fine (and we can kill a bunch of them once https://github.com/rust-lang/rust/pull/62257 lands).
> don't call Memory::get without checking the pointer first

- src/helpers.rs
- src/shims/foreign_items.rs
- src/shims/tls.rs
Comparing pointers should be done more carefully than that
> avoid Scalar::is_null_ptr, it is going away

- src/shims/foreign_items.rs
This is the Miri side of https://github.com/rust-lang/rust/pull/62257
> use Memory::read_c_str, avoid a few to_ptr

- src/shims/intrinsics.rs
Finally. :D
However, to land this we'll need to fix the intptrcast issues that block https://github.com/rust-lang/miri/pull/803.
> uninit intrinsic is gone

- tests/run-pass/async-fn.rs
`await_macro` is now unsupported so we should remove it.
Failed in https://github.com/rust-lang/rust/pull/63141
r? @RalfJung
> Remove `await_macro`

- src/helpers.rs
- src/shims/dlsym.rs
- src/shims/foreign_items.rs
This matches, for example, the `getrandom` syscall.
> gen_random helper: move ptr argument to front

- src/helpers.rs
The Linux kernel will handle a null pointer passed to 'getrandom'
without error, as long as the length is also 0. The `getrandom` crate
relies on this behavior: https://github.com/rust-random/getrandom/blob/ab44edf3c7af721a00e22648b6c811ccb559ba81/src/linux_android.rs#L26
Since it works fine on the actual kernel (and should continue to, due to
the kernel's backwards-compatibility guarantees), Miri should support it
as well.
> Allowing passing a null pointer to getrandom() when length is 0

- test-cargo-miri/Cargo.lock
With both https://github.com/rust-random/getrandom/pull/74 and https://github.com/rust-lang/miri/pull/884 having landed, this should work now.
> test-cargo-miri: cargo update

- src/shims/intrinsics.rs
This reverts commit fa290f1a481b0f98ed1de06206e643af8e04acd5.
Uninit is [being reinstated](https://github.com/rust-lang/rust/pull/63343) because it breaks some broken code.
> Revert "uninit intrinsic is gone"

- src/bin/cargo-miri.rs
Rust bootstrap needs it for the CARGO env var handling.
> bump xargo version

- src/shims/foreign_items.rs
Closes https://github.com/rust-lang/miri/issues/821
r? @RalfJung
> Use ldexp from cmath instead

- tests/run-pass/async-fn.rs
- tests/run-pass/generator.rs
See discussion in https://github.com/rust-lang/rust/pull/63035.
> Add generator, async tests with uninhabited saved local

- miri
With the test-miri flag gone, the libstd of local builds isn't good enough for Miri any more.
> local rustc builds now also need a sysroot built

- README.md
- benches/helpers/miri_helper.rs
- src/bin/miri-rustc-tests.rs
- src/bin/miri.rs
- src/eval.rs
- src/lib.rs
- src/machine.rs
- src/shims/env.rs
- src/shims/foreign_items.rs
- src/shims/mod.rs
- tests/compiletest.rs
- tests/run-pass/communication.rs
- tests/run-pass/env.rs
related issue: https://github.com/rust-lang/miri/issues/800. r? @RalfJung
> Enable env communication

- Cargo.toml
- README.md
- src/helpers.rs
- src/machine.rs
This uses the host's randomness when the communication enabled flag is used. I am not sure about the error handling. I was thinking about fallbacking to `rand` if `getrandom` fails and also print something so the user knows miri is not using the host's rng because it failed. Let me know what you think. 
Related issue: https://github.com/rust-lang/miri/issues/800.
r? @RalfJung @oli-obk
> Use host's rng when communication is enabled

- Cargo.toml
so that we dont have to bump Cargo.toml in rustc
> decrease getrandom version

- Cargo.toml
This seems to be what rand_core does, and then we need to do it as well or else the rustc feature checker complains.
> explicitly enable getrandom/std feature

- src/shims/env.rs
In order to res0lve https://github.com/rust-lang/miri/issues/756 is necessary to have the whole `"NAME=VALUE"` sequence of bytes written into memory instead of just the value.
This change does not affect the interface of the `shim::envs::EnvVars` type in any way.
r? @RalfJung @oli-obk
> Write name and value for each env var

- Cargo.toml
- test-cargo-miri/Cargo.toml
- test-cargo-miri/build.rs
@elichai reported something that sounded a lot like build script running in Miri. But as this test shows, build scripts are not run by Miri, they are run normally.
@elichai are you sure the [env var usage you were referring to](https://github.com/rust-lang/miri/issues/641#issuecomment-524989482) was only in a build script? Those shouldn't be affected by Miri flags at all. Is your code available somewhere so that I can try to reproduce?
> test that build scripts do not run in Miri

- src/helpers.rs
Currently, retagging of a shared reference tries real hard to find the `UnsafeCell` and mark everything else as frozen. We even read enum discriminants to figure out the variant and determine if there is an `UnsafeCell` in there or not.
Unfortunately, that leads to some very hard to analyze behavior: during retagging, we do read accesses, which are subject to the rules of Stacked Borrows and the existing tags! My head hurts when I try to think about this. It's just too recursive.
This PR simplifies the semantics by treating enums like unions: if any variant has an `UnsafeCell`, the entire thing behaves like an `UnsafeCell`. This means retagging no longer has to read from memory, the way it affects the stack is entirely determined by the type.
> Stacked Borrows: don't read from memory during retagging

- README.md
- src/shims/env.rs
- test-cargo-miri/run-test.py
- test-cargo-miri/test.stdout.ref3
Related issue: https://github.com/rust-lang/miri/issues/933
I'm not sure if that's the better place to blacklist `TERM`, @RalfJung let me know if there is a less hacky place to put it.
> Fix cargo-miri with disabled isolation

- Cargo.toml
It's automatically detected: https://github.com/BurntSushi/byteorder/commit/5b3ffeeed2d04ec5051336ea2c6e6d36abc94581
With this PR `byteorder` can be from [rustc-workspace-hack](https://github.com/rust-lang/rust/blob/f71826e8f26fd4fa331574caa462960db8ed961a/src/tools/rustc-workspace-hack/Cargo.toml#L74).
> Bump byteorder and remove no-op feature

- src/shims/env.rs
- src/shims/foreign_items.rs
- tests/compile-fail/chdir_invalid_path.rs
- tests/run-pass/change_current_dir.rs
- tests/run-pass/get_current_dir.rs
> Add `chdir` shim

- src/shims/foreign_items.rs
- src/shims/io.rs
- tests/hello.txt
- tests/run-pass/file_read.rs
> Enable file writing

- src/shims/intrinsics.rs
- tests/run-pass/atomic.rs
> Add missing atomic_fence intrinsics as nops

- src/eval.rs
- src/machine.rs
- src/shims/env.rs
- src/shims/foreign_items.rs
- src/shims/io.rs
These changes move the `Evaluator::last_error` into miri's memory and implement the `__errno_location()` shim (which is used by the file handling functions when they fail).
> Move last error into memory

- src/shims/foreign_items.rs
- src/shims/io.rs
- tests/run-pass/file_manipulation.rs
r? @oli-obk 
This closes the whole create, write, read, delete circle for file handling.
> Add unlink shim to delete files

- tests/run-pass/fs.rs
> Check that fs errors have the proper kind

- src/helpers.rs
- src/lib.rs
- src/shims/foreign_items.rs
- src/shims/mod.rs
- src/shims/time.rs
- tests/run-pass/clock.rs
r? @oli-obk 
I think there is no way to do proper testing of this other than checking that miri does not crash when calling `clock_gettime`.
> Add clock_gettime shim

- src/bin/cargo-miri.rs
In Windows 10, there was an issue with building MIRI locally and getting it running,
due to unpredictable backslash escaping issues in paths.
I added a code snippet that would only be compiled in Windows OS, which replaces all backslashes in paths to slashes.
This fix should only affect Windows users. 
Building and testing MIRI locally now works fine after the fix. 
Fixes https://github.com/rust-lang/miri/issues/978
> change cargo-miri.rs to fix issue #978

- src/shims/fs.rs
@RalfJung this is my attempt to check for undesired flags. I also changed fcntl to error when doing any other action besides getting the flags for a fd
> Error when there is an unsupported flag for opening a file

- src/helpers.rs
- src/shims/env.rs
- src/shims/fs.rs
- src/shims/time.rs
Fixes https://github.com/rust-lang/miri/issues/986
r? @RalfJung
> Add function to error with enabled isolation

- src/eval.rs
- src/helpers.rs
- src/shims/env.rs
- src/shims/foreign_items.rs
- src/shims/fs.rs
- src/shims/intrinsics.rs
@christianpoveda you said, I think, that `fs.rs` could also be cleaned up to longer remove-and-then-add file descriptors from the table? Could you make a PR for that?
> cleanup now that borrow checker knows memory is a field

- src/eval.rs
- src/helpers.rs
- src/shims/foreign_items.rs
- src/shims/intrinsics.rs
This simplifies some bounds checks and adds comments.
> audit our bounds checks

- src/eval.rs
- src/helpers.rs
- src/machine.rs
- src/shims/env.rs
- src/shims/foreign_items.rs
- src/shims/fs.rs
> Change the last OS error location to a place

- tests/run-pass/align_offset.rs
Fixes https://github.com/rust-lang/miri/issues/873
> test align_to example

- src/eval.rs
Thanks to help from @bjorn3, @RalfJung, and @oli-obk on issue #1035 , I fixed the miri code so that error code **E0080** is no longer printed out for MIRI evaluation errors. I tested my code in my Linux machine as below.
Remaining concern is whether the variable name `new_tcx` which I used is misleading or not.
Fixes https://github.com/rust-lang/miri/issues/1035
> error code E0080 is no longer printed with MIRI error message

- src/shims/intrinsics.rs
- tests/run-pass/floats.rs
Tries to implment `intrinsics::copysignf32` and `intrinsics::copysignf64`. Fixes #1046.
> Implment intrinsics::copysignf32 and intrinsics::copysignf64

- README.md
We didn't mean any specific date, that was just an example.
> generalize readme

- src/bin/miri.rs
- src/eval.rs
Fixes #1064
This ensures that we set the error code properly when a panic unwinds
past `main`.
I'm not sure what the best way to write a test for this is
> Propagate the return code from the `start` lang item

- tests/run-pass/catch_panic.rs
- tests/run-pass/catch_panic.stderr
- tests/run-pass/panic1.rs
- tests/run-pass/panic1.stderr
- tests/run-pass/panic2.rs
- tests/run-pass/panic2.stderr
Do not silence panic msg printing (so we subsume the tests checking those), and check a few different ways of raising a panic.
> beef up catch_panic test

- miri
- src/bin/cargo-miri.rs
This also removes an odd hack from our `./miri` script.
> cargo-miri: support locally built rustc

- src/shims/foreign_items.rs
Thanks @petrochenkov for suggesting this!
> avoid injected_panic_runtime which is going away

- README.md
- test-cargo-miri/test.stdout.ref
- test-cargo-miri/test.stdout.ref2
- test-cargo-miri/test.stdout.ref3
- test-cargo-miri/tests/test.rs
This is better because it avoids warnings due to unused imports (the ignored tests still get compiled, just not executed).
> better way to ignore tests in Miri

- README.md
This PR from the rustup repository brought me here: https://github.com/rust-lang/rustup/issues/2148
TL;DR With rustup 1.21.0 `rustup install` and `rustup uninstall` are being deprecated in favor of `rustup toolchain install` and `rustup toolchain uninstall`. There's plenty of code/documentation out there that needs to be updated to reflect this.
Thought It would be cool to help, however small the change may be. :)
Keep up the great work!
> Updated README to reflect deprecation of rustup install

- .appveyor.yml
- .travis.yml
In the same spirit as #1110 😄 
This PR from the rustup repository brought me here: https://github.com/rust-lang/rustup/issues/2148
TL;DR With rustup 1.21.0 `rustup install` and `rustup uninstall` are being deprecated in favor of `rustup toolchain install` and `rustup toolchain uninstall`. There's plenty of code/documentation out there that needs to be updated to reflect this.
Thought It would be cool to help, however small the change may be. :)
Keep up the great work!
> Updated CI config to reflect deprecation of rustup uninstall

- src/helpers.rs
- src/shims/env.rs
- src/shims/foreign_items.rs
- src/shims/fs.rs
- src/shims/time.rs
- tests/run-pass/fs.rs
This is an attempt to fix: https://github.com/rust-lang/miri/issues/999 (for linux only)
Currently there is one problem that I haven't been able to solve. `std::fs::metadata` fails because the creation time is not available even though it is provided in the shim code.
In order to inform the caller that the field was provided, the `stx_flag` field must have the bits of `STATX_BTIME` set (which they are). The creation time is in the `stx_btime` field of the `statx` struct (see [1]). The relevant code in `libstd` is here (probably?): https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/fs.rs#L322
Another important point is that we are just providing the fields that are available in "all" platforms (this is, without using any platform specific traits or so). This can be improved …
> Add statx shim for linux target

- benches/fibonacci.rs
- benches/helpers/miri_helper.rs
- benches/smoke.rs
- rustfmt.toml
- src/bin/cargo-miri.rs
- src/bin/miri-rustc-tests.rs
- src/bin/miri.rs
- src/eval.rs
- src/helpers.rs
- src/intptrcast.rs
- src/lib.rs
- src/machine.rs
- src/mono_hash_map.rs
- src/operator.rs
- src/range_map.rs
- src/shims/dlsym.rs
- src/shims/foreign_items.rs
- src/shims/fs.rs
- src/shims/intrinsics.rs
- src/shims/mod.rs
- src/shims/panic.rs
- src/shims/time.rs
- src/shims/tls.rs
- src/stacked_borrows.rs
- tests/compiletest.rs
This is `cargo +nightly fmt --all` with `rustc 1.41.0-nightly (c8ea4ace9 2019-12-14)`
> Run rustfmt

- src/eval.rs
- tests/run-pass/main_result.rs
Turns out we already properly create the substitution to call the libstd start-fn with an appropriate `main`, we just had an overzealous check in the way.
Fixes https://github.com/rust-lang/miri/issues/1116.
> support main functions with Result return type

- src/shims/env.rs
- src/shims/foreign_items.rs
- src/shims/fs.rs
- tests/run-pass/fs.rs
Here we go. I'm apologizing in advice for the constant torture that Travis will suffer.
> add stat shim for macos

- src/helpers.rs
- src/shims/env.rs
- src/shims/foreign_items.rs
First part of the plan laid out in #707 (comment).
Re-submitting a pull-request for work from  #1098 (manual rebasing..)
r? @RalfJung
> Add helper 'alloc_os_str_as_c_str' and use it in env_var emulation

- src/shims/env.rs
- src/shims/fs.rs
this fixes https://github.com/rust-lang/miri/issues/999
r? @RalfJung
> Ignore close errors in read-only files.

- tests/run-pass/hashmap.rs
With https://github.com/rust-lang/miri/pull/1130 landed, this should work now. Thanks @christianpoveda!
Fixes https://github.com/rust-lang/miri/issues/686
> test macOS hashmap

- travis.sh
According to https://blog.rust-lang.org/2020/01/03/reducing-support-for-32-bit-apple-targets.html, these are tier 3 targets now, and might not be available on nightly much longer. So let's stop testing them.
> no longer test 32bit macOS

- src/diagnostics.rs
- src/eval.rs
- src/lib.rs
- src/stacked_borrows.rs
> Add a scheme for emitting errors without halting interpretation

- src/shims/intrinsics.rs
- tests/run-pass/atomic.rs
This applies the no-op shim for atomic fences to `atomic_singlethreadfence` and related intrinsics.
> Shim intrinsics::atomic_singlethreadfence, etc.

- README.md
This updates the installation instructions to point out that miri is only available on nightly, and encodes this assumption into the installation instructions.
It took me a bit of research to find out *why* miri wasn't installing on `windows-msvc`:
```txt
C:\Users\yoshu> rustup component add miri
error: component 'miri' for target 'x86_64-pc-windows-msvc' is unavailable for download for channel stable
```
I thought it must 've been something with the `msvc` target, but it turned out I was running on `stable`, and miri can only be installed on `nightly`. Having that be clearer in the installation instructions would've saved me some time debugging. Thanks!
> Document miri can only be installed on nightly

- src/shims/foreign_items.rs
- tests/run-pass/fs.rs
- tests/run-pass/libc.rs
This function is present in the libc crate, but not exposed through the standard library anywhere, so I haven't included a test for it.
> Add no-op shim for posix_fadvise

- src/helpers.rs
- src/shims/foreign_items.rs
- src/shims/fs.rs
- src/shims/time.rs
- tests/run-pass/fs.rs
This enables use of `File::metadata()`.
> Add support for AT_EMPTY_PATH to statx shim

- tests/compile-fail/stacked_borrows/illegal_read8.rs
- tests/run-pass/stacked-borrows/stacked-borrows.rs
- tests/run-pass/stacked-borrows/stacked-borrows.stderr
With https://github.com/rust-lang/rust/pull/64588 landed, we can finally test these things adequately. :)
> Test raw-ptr-cast without reborrow

- .appveyor.yml
- .travis.yml
`cargo install` will now update old versions, and not fail if things are up-to-date.
> rely on improved cargo install

- src/shims/foreign_items.rs
- src/shims/fs.rs
- tests/run-pass/fs.rs
This adds a shim for `lseek64` (`lseek` on macOS). This enables the use of `<File as Seek>::seek`. Testing is included.
> Add shim for seeking files

- src/shims/foreign_items.rs
- src/shims/fs.rs
- tests/run-pass/fs.rs
This adds a straightforward shim for rename, which is used by `std::fs::rename`. Testing is included.
As a heads up, I expect one or two merge conflicts between my PRs, since some of them touch the same `use` statements, or add items near the same places. I'll rebase and fix them as they come up.
> Add shim for rename

- src/lib.rs
- src/shims/fs.rs
- tests/run-pass/fs.rs
This adds support for `F_DUPFD` and `F_DUPFD_CLOEXEC` to the shim for `fcntl`. (The `FileHandler` does not track the `FD_CLOEXEC` flag for open files, so these commands are effectively the same.) These changes enable using `File::try_clone`.
I also changed the initial value of the `low` field in `FileHandler`, so that it matches the intent of the preceding comment. The `open` shim was pre-incrementing it when choosing new file descriptor numbers, so FD 3 was being skipped.
> Add F_DUPFD/F_DUPFD_CLOEXEC to fcntl shim

- tests/run-pass/fs.rs
As suggested [here](https://github.com/rust-lang/miri/pull/1158#issuecomment-586459463) this PR adds an additional test case for calling rename on a file path that doesn't exist.
> Test error case of std::fs::rename

- Cargo.lock
- Cargo.toml
- src/bin/cargo-miri.rs
Fixes #1057
I'm using my original approach from PR #1048. Ideally, we would
distinguish between build-deps/dependencies/'final crate' via a
different approach (e.g. the target directory). However, I
haven't been able to get that to work just yet.
However, everything should be working with the approach I'm using. At a
minimum, we can use this PR to verify that everything works as expected
when we don't actually produce native build outputs.
> Use 'cargo check' to build the sysroot and target crate

- src/helpers.rs
- src/lib.rs
- src/machine.rs
- src/shims/env.rs
- src/shims/foreign_items/posix.rs
- src/shims/foreign_items/posix/linux.rs
- src/shims/foreign_items/posix/macos.rs
- src/shims/fs.rs
- tests/run-pass/fs.rs
This PR adds support for `mkdir`, `rmdir`, `opendir`, `closedir`, and `readdir64_r`.
Open directory streams are tracked through a HashMap indexed by pointer locations, which holds directory iterators. Since `DIR` is an opaque type in glibc, I represent them with 1-byte allocations, and then just use their pointers in HashMap lookups.
Tests are included to exercise the new functionality.
> Add directory-related shims

- src/bin/cargo-miri.rs
This reflects the fact that we want bootstrap to override `xargo-check`,
not `xargo
> Rename XARGO env var to XARGO_CHECK

- README.md
- benches/helpers/miri_helper.rs
- src/bin/miri-rustc-tests.rs
- src/bin/miri.rs
- src/diagnostics.rs
- src/eval.rs
- src/machine.rs
> Add option to print when an AllocId gets created

- src/eval.rs
- src/machine.rs
- src/shims/env.rs
- src/shims/foreign_items/posix/macos.rs
- tests/compile-fail/environ-gets-deallocated.rs
- tests/run-pass/env.rs
- tests/run-pass/env.stdout
Remake of https://github.com/rust-lang/miri/pull/1147. There are three main problems with this:
1. For some reason `update_environ` is not updating `environ` when `setenv` or `unsetenv` are called. Even then it works during initialization.
2. I am not deallocating the old array with the variables in `update_environ`.
3. I had to store the `environ` place into `MemoryExtra` as a field to update it. I was thinking about changing `extern_statics` to store places instead of `AllocID`s to avoid this.
@RalfJung 
Fixes https://github.com/rust-lang/miri/issues/756
> Environ shim

- src/shims/intrinsics.rs
@RalfJung requires https://github.com/rust-lang/rust/pull/69825
> rm custom `intrinsics::discriminant_value`

- README.md
- tests/compiletest.rs
- travis.sh
Just like we already pass the target architecture to our compiletest wrapper via `MIRI_TEST_TARGET` (and then have CI run compiletest with different values for that env var), we now do the same for running the tests with and without MIR optimizations.
This has the advantage of speeding up local `./miri test`, where in the vast majority of cases running tests both with and without optimizations is just a waste of time.
> move repeated run of test suite (without and with MIR optimizations) out of compiletest

- src/diagnostics.rs
- src/eval.rs
- src/machine.rs
- src/shims/intrinsics.rs
- tests/compile-fail/invalid_zero_init.rs
- tests/compile-fail/uninit_uninhabited_type.rs
- tests/run-pass/panic/catch_panic.rs
- tests/run-pass/panic/catch_panic.stderr
This fixes #1222 
replacing the panic with an abort and a corresponding message.
the stack trace is already printed, this just adds an optional message the caller can pass, and I just pass the same message we passed to the panic but now to the abort instead.
r? @RalfJung
> Abort instead of panic on asserting intrinsics

- src/shims/foreign_items.rs
- src/shims/mod.rs
- src/shims/panic.rs
- tests/compile-fail/abort-terminator.rs
- tests/compile-fail/panic/double_panic.rs
- tests/compile-fail/panic/windows1.rs
- tests/compile-fail/panic/windows2.rs
- tests/compile-fail/panic/windows3.rs
@CAD97 [proposed](https://github.com/rust-lang/miri/issues/1059#issuecomment-601217992) trying to get a better error for failed panics on Windows.
Could you test if this works for you?
> whitelist platforms where panicking should work

- src/diagnostics.rs
- src/eval.rs
- src/helpers.rs
- src/lib.rs
- src/stacked_borrows.rs
Unsupported operation:
```
error: unsupported operation: Miri does not support threading
--> /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/sys/unix/thread.rs:68:19
|
68 |         let ret = libc::pthread_create(&mut native, &attr, thread_start, &*p as *const _ as *mut _);
|                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Miri does not support threading
|
= help: this is likely not a bug in the program; it indicates that the program performed an operation that the interpreter does not support
```
Unsupported operation that works without isolation:
```
error: unsupported operation: `clock_gettime` not available when isolation is enabled
--> /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/sys/unix/time.rs:349 …
```
> give some context in error messages

- src/helpers.rs
Turns out that condition was wrong and these functions never got compiled... Cc @christianpoveda 
I entirely overlooked this during review and just wondered why the heck this even compiles, when `into_bytes` just *doesn't exist*...^^
> fix conditional compilation condition for os_str <-> bytes conversion

- README.md
- src/shims/env.rs
- src/shims/foreign_items/windows.rs
- tests/compile-fail/environ-gets-deallocated.rs
- tests/run-pass/env-exclude.rs
- tests/run-pass/env-without-isolation.rs
- tests/run-pass/env.rs
This PR attempts to implement the final step of the instructions laid out in https://github.com/rust-lang/miri/issues/707#issuecomment-561564057 , and is yet a work in progress.
(**helpers.rs**)
(`std::env::var()`, `std::env::set_var()`)
- MIRI errors while running `std::env::remove_var()` in Windows.
MIRI complaining about raw pointer usage in 
Rust standard library [*src/libstd/sys/windows/os.rs*](https://github.com/rust-lang/miri/pull/1225#issuecomment-602100146).
- Move string helpers into a new file to avoid bloating **src/helpers.rs** too much. (**shims/os_str.rs**)
> Add shims for env var emulation in Windows

- src/eval.rs
- src/shims/foreign_items/posix/macos.rs
- src/shims/tls.rs
- tests/compile-fail/memleak.rs
- tests/compile-fail/memleak_rc.rs
Now that I can run macOS interpretation locally, this was not that hard to fix. ;)
Fixes https://github.com/rust-lang/miri/issues/443
> implement TLS cleanup for macOS

- src/eval.rs
- src/lib.rs
- src/machine.rs
- src/shims/env.rs
- src/stacked_borrows.rs
`Machine` memory is not leak-checked, so if we forgot to deallocate part of the env shim memory, we wouldn't even notice. Thus add a dedicated memory kind that is leak-checked.
> env shim: make sure we clean up all the memory we allocate

- src/helpers.rs
- src/shims/foreign_items.rs
- src/shims/foreign_items/posix.rs
- src/shims/foreign_items/posix/linux.rs
- src/shims/foreign_items/posix/macos.rs
- src/shims/foreign_items/windows.rs
Also organize them better by category.
Fixes https://github.com/rust-lang/miri/issues/1181 (by making mmap not callable from user code)
> Limit shims to libstd where possible

- src/shims/env.rs
Follow-up to https://github.com/rust-lang/miri/pull/1271. I forgot to adjust this when my plans changed a bit.
> we don't deallocate the environ global, so leave it in the machine

- src/helpers.rs
- src/shims/env.rs
- src/shims/foreign_items/windows.rs
- src/shims/os_str.rs
- tests/run-pass/current_dir.rs
Implemented shims for Windows
* [GetCurrentDirectoryW](https://github.com/rust-lang/rust/blob/75208942f6144daac669e8e382029fc33bdce841/src/libstd/sys/windows/os.rs#L242) (`getcwd` for Windows)
* [SetCurrentDirectoryW](https://github.com/rust-lang/rust/blob/75208942f6144daac669e8e382029fc33bdce841/src/libstd/sys/windows/os.rs#L250) (`chdir` for Windows)
Currently passes test :
`./miri run tests/run-pass/current_dir.rs -Zmiri-disable-isolation`
> Windows shims for GetCurrentDirectoryW/SetCurrentDirectoryW

- src/shims/os_str.rs
Fixed `fn convert_path_separator()` to take `Cow<>` as argument,
in order to prevent unnecessary allocation when target & host path separators are equal.
> make 'fn convert_path_separator' to take 'Cow<>' as argument

- src/shims/fs.rs
- tests/run-pass/fs.rs
This PR extends the POSIX shim for `open` to support the `O_EXCL` flag, when it is used alongside `O_CREAT`, and exercises it by testing `OpenOptions::create_new`.
> Add support for OpenOptions::create_new()/O_EXCL

- miri
I somehow thought that was already the default, but seems like it is not?
> miri build script: use incremental builds

- src/shims/time.rs
Also use `+` instead of `checked_add().unwrap()` (which is equivalent).
Cc @JOE1994
> correct factual mistake in Windows message

- src/shims/foreign_items/windows.rs
- src/shims/time.rs
- tests/run-pass/time.rs
Add support for creating `std::time::Instant` in Windows
Includes shims for `QueryPerformanceCounter` & `QueryPerformanceFrequency` in Windows, which are both called in Windows when `std::time::Instant` is created.
Windows docs page ["Acquiring high-resolution time stamps"](https://docs.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps) was helpful in learning how `QueryPerformanceCounter` & `QueryPerformanceFrequency` work.
closes #1291
> Add support for 'std::time::Instant' in Windows

- rust-version
- src/bin/cargo-miri.rs
So we can remove a special hack. I checked this locally to confirm it works.
Cc https://github.com/rust-lang/rust/pull/70642 @eddyb
> Rust bootstrap sysroot now has src in the same place as rust-src

- README.md
Fixes https://github.com/rust-lang/miri/issues/1289
This makes it clearer in the readme how miri will warn of supported or unsupported code in a program under test/run. 
Thanks!
> Update readme to make supported code clearer

- src/shims/fs.rs
Wondering why `last_entry` was introduced (in #1156) while the alternative is shorter and seems clearer to me. 
Also, as the perpetrator of map_first_last, I now think that `first_entry`/`last_entry` are silly methods because they're supposed to be constant time (as opposed to `entry`), so there's no money to be made by doing multiple things with the entry.
> Replace last_entry with last_key_value

- src/diagnostics.rs
- src/eval.rs
I think this improves how things look, and makes it easier to see the help text (it currently kind of drowns next to the backtrace).
Before:
```
error: unsupported operation: Miri does not support threading
--> /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/sys/unix/thread.rs:68:19
|
68 |         let ret = libc::pthread_create(&mut native, &attr, thread_start, &*p as *const _ as *mut _);
|                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Miri does not support threading
|
= help: this is likely not a bug in the program; it indicates that the program performed an operation that the interpreter does not support
= note: inside `std::sys::unix::thread::Thread::new` at …
```
> add empty line before backtrace, to separate it from help text

- tests/run-pass/float.rs
- tests/run-pass/float_fast_math.rs
Copy a bunch of float cast tests from https://github.com/WebAssembly/testsuite/blob/master/conversions.wast. I didn't do all of them though, too lazy... maybe we should have a wasm interpreter written in Rust and run that in Miri and use the wasm test suite directly that way? :P
> Even more float cast tests

- src/shims/intrinsics.rs
Also remove `pref_align_of` as it was moved into rustc long ago, and `align_of_val` as it doesn't exist (the name is `min_align_of_val`, which we also already handle).
> organize intrinsics in groups

- src/diagnostics.rs
Cc @shepmaster
```
error: Undefined Behavior: accessing memory with alignment 1, but alignment 8 is required
--> tests/compile-fail/unaligned_pointers/alignment.rs:8:9
|
8 |         *y_ptr = 42;
|         ^^^^^^^^^^^ accessing memory with alignment 1, but alignment 8 is required
|
= help: this usually indicates that your program performed an invalid operation and caused Undefined Behavior
= help: but alignment errors can also be false positives, see https://github.com/rust-lang/miri/issues/1074
```
> for alignment errors, note that there might be false positives

- src/shims/foreign_items/posix/macos.rs
- src/shims/time.rs
- tests/run-pass/time.rs
Since we return nanoseceonds instead of ticks from `mach_absolute_time`, we don't need to scale the absolute time
Fixes #1288
> Implement `mach_timebase_info` for macOS

- README.md
- src/diagnostics.rs
- src/machine.rs
> add deallocation tracking

- src/shims/intrinsics.rs
- tests/compile-fail/intrinsics/copy_overlapping.rs
- tests/compile-fail/intrinsics/copy_unaligned.rs
- tests/compile-fail/intrinsics/float_to_int_32_inf1.rs
- tests/compile-fail/intrinsics/float_to_int_32_infneg1.rs
- tests/compile-fail/intrinsics/float_to_int_32_nan.rs
- tests/compile-fail/intrinsics/float_to_int_32_nanneg.rs
- tests/compile-fail/intrinsics/float_to_int_32_neg.rs
- tests/compile-fail/intrinsics/float_to_int_32_too_big1.rs
- tests/compile-fail/intrinsics/float_to_int_32_too_big2.rs
- tests/compile-fail/intrinsics/float_to_int_32_too_small1.rs
- tests/compile-fail/intrinsics/float_to_int_64_inf1.rs
- tests/compile-fail/intrinsics/float_to_int_64_infneg1.rs
- tests/compile-fail/intrinsics/float_to_int_64_infneg2.rs
- tests/compile-fail/intrinsics/float_to_int_64_nan.rs
- tests/compile-fail/intrinsics/float_to_int_64_neg.rs
- tests/compile-fail/intrinsics/float_to_int_64_too_big1.rs
- tests/compile-fail/intrinsics/float_to_int_64_too_big2.rs
- tests/compile-fail/intrinsics/float_to_int_64_too_big3.rs
- tests/compile-fail/intrinsics/float_to_int_64_too_big4.rs
- tests/compile-fail/intrinsics/float_to_int_64_too_big5.rs
- tests/compile-fail/intrinsics/float_to_int_64_too_small1.rs
- tests/compile-fail/intrinsics/float_to_int_64_too_small2.rs
- tests/compile-fail/intrinsics/float_to_int_64_too_small3.rs
- tests/run-pass/float.rs
@hanna-kruppe would be great if you could have a look at this.
`float.rs` tests legal casts. `test_cast` checks that both `as` casts and unchecked casts work (i.e., these are not saturating). The `compile-fail` tests should ensure that illegal casts via the intrinsic are detected as such.
Fixes https://github.com/rust-lang/miri/issues/1264
> implement float_to_int_unchecked

- src/shims/foreign_items.rs
- src/shims/foreign_items/posix.rs
- src/shims/foreign_items/windows.rs
- tests/run-pass/sync.rs
This PR adds support for `std::sync::atomic::spin_loop_hint()` by implementing the `llvm.x86.sse2.pause` intrinsic when the target is x86-based. It appears this is the first LLVM intrinsic in foreign_items, so I added a couple match blocks to handle it or fall through to the different OS-specific methods. I added a basic smoke test to `tests/run-pass/sync.rs`. I came across this by way of `crossbeam::utils::Backoff::spin()`, FWIW.
> Handle std::sync::atomic::spin_loop_hint()

- src/shims/foreign_items/posix/linux.rs
- src/shims/foreign_items/posix/macos.rs
- src/shims/fs.rs
- tests/run-pass/fs.rs
This adds a shim for `ftruncate64` (on Linux) or `ftruncate` (on macOS) to enable support for `File::set_len`, and includes a test.
> Implement ftruncate64/ftruncate for File::set_len

- build.rs
- tests/compiletest.rs
Just read about this in the 1.43 release notes. :)
> test suite: rely on CARGO_BIN_EXE_ env vars

- README.md
Details to the found in https://github.com/rust-lang/miri/issues/1364.
Note that this was not a found in a `master` or production release of ink!, however without analysing the code via `miri` this could have potentially happened.
> Add miri trophy for LazyArray::swap (ink! PR)

- src/diagnostics.rs
- tests/compile-fail/undefined_buffer.rs
Here's a small addition I made locally to the UB diagnostics, in case you're interested in it. This PR calls `dump_alloc()` on the relevant allocation if Miri fails on UB due to reading undefined bytes. This came in handy when diagnosing such an issue in a large program using unsafe Rust, in part because it wasn't deterministic enough to use `-Zmiri-track-alloc-id=`. If you'd like to put this behind another -Z flag, let me know.
> Print hex dump of alloc on reading undef bytes

- src/shims/foreign_items.rs
- src/shims/foreign_items/posix/macos.rs
- src/shims/thread.rs
- src/thread.rs
- tests/run-pass/concurrency/simple.rs
- tests/run-pass/concurrency/simple.stderr
- tests/run-pass/sync.rs
- tests/run-pass/transmute_fat2.rs
- tests/run-pass/transmute_fat2.stderr
@vakaras agreed it would make sense to make `spin_loop` yield, so this implements that.
Also add a test for a panic being raised in one thread, caught by the panic machinery, and then expose through the join handle. Miraculously, that just works. :)
> Make spin_loop yield, and a panicking thread test

- src/helpers.rs
- src/lib.rs
- src/shims/dlsym.rs
- src/shims/foreign_items.rs
- src/shims/foreign_items/posix.rs
- src/shims/foreign_items/posix/linux.rs
- src/shims/foreign_items/posix/macos.rs
- src/shims/foreign_items/windows.rs
- src/shims/fs.rs
- src/shims/intrinsics.rs
- src/shims/mod.rs
- src/shims/panic.rs
- src/shims/thread.rs
- tests/compile-fail/check_arg_count.rs
- tests/compile-fail/check_arg_count_too_few_args.rs
- tests/compile-fail/check_arg_count_too_many_args.rs
Fixes #1272
Some shims don't use all their arguments, I've assumed they are being called in tests with the correct number of arguments here.
> Check that shims are called with the correct number of arguments

- src/bin/cargo-miri.rs
- src/bin/miri.rs
@oli-obk I think that's better than looking at `--emit` like we did before... what do you think?
> re-do cargo-miri host/target detection logic to match rustbuild

- README.md
- src/bin/cargo-miri.rs
- src/bin/miri.rs
Fixes https://github.com/rust-lang/rust/issues/52856
> make Miri work in rustc bootstrap stage 0

- README.md
- src/bin/cargo-miri.rs
- src/bin/miri.rs
Always go through 'MIRI_BE_RUSTC=1 miri' instead. This is based on @oli-obk's great idea to add a way to make Miri behave like rustc, which already helped us in https://github.com/rust-lang/miri/pull/1405. Now it means in `cargo-miri` we run *all* crates through the same binary, and use the env var to determine if we compile or interpret them. This makes sure the compiler is consistent.
The `rustc` binary of the current toolchain is now not used at all, only the `miri` binary is. In particular this means we can kill the sysroot consistency check. :)
> cargo-miri: never invoke rustc

- tests/compiletest.rs
This also means we do not need the `RUSTC_TEST_SUITE` env var any more.
> compiletest: no need to call rustc here

- README.md
- src/bin/cargo-miri.rs
Fixes https://github.com/rust-lang/miri/issues/1414
> add test suite filter example to README and 'cargo miri --help'

- src/bin/cargo-miri.rs
Until recently we were always overwriting `RUSTFLAGS`, but we stopped doing that when moving to `MIRI_BE_RUSTC`. That introduced the regression in https://github.com/rust-lang/miri/issues/1410. This fixes it.
Fixes https://github.com/rust-lang/miri/issues/1410
> fix libstd rebuilds due to RUSTFLAGS changes

- src/shims/dlsym.rs
- src/shims/foreign_items/posix.rs
- src/shims/foreign_items/windows.rs
This makes progress towards https://github.com/rust-lang/miri/issues/1059.
> prepare Dlsym system for dynamic symbols on Windows

- tests/run-pass/intrinsics.rs
Make sure this works for all types, not just enums/generators.
> test discriminant_value intrinsic

- tests/run-pass/dyn-lcsit.rs
> add interesting unsizing test

- src/bin/cargo-miri.rs
Fixes https://github.com/rust-lang/miri/issues/1421
@bjorn3 @oli-obk do you think that is a reasonable way to solve this issue?
> unset RUSTC_WRAPPER for xargo invocation

- README.md
- src/shims/foreign_items/posix.rs
- src/shims/foreign_items/posix/macos.rs
- src/shims/foreign_items/windows.rs
- src/shims/sync.rs
- src/shims/thread.rs
- src/shims/tls.rs
- src/sync.rs
- src/thread.rs
- tests/run-pass/concurrency/sync.rs
Make some methods infallible, move a bit more work into the platform-independent `sync.rs`, and fix a bug in rwlock unlocking.
> Synchronization primitive cleanup

- README.md
A small fix was made to libstd in rust-lang/rust#70479 (back in March).
(Miri reported UB due to Stacked Borrows violation - [link to Miri error log](https://github.com/rust-lang/miri/pull/1225#discussion_r397830221))
Thank you for reviewing :+1:
> Add a case to list of 'StackedBorrows violations'

- src/shims/foreign_items/posix.rs
- src/shims/foreign_items/posix/linux.rs
- src/shims/fs.rs
- tests/run-pass/fs.rs
- tests/run-pass/libc.rs
This PR adds shim implementations for these related file syncing functions.
* `fsync`, for POSIX targets, backed by `File::sync_all()`
* `fdatasync`, for POSIX targets, backed by `File::sync_data()`
* `fcntl` with command `F_FULLFSYNC`, for macOS targets, backed by `File::sync_all()`
* `sync_file_range`, for Linux targets, backed by `File::sync_data()`
> Add file sync shims

- tests/compile-fail/dangling_pointers/dangling_pointer_addr_of.rs
- tests/compile-fail/unaligned_pointers/unaligned_ptr_addr_of.rs
- tests/run-pass/packed_struct.rs
Make sure it can create pointers to packed fields, but *cannot* deref dangling or unaligned (raw) pointers.
> Test raw_ptr macro

- src/shims/intrinsics.rs
They are now implemented in MIR interpreter by rust-lang/rust#73778
> Remove likely and unlikely from intrinsics shim

- miri
This helps cargo tell apart `./miri` builds and `cargo check` (e.g. through rust-analyzer).
See https://github.com/rust-lang/cargo/issues/8440.
> set --target when building miri

- rust-version
- src/machine.rs
- src/shims/env.rs
- src/stacked_borrows.rs
Fixes a regression introduced by https://github.com/rust-lang/rust/pull/74006
> we cannot track all machine memory any more due to int-ptr-casts

- cargo-miri/bin.rs
This should help with https://github.com/rust-lang/rust/pull/74146#issuecomment-655723028
> on Windows, strip the '\\?\' prefix from the canonical path

- cargo-miri/bin.rs
Newer xargo should hopefully work with the paths this produces on Windows.
> go back to using canonicalize()

- src/diagnostics.rs
- src/eval.rs
- src/thread.rs
Our non-fatal diagnostics are printed *after* completing the step that triggered them, which means the span and stacktrace used for them is that of the *next* MIR statement being executed. That's quite bad, obviously, as pointing to where in the source something happens is their entire point.
Here's an example:
```rust
use std::ptr;
static mut PTR: *mut u8 = ptr::null_mut();
fn get_ptr() -> *const u8 { unsafe { PTR }}
fn cause_ub() { unsafe {
let _x = &*get_ptr();
} }
fn main() { unsafe {
let mut l = 0;
PTR = &mut l;
let r = &mut *PTR;
cause_ub();
let _x = *r;
} }
```
This example is UB; if you track the pointer tag that is given in the final error, it points to the entire body of `cause_ub` as a span, instead of the `&*get_ptr();`.
I am not sure what the best way is to fix this. The …
> fix non-fatal diagnostics stacktraces

- src/shims/intrinsics.rs
This is now supported by the interpreter with https://github.com/rust-lang/rust/pull/74459. We can remove this intrinsic implementation here.
This is covered by this test: https://github.com/rust-lang/miri/blob/master/tests/compile-fail/unreachable.rs
I guess we need to wait until the rust-lang/rust PR merges into nightly, and then we can update `rust-version` hash in the PR, right?
r? @oli-obk
> Remove unreachable intrinsic

- cargo-miri/bin.rs
No reason to actually emit any object code.
This helps with some strange ICEs when testing Miri in the rustc workspace.
> only check-build the dummy xargo project

- src/machine.rs
- src/shims/posix/fs.rs
Related issue: #1486 
Instead of mapping FDs to `FileHandle`, map them to a `FileDescriptor` trait object. The goal is to eventually have both `FileHandle` as well as `Stdin`, `Stdout` and `Stderr` implement this trait so that syscalls involving FDs can handle both `File`s as well as the standard IO streams.
This PR adds the `FileDescriptor` trait and an `impl` for `FileHandle`. I'll open a separate PR for implementing the trait for the standard IO streams.
> Add FileDescriptor trait to abstract fn's on File's and Stdin,Stdout,Stderr

- src/shims/posix/foreign_items.rs
- src/shims/posix/fs.rs
- tests/compile-fail/fs/read_from_stdout.rs
- tests/compile-fail/fs/write_to_stdin.rs
- Use `FileDescriptor::read` for stdin reads
- Use `FileDescriptor::write` for stdout/err writes
- Handle stdout/err reads in `FileDescriptor::read`
The `FileDescriptor` trait was added in PR #1495 
Closes #1486
> Add `impl FileDescriptor` for stdin, stdout, stderr

- src/shims/posix/fs.rs
Instead of indicating incorrectly that a handle was not found, return the error from `as_file_handle` indicating the operation is not supported on the FD.
Addresses some comments in #1495
> Bubble up errors from FileDescriptor::as_file_handle

- src/diagnostics.rs
For https://github.com/rust-lang/miri/issues/1382, we also need to allow `ReferencedConstant` post-monomorphization errors. The other post-monomorphization errors should still be impossible to trigger in Miri. The fix is not complete though without https://github.com/rust-lang/rust/pull/75339.
> accept some post-monomorphization errors

- src/machine.rs
- src/shims/posix/fs.rs
Also:
- Type annotate `handles` declaration, instead of annotating every insert.
- Add note about flush being unnecessary when writing to stderr
Addresses comments in #1495 and #1497
> Remove lifetime from FileDescriptor trait

- Cargo.lock
- Cargo.toml
miri hasn't actually depended on byteorder directly for a while.
Let's remove this dependency so Rust also depends less on it.
> Remove byteorder dependency

- cargo-miri/bin.rs
This PR addresses a FIXME in cargo-miri, and filters the targets to be checked when any of the `--bin`, '--test`, or `--lib` flags are passed.
> Support --test/--bin/--lib in cargo-miri

- test-cargo-miri/run-test.py
- test-cargo-miri/test.stdout.ref4
- test-cargo-miri/test.stdout.ref5
This is a followup to #1525, adding a few test invocations with targets specified in the cargo arguments.
> Test cargo miri target selection

- src/eval.rs
- src/helpers.rs
- src/machine.rs
- src/shims/panic.rs
- src/shims/posix/linux/foreign_items.rs
- src/shims/posix/macos/foreign_items.rs
- src/thread.rs
- tests/run-pass/libc.rs
- tests/run-pass/libc.stderr
- tests/run-pass/panic/concurrent-panic.rs
- tests/run-pass/panic/concurrent-panic.stderr
This PR moves the panic payload storage from the `Machine` state to per-thread state. Prior to this change, if one thread panicked while another was still unwinding, Miri would fail with `thread 'rustc' panicked at 'the panic runtime should avoid double-panics', src/shims/panic.rs:51:9`. I ran into this issue while prototyping a round-robin scheduler, but it's also reachable with the current scheduler and contrived programs that use blocking API calls to cause thread switching during unwinding. I wrote a test case along those lines for this change.
> Move panic payload state from Machine to Thread

- src/shims/posix/fs.rs
- tests/compile-fail/fs/close_stdout.rs
- tests/run-pass/fs_libc.rs
- tests/run-pass/fs_libc.stderr
- tests/run-pass/fs_libc.stdout
Implements some of the operations for stdin/out/err, towards #1499
> Implement dup and close for stdin/stdout/stderr

- README.md
- cargo-miri/bin.rs
- src/shims/foreign_items.rs
- src/shims/panic.rs
- tests/compile-fail/panic/panic_abort1.rs
- tests/compile-fail/panic/panic_abort2.rs
- tests/compile-fail/panic/panic_abort3.rs
- tests/compile-fail/panic/panic_abort4.rs
This adds support for abort-on-panic (https://github.com/rust-lang/miri/issues/1058). To achieve this, we insert `cargo-miri` as `RUSTC` when building the standard library, and patch the rustc flags in a way similar to what bootstrap does.
However, this is currently not supported on Windows as the Windows code uses inline assembly to cause an abort (?!?). I'll submit a rustc PR with some `cffg(miri)` to make that work. (EDIT: that would be https://github.com/rust-lang/rust/pull/76871)
Cc @Aaron1011 r? @oli-obk
> support panic=abort

- cargo-miri/bin.rs
I forgot this in https://github.com/rust-lang/miri/pull/1540. Again this is just temporary, for backwards compatibility.
> also support old 'cargo miri run -- -- args' style

- test-cargo-miri/Cargo.lock
- test-cargo-miri/Cargo.toml
Adds a test for the issue fixed in https://github.com/rust-lang/miri/pull/1557
> test formerly broken serde_derive dependency

- src/helpers.rs
- src/shims/posix/linux/foreign_items.rs
- src/shims/posix/linux/mod.rs
- src/shims/posix/linux/sync.rs
- src/sync.rs
- tests/compile-fail/fs/isolated_file.rs
- tests/compile-fail/fs/isolated_stdin.rs
- tests/run-pass/concurrency/linux-futex.rs
- tests/run-pass/concurrency/linux-futex.stderr
- tests/run-pass/concurrency/parking.rs
- tests/run-pass/concurrency/parking.stderr
Fixes https://github.com/rust-lang/rust/issues/77406 and fixes #1562.
This makes std's park(), park_timeout(), and unpark() work. That means std::sync::Once is usable again and the test pass again with the latest rustc.
This also makes parking_lot work.
> Implement futex_wait and futex_wake.

- src/bin/miri.rs
- src/shims/posix/linux/foreign_items.rs
- src/shims/posix/linux/sync.rs
@m-ou-se do you think this check makes sense?
The `abi` of a layout contains everything needed for the calling convention (as far as I know), so this should ensure that all the ignored arguments are passed like integers and do not otherwise mess up argument passing.
The one thing I am not sure about is what happens when more arguments are passed than fit in registers. The `syscall` man page says that all calling conventions support at least 6 arguments, except for "mips/o32" where it says that
```
[1] The mips/o32 system call convention passes arguments 5 through 8 on the user stack.
```
If we assume that passing these extra arguments to futex is legal even with that calling convention, that would mean that those user stack arguments are just silently ignored as well, which seems …
> check that all syscall arguments are scalars

- .github/workflows/ci.yml
I already had a complete template to transition from Travis and Appveyor.
Since actions will not run on repo haven't enabled it before.
I have this dummy template first to enable it on default branch.
We should address a few todo here, merge it and I will send another patch
to complete the migration.
> Add a dummy actions template to enable it on CI

- .github/workflows/ci.yml
There are probably ways to simplify this... I just copied this from the Rust repo and expanded the anchors and adjusted the `needs` thing. Hopefully this unblocks Miri PR landing.
> add bors notification jobs

- cargo-miri/bin.rs
Fixes https://github.com/rust-lang/miri/issues/1567
Unfortunately, I found no nice way to test for this.
> fix for rlib/cdylib crates in dependency tree

- .appveyor.yml
- .github/workflows/ci.yml
- .travis.yml
- README.md
- ci.sh
Complete adding github actions whose dummy template added in #1563 .
But it will need https://github.com/rust-lang/rust-central-station/pull/939 merged first
to be able to gate bors on Actions CI checks.
> Adding a working github actions template

- README.md
This is a great feature, let's hope more people notice it :)
> README: make our cross-interpretation feature stand out more

- tests/run-pass/backtrace-std.rs
- tests/run-pass/backtrace-std.stderr
Closes https://github.com/rust-lang/miri/issues/1578
> Test std backtrace type

- README.md
- cargo-miri/bin.rs
- tests/run-pass/concurrency/simple.stderr
- tests/run-pass/panic/catch_panic.stderr
- tests/run-pass/panic/concurrent-panic.stderr
- tests/run-pass/panic/div-by-zero-2.stderr
- tests/run-pass/panic/overflowing-lsh-neg.stderr
- tests/run-pass/panic/overflowing-rsh-1.stderr
- tests/run-pass/panic/overflowing-rsh-2.stderr
- tests/run-pass/panic/panic1.rs
- tests/run-pass/panic/panic1.stderr
- tests/run-pass/panic/panic2.stderr
- tests/run-pass/panic/panic3.stderr
- tests/run-pass/panic/panic4.stderr
- tests/run-pass/transmute_fat2.stderr
This allows the normal std panic hook to print a backtrace if
`RUST_BACKTRACE=1` and `-Z miri-disable-isolation` are set
> Enable `backtrace` feature in the generated `Xargo.toml`

- cargo-miri/bin.rs
Previously miri used `cargo install xargo -f` which shouldn't be
necessary anymore since `cargo install` will now upgrade without `-f`.
The only reason I can see to use `-f` is from the cargo docs:
> This is also useful if something has changed on the system that you
> want to rebuild with, such as a newer version of `rustc`.
See the [discussion on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/why.20does.20miri.20require.20xargo/near/214351239).
> Don't force-install xargo

- miri
Fixes #1597.
`./miri` is just testing whether the platform supports `readlink -e`,
but it didn't hide properly hide the stderr output. This fixes that.
> Hide readlink error in `./miri`

- src/bin/miri-rustc-tests.rs
- src/bin/miri.rs
- src/lib.rs
Feel free to close this if this is intentionally not a constant.
> Make `miri_default_args()` a constant

- miri
- src/diagnostics.rs
- src/stacked_borrows.rs
Also use bash to make sure `&>` works.
> pointer tag tracking: also show when tag is being created

- cargo-miri/bin.rs
- tests/run-pass/panic/catch_panic.rs
- tests/run-pass/panic/catch_panic.stderr
Debug assertions in the standard library can be somewhat expensive to check, in particular the ones covering each and every `ptr::write/copy/copy_nonoverlapping`. Miri will find most of those problems anyway since they cause UB. There are other debug assertions, such as ensuring internal invariants are maintained, but given how slow Miri already is, I think it is better to skip those checks in Miri and instead figure out a better way for people to use a standard library with debug assertions enabled.
> disable debug assertions in the standard library

- CONTRIBUTING.md
> Update locally-built rustc instructions

- tests/run-pass/concurrency/sync.rs
just saw this fail on macOS in PR CI, so add some extra safety margin
> increase timeout to avoid spurious test failures

- tests/run-pass/backtrace-api.rs
- tests/run-pass/backtrace-std.rs
- tests/run-pass/panic/panic1.rs
Tests failed when using a local build as my folders are called `rustc`, `rustc.2`, ...
Expand the regex to also support that naming scheme.
> backtrace tests: support more ways of checking out Rust locally

- CONTRIBUTING.md
It seems to work fine with `--stage 1` and it should be faster.
Cc #1610
Cc @jyn514
> CONTRIBUTING.md: Use `build --stage 1` instead of `build --stage 2`

- CONTRIBUTING.md
This builds on the changes from https://github.com/rust-lang/miri/pull/1612 and should not be merged before.
- Fix incorrect comment
- Recommend `x.py setup` over manually editing config.toml
- Link to rustc-dev-guide
> Improve contributing instructions

- src/data_race.rs
- src/lib.rs
- src/vector_clock.rs
- tests/compile-fail/data_race/release_seq_race_same_thread.rs
- tests/run-pass/concurrency/data_race.rs
See [Weaken Release Sequences](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0982r1.html), since the exception for relaxed writes on the same thread as a release write not blocking release sequences was removed in the C++20 memory model compared to the C11 memory model the paper was based on. The implementation can be updated and simplified to match this.  [Rust is currently specified to use the C++20 memory model](https://doc.rust-lang.org/std/sync/atomic/index.html).
> Weaken release sequences to match the C++20 memory model

- README.md
Just something I noticed while reading.
> Fix README.md typo "extend" -> "extent"

- src/shims/intrinsics.rs
Since https://github.com/rust-lang/rust/pull/80040, we can rely on the pass introduced in https://github.com/rust-lang/rust/pull/79049 to lower away `forget`.
> remove intrinsic that is now implemented in the rustc side

- .github/workflows/ci.yml
> send Zulip notification when cron job fails

- src/lib.rs
`#![feature(min_const_generics)]` has been [stabilized](https://github.com/rust-lang/rust/pull/79135), so I removed `#![feature(const_generics)]` and `#![allow(incomplete_features)]` (I assume Miri is not built by the beta bootstrap compiler so it's fine to just remove them).
The test [`tests/run-pass/specialization.rs` also has a `#![allow(incomplete_features)]` for `#![feature(specialization)]`](https://github.com/rust-lang/miri/blob/9949d9e4/tests/run-pass/specialization.rs#L1-L2). I think that can be removed and `#![feature(specialization)]` can be replaced with `#![feature(min_specialization)]`, but I'm not sure whether I should do that because it's a test. Feel free to ask me to remove it if it's fine to do so.
> Remove `#![feature(const_generics)]` and `#![allow(incomplete_features)]`

- ci.sh
- src/shims/foreign_items.rs
- src/shims/posix/foreign_items.rs
- src/shims/posix/macos/foreign_items.rs
`libc::sysconf(libc::_SC_NPROCESSORS_CONF)` is used by AArch64 devices to get the number of CPUs in the `num_cpus` crate:
https://github.com/seanmonstar/num_cpus/blob/b423db0a698b035914ae1fd6b7ce5d2a4e727b46/src/lib.rs#L337-L342
> Add shim for libc::sysconf(libc::_SC_NPROCESSORS_CONF)

- cargo-miri/bin.rs
- test-cargo-miri/run-test.py
- test-cargo-miri/subcrate/Cargo.toml
- test-cargo-miri/subcrate/src/lib.rs
- test-cargo-miri/test.stderr-proc-macro.ref
>  [cargo-miri] Skip unit tests of `proc-macro` crates

- .github/workflows/ci.yml
https://rust-lang.zulipchat.com/#narrow/stream/269128-miri/topic/Cron.20Job.20Failure/near/223865005:
> Dear @**RalfJ** and @**oli**\n\nIt would appear that the Miri cron job build failed. Would you mind investigating this issue?\n\nThanks in advance!\nSincerely,\nThe Miri Cronjobs Bot
This PR changes that to:
> Dear @**RalfJ** and @**oli**
>
> It would appear that the Miri cron job build failed. Would you mind investigating this issue?
>
> Thanks in advance!
> Sincerely,
> The Miri Cronjobs Bot
> Fix `\n` in Zulip message

- src/bin/miri.rs
- src/data_race.rs
- src/eval.rs
- src/machine.rs
- src/shims/intrinsics.rs
- tests/run-pass/atomic.rs
In practice this is pretty useful for detecting bugs.
This fails more frequently than realistic (~~50%~~ (now 80%, controlled by a flag) of the time). I couldn't find any existing code that tries to model this (tsan, cdschecker, etc all seem to have TODOs there). Relacy models it with a 25% or 50% failure chance depending on some settings.
CC @JCTyblaidd who wrote the code this modifies initially, and seems interested in this subject.
> Add random failures to compare_exchange_weak

- src/helpers.rs
- src/machine.rs
- src/shims/dlsym.rs
- src/shims/foreign_items.rs
- src/shims/mod.rs
- src/shims/posix/dlsym.rs
- src/shims/posix/foreign_items.rs
- src/shims/windows/dlsym.rs
- src/shims/windows/foreign_items.rs
> Add ABI check for shims

- src/bin/miri.rs
`panic!(format!(..))` will start giving a warning [soon](https://github.com/rust-lang/rust/pull/81645).
> Remove unnecessary `format!()` in `panic!()`.

- cargo-miri/bin.rs
- test-cargo-miri/Cargo.lock
- test-cargo-miri/Cargo.toml
- test-cargo-miri/cdylib/Cargo.toml
- test-cargo-miri/cdylib/src/lib.rs
- test-cargo-miri/issue-1705/Cargo.toml
- test-cargo-miri/issue-1705/src/lib.rs
- test-cargo-miri/src/lib.rs
>  Patch `--extern` arguments in `phase_cargo_rustc` as well

- src/stacked_borrows.rs
- tests/compile-fail/stacked_borrows/zst_slice.rs
@SkiFire13 [pointed out](https://github.com/rust-lang/rust/pull/82554#issuecomment-787088712) that Miri fails to detect illegal use of empty slices. This PR fixes that. In so doing, it uncovers a flaw of Stacked Borrows: it is incompatible with how the formatting machinery uses `extern type`, so for now we skip reborrowing when we cannot determine the exact size of the pointee.
> fix reborrowing of tagged ZST references

- ci.sh
`RUST_TEST_NOCAPTURE` seems to make no difference except for making compiletest output not use colors any more; `RUST_BACKTRACE` is already set by `compiletest.rs`.
> adjust CI test flags

- src/data_race.rs
- src/shims/intrinsics.rs
- tests/run-pass/atomic.rs
Closes #1718
Previous attempt: #1653
TODO:
**Note:** this PR also removes arbitrary trailing whitespace and generally formats the affected files
> Add atomic min and max

- src/shims/intrinsics.rs
The corresponding enum is called `AtomicOp` so IMO this also makes more sense as the name for the function.
> rename atomic_op_min_max -> atomic_op

- src/shims/intrinsics.rs
- tests/compile-fail/breakpoint.rs
The `breakpoint` intrinsic raises a `SIGTRAP` signal. If a debugger is attached to a normal program, then `SIGTRAP` can be used to trigger breakpoints in debuggers like `gdb`. If there is no debugger, then the program exits with a message like `Trace/breakpoint trap (core dumped)`. This adds support for the intrinsic in Miri. While actually passing through the `SIGTRAP` doesn't make sense in a Miri context (if it just raised the signal normally then it would allow for debugging Miri itself, not the program being evaluated). As such, it just raises an error.
> Support breakpoint intrinsic

- Cargo.toml
rust-analyzer/rust-analyzer#7891
> Opt-in to rustc_private for `rust-analyzer`

- src/shims/panic.rs
- tests/compile-fail/panic/bad_unwind.rs
- tests/compile-fail/panic/unwind_panic_abort.rs
Fixes https://github.com/rust-lang/miri/issues/1740
> ensure we catch incorrectly unwinding calls

- README.md
[Rendered](https://github.com/jrvanwhy/miri/tree/track-raw-pointers-doc)
Minor change: I changed the quotes around `<untagged>` into backticks, so they render correctly in markdown.
~~Significant change: I documented that `-Zmiri-track-raw-pointers` is a strictly more restrictive model that "normal" Stacked Borrows. **I am not confident this change is correct, please verify it.** If this change is not correct, let me know, and I'll update this PR to document that :-)~~
EDIT: I was wrong, `-Zmiri-track-raw-pointers` may not be strictly more restrictive. I added the following sentence to prevent others from making the same assumption that I did:
> Note that it is not currently guaranteed that code that works with `-Zmiri-track-raw-pointers` also works without `-Zmiri-track-raw-pointers`.
> Improvements to the README item on `-Zmiri-track-raw-pointers`.

- test-cargo-miri/Cargo.lock
- test-cargo-miri/Cargo.toml
- test-cargo-miri/tests/test.rs
getrandom 0.1 is still in use, so let's make sure it also still works with Miri.
> also test old getrandom

- README.md
- cargo-miri/bin.rs
- test-cargo-miri/run-test.py
- test-cargo-miri/src/lib.rs
- test-cargo-miri/test.cross-target.stdout.ref
- test-cargo-miri/test.default.stdout.ref
- test-cargo-miri/test.filter.cross-target.stdout.ref
- test-cargo-miri/test.filter.stdout.ref
- test-cargo-miri/test.stderr-rustdoc.ref
@teryror did all the work in https://github.com/rust-lang/miri/pull/1671; I just finished things up and fixed conflicts. Also thanks to @hyd-dev for preemptively fixing a sysroot issue that would have taken me some time to diagnose.
Fixes https://github.com/rust-lang/miri/issues/584
> add rustdoc support

- README.md
- cargo-miri/bin.rs
- src/bin/miri.rs
- test-cargo-miri/Cargo.lock
- test-cargo-miri/Cargo.toml
- test-cargo-miri/build.rs
- test-cargo-miri/issue-1760/Cargo.toml
- test-cargo-miri/issue-1760/build.rs
- test-cargo-miri/issue-1760/src/lib.rs
- test-cargo-miri/src/lib.rs
- tests/run-pass/cfg_miri.rs
They (specifically, `--cfg=miri`) may cause procedural macros (and probably build scripts) to depend on Miri-only symbols, such as `miri_resolve_frame`.
This PR makes `miri` detect host crates inspecting the value of the `MIRI_BE_RUSTC` environment variable (`target` -> target crate, `host` -> host crate, other -> panic) and skip the insertion of `MIRI_DEFAULT_ARGS` if it's a host crate.
Fixes #1760
> Don't use `MIRI_DEFAULT_ARGS` to compile host crates

- src/thread.rs
- tests/run-pass/concurrency/libc_pthread_cond.rs
Currently, we check for expired timeouts after each step of execution. That seems excessive. This changes the scheduler to only check for timeouts when the active thread cannot continue running any more.
@vakaras does this sound right? `pthread_cond_timedwait` anyway already yields, of course, since it blocks on getting the signal (or the timeout).
> only check timeouts when a thread yields

- README.md
- cargo-miri/bin.rs
@hyd-dev pointed out that `MIRI_BE_RUSTC` is set to an incorrect value during the xargo sysroot build. This fixes that.
> fix MIRI_BE_RUSTC value during sysroot build

- cargo-miri/bin.rs
With https://github.com/rust-lang/miri/pull/1540, we deprecated `cargo miri test -- -Zmiri-disable-stacked-borrows` as a style of passing flags to Miri, introducing `MIRIFLAGS="-Zmiri-disable-stacked-borrows" cargo miri test` instead. This made `cargo miri` more compatible with `cargo`; both now behave the same in terms of argument parsing.
However, to avoid breaking things, I introduced some backwards compatibility hack such that the old way would still work. Six months later, I think it is time to remove that hack.
> remove compatibility code for passing miri flags via cargo arguments

- Cargo.toml
- tests/compiletest.rs
Quoting from the comment in `tests/compiletest.rs`:
> Custom test runner, to avoid libtest being wrapped around compiletest which wraps libtest.
I believe `harness = false` is more suitable for that purpose.
I have verified that both `./miri test` and `LD_LIBRARY_PATH=$PWD/build/x86_64-unknown-linux-gnu/stage2/lib PATH=$PWD/build/bin:$PATH ./x.py test src/tools/miri` work well.
> Use `harness = false` instead of `#![feature(custom_test_frameworks)]`

- src/shims/intrinsics.rs
- tests/compile-fail/fast_math_both.rs
- tests/compile-fail/fast_math_first.rs
- tests/compile-fail/fast_math_second.rs
Calling these intrinsics with non-finite values is undefined behaviour, since they result in `f*` intrinsics in LLVM with the `fast` flag, and `fast` math on non-finite values results in `poison` values. (technically LLVM only considers it UB upon _using_ the value, but that shouldn't make much of a difference)
> Throw UB if f*_fast intrinsic called with non-finite value

- cargo-miri/bin.rs
- cargo-miri/build.rs
Fixes https://github.com/rust-lang/rust/issues/84182
@semarie this should fix your problem... but I think any version of Miri actually shipped to users should have the proper git version information embedded, so I am not sure if this is the right fix. How do you do this for rustc proper? Even stable builds usually have a git version:
```
$ rustc +stable --version
rustc 1.51.0 (2fd73fabe 2021-03-23)
```
> support building Miri outside a git repo

- src/helpers.rs
- src/shims/foreign_items.rs
- src/shims/os_str.rs
- src/shims/posix/foreign_items.rs
- src/shims/posix/thread.rs
- src/shims/windows/foreign_items.rs
This is a part of https://github.com/rust-lang/miri/pull/1804 that we can already do.
> stop relying on c_str/wide_str helpers in rustc

- src/data_race.rs
- src/machine.rs
- src/stacked_borrows.rs
- src/thread.rs
Now that the memory access hooks get references to `MemoryExtra`, we can avoid refcounting for the global state of Stacked Borrows and the data race detector.
> get rid of some `Rc`

- cargo-miri/bin.rs
- test-cargo-miri/run-test.py
- test-cargo-miri/subcrate/src/lib.rs
- test-cargo-miri/test.stderr-proc-macro-doctest.ref
Fixes #1813.
Verified that the newly added tests failed without the `cargo-miri` change and pass with normal `cargo test`.
> Skip doctests of `proc-macro` crates

- Cargo.lock
- Cargo.toml
- README.md
- src/bin/miri.rs
- src/eval.rs
- src/machine.rs
- src/shims/panic.rs
This PR uses the `measureme` crate to profile the call stack of the
program being interpreted by Miri. This is accomplished by starting a
measureme 'event' when we enter a function call, and ending the event
when we exit the call. The `measureme` tooling can be used to produce a
call stack from the generated profile data.
Limitations:
* We currently record every single entry/exit. This might generate very
large profile outputs for programs with a large number of function
calls. In follow-up work, we might want to explore sampling (e.g. only
recording every N function calls).
* This does not integrate very well with Miri's concurrency support.
Each event we record starts when we push a frame, and ends when we pop
a frame. As a result, the timing recorded for a particular frame will include …
> Add `measureme` integration for profiling the interpreted program

- tests/run-pass/strings.rs
This PR adds a regression test for the aliasing rules of a `Unique<T>` pointer.
At the time of writing this test case, Miri does not treat `Unique<T>`
pointers as a special case, these are treated like any other raw pointer.
However, there are existing Github issues which may lead to `Unique<T>`
becoming a special case through asserting unique ownership over the pointee:
- https://github.com/rust-lang/unsafe-code-guidelines/issues/258
- https://github.com/rust-lang/unsafe-code-guidelines/issues/262
In the new test case, the calls to `String::remove` and `String::insert[_str]` follow
code paths that would trigger undefined behavior in case `Unique<T>`
would ever assert semantic ownership over the pointee. Internally,
these methods call `self.vec.as_ptr()` and `self.vec.as_mut_ptr()` on
the …
> added a strings.rs regression test case for potential future UB

- README.md
In particular current example doesn't work if you have a rust-toolchain file in the project.
> Specify miri toolchain for CI example

- README.md
- src/bin/miri.rs
- src/diagnostics.rs
- src/eval.rs
- src/helpers.rs
- src/lib.rs
- src/machine.rs
- src/shims/env.rs
- src/shims/posix/fs.rs
- tests/run-pass/current_dir_with_isolation.rs
- tests/run-pass/current_dir_with_isolation.stderr
get and set current dir operations used to halt the machine by
throwing an exception in isolation mode. This change updates them to
return a dummy `NotFound` error instead, and keep the machine running.
I started with a custom error using `ErrorKind::Other`, but since it
can't be mapped to a raw OS error, I dropped it. `NotFound` kind of make
sense for get operations, but not much for set operations. But that's
the only error supported for windows currently.
> fix: avoid stopping machine upon running env operations in isolation

- src/diagnostics.rs
- src/helpers.rs
- src/shims/env.rs
- tests/run-pass/current_dir_with_isolation.rs
- tests/run-pass/current_dir_with_isolation.stderr
Follow-up to https://github.com/rust-lang/miri/pull/1797
> isolated operations return EPERM; tweak isolation hint

- README.md
- src/bin/miri.rs
- src/eval.rs
- src/helpers.rs
- src/machine.rs
- src/shims/foreign_items.rs
- src/shims/panic.rs
- src/shims/posix/linux/foreign_items.rs
- src/shims/windows/foreign_items.rs
- tests/compile-fail/concurrency/thread-spawn.rs
- tests/run-pass/panic/unsupported_foreign_function.rs
- tests/run-pass/panic/unsupported_foreign_function.stderr
This PR fixes #1807 and allows an optional flag to be specified to panic when an unsupported syscall is encountered. In essence, instead of bubbling up an error in the context of the Miri application Miri will panic within the context of the *emulated* application. This feature is desired to allow CI pipelines to determine if a Miri failure is unsupported functionality or actual UB. Please read [this comment](https://github.com/rust-lang/miri/issues/1807#issuecomment-845425076) for the rationale behind this change.
Note: this change does not cover all cases where unsupported functionality errors may be raised. If you search the repo for `throw_unsup_format!` there are many cases that I think are less likely to occur and may still be problematic for some folks.
TODO:
> Add support for panicking in the emulated application when unsupported functionality is encountered

- src/diagnostics.rs
- src/helpers.rs
- src/machine.rs
- src/shims/backtrace.rs
- src/shims/foreign_items.rs
- src/shims/panic.rs
- src/shims/posix/foreign_items.rs
- src/shims/posix/linux/foreign_items.rs
- src/shims/posix/macos/foreign_items.rs
- src/shims/windows/foreign_items.rs
- tests/compile-fail/function_calls/check_arg_count_abort.rs
- tests/compile-fail/function_calls/exported_symbol_shim_clashing.rs
- tests/run-pass/function_calls/exported_symbol.rs
Implements https://github.com/rust-lang/miri/pull/1776#issuecomment-821322605.
The error looks like this:
```
error: found `malloc` symbol definition that clashes with a built-in shim
--> tests/compile-fail/function_calls/exported_symbol_shim_clashing.rs:12:9
|
12 |         malloc(0);
|         ^^^^^^^^^ found `malloc` symbol definition that clashes with a built-in shim
|
help: the `malloc` symbol is defined here
--> tests/compile-fail/function_calls/exported_symbol_shim_clashing.rs:2:1
|
2  | / extern "C" fn malloc(_: usize) -> *mut std::ffi::c_void {
3  | |     //~^ HELP the `malloc` symbol is defined here
4  | |     unreachable!()
5  | | }
| |_^
= note: inside `main` at tests/compile-fail/function_calls/exported_symbol_shim_clashing.rs:12:9
```
This does not implement "better error …
> Report an error if a `#[no_mangle]`/`#[export_name = ...]` function has the same symbol name as a built-in shim

- src/bin/miri.rs
- src/shims/foreign_items.rs
- test-cargo-miri/Cargo.lock
- test-cargo-miri/Cargo.toml
- test-cargo-miri/exported-symbol-dep/src/lib.rs
- test-cargo-miri/issue-rust-86261/Cargo.toml
- test-cargo-miri/issue-rust-86261/src/lib.rs
- test-cargo-miri/src/main.rs
[`#[no_mangle]` on a `use` item](https://docs.rs/brotli-decompressor/2.3.1/src/brotli_decompressor/ffi/mod.rs.html#3-5) can make Miri ICE when compiling a dependency (rust-lang/rust#86261):
```rs
#[no_mangle]
use std::{thread,panic, io, boxed, any, string};
```
<details>
```
error: internal compiler error: compiler/rustc_middle/src/ty/mod.rs:1650:13: item_name: no name for DefPath { data: [DisambiguatedDefPathData { data: Misc, disambiguator: 14 }], krate: crate0 }
thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1007:9
stack backtrace:
0: std::panicking::begin_panic
1: std::panic::panic_any
2: rustc_errors::HandlerInner::bug
3: rustc_errors::Handler::bug
4: rustc_middle::ty::context::tls::with_opt
5: rustc_middle::util::bug::opt_span_bug_fmt
6: …
```
> Filter out items other than non-generic functions and statics in our version of `exported_symbols`

- .github/workflows/ci.yml
- cargo-miri/bin.rs
- rustup-toolchain
- test-cargo-miri/.gitignore
- test-cargo-miri/run-test.py
- test-cargo-miri/run.custom-target-dir.stderr.ref
Resolves #1311.
This PR makes Miri use `miri` inside the rustc target directory as its target directory, by letting `cargo-miri` get the rustc target directory by calling `cargo metadata`, append `miri` to it, and pass it with `--target-dir` to Cargo.
Getting the rustc target directory accurately requires calling `cargo metadata` as far as I know, because the `target-dir` can be set in config files in various places that are hard for `cargo-miri` to find.
I also considered https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#custom-named-profiles, but it looks like that requires adding `cargo-features = ["named-profiles"]` to **`Cargo.toml`**, which would be tricky for `cargo-miri`:
```
$ cargo +nightly-2021-06-23 test --config 'profile.miri.inherits="release"' --profile=miri …
```
> Use `miri` inside the target directory used by rustc as Miri's target directory

- src/shims/foreign_items.rs
- src/stacked_borrows.rs
Only heap allocations need an exception.
> also treat CallerLocation and Machine memory as properly tagged

- LICENSE-APACHE
- LICENSE-MIT
@Mark-Simulacrum pointed out that our license files are slightly different from those in rustc. This syncs them.
The question is... is this a thing we can just do?^^
> sync license files with rustc repo

- benches/helpers/miri_helper.rs
- cargo-miri/bin.rs
- rustfmt.toml
- src/bin/miri.rs
- src/diagnostics.rs
- src/helpers.rs
- src/shims/env.rs
- src/shims/foreign_items.rs
- src/shims/intrinsics.rs
- src/shims/posix/fs.rs
- src/stacked_borrows.rs
- src/vector_clock.rs
This is an experiment, I am not yet sure if I like it... but it does prevent rustfmt from putting stuff after the `=>` in a `match` (unless the entire arm fits there), which IMO is a big plus. What do others think?
(I also tried setting `match_arm_blocks` back to its default of `true`, but that adds too many braces for my taste.)
Btw, @calebcartwright is the interaction of `match_arm_blocks = false` and `force_multiline_blocks = true` as can be seen here expected? I think I like it, but it it is not at all what I expected from the docs which describe `force_multiline_blocks = true` as "Force multiline closure and match arm bodies to be wrapped in a block" -- but here that is not the effect it has, there are no new blocks being added.
> fmt: set force_multiline_blocks=true

- src/diagnostics.rs
- src/helpers.rs
- src/shims/env.rs
- src/shims/posix/fs.rs
- tests/run-pass/fs_with_isolation.rs
- tests/run-pass/fs_with_isolation.stderr
Update posix fs shims to use new API `reject_in_isolation`, which
allows rejection with error code instead of always forcing abort.
Error code chosen for each op is the most appropriate one from the
list in corresponding syscall's manual.
Updated helper APIs to not use quotes (\`) around input name while
preparing the message. This allows callers to pass multi-word string
like -- "\`read\` from stdin".
Cc https://github.com/rust-lang/miri/issues/1034
> Fix use of deprecated `check_no_isolation` in posix fs shims

- src/diagnostics.rs
- src/eval.rs
Fixes https://github.com/rust-lang/miri/issues/1834
> show proper error when using a sysroot without MIR

- README.md
- src/eval.rs
- src/thread.rs
- tests/compile-fail/concurrency/libc_pthread_create_main_terminate.rs
- tests/run-pass/threadleak_ignored.rs
- tests/run-pass/threadleak_ignored.stderr
This is a step towards https://github.com/rust-lang/miri/issues/1371. The remaining hard part would be supporting checking for memory leaks when there are threads still running. For now we elegantly avoid this problem by using the same flag to control both of these checks. :)
> also ignore 'thread leaks' with -Zmiri-ignore-leaks

- src/bin/miri.rs
The `used_crate_source` query defines its return type as [`Lrc<CrateSource>`](https://github.com/rust-lang/rust/blob/1195bea5a7b73e079fa14b37ac7e375fc77d368a/compiler/rustc_middle/src/query/mod.rs#L1418), which would be `Arc` when `parallel-compiler = true`.
I assume this fixes rust-lang/rust#87623. I didn't test that locally -- I'm not interested in `parallel-compiler = true` enough to be willing to recompile rustc with that configuration to test it, but I'm submitting this in case it might be useful for `parallel-compiler = true` users.
> Use `Lrc` instead of `Rc` in `MiriCompilerCalls::config()`

- test-cargo-miri/exported-symbol-dep/src/lib.rs
- tests/run-pass/function_calls/exported_symbol.rs
https://github.com/rust-lang/rust/pull/86492 has landed:
- The code in https://github.com/rust-lang/miri/issues/1837 starts to work (even without `AssocFn::foo();` at line 12) in Miri.
- `pub` is not necessary for `#[no_mangle]` associated functions in `test-cargo-miri/exported-symbol-dep/src/lib.rs` anymore.
Closes https://github.com/rust-lang/miri/issues/1837.
> Update tests for `#[no_mangle]` on associated functions

- src/data_race.rs
- src/helpers.rs
> Fix typos “a”→“an”

- src/shims/intrinsics.rs
- tests/run-pass/write-bytes.rs
Add support for the unstable `volatile_set_memory` intrinsic
(Runtime behaviour and soundness requirements for `volatile_set_memory` are identical to those of `write_bytes`, so supporting this intrinsic is trivial.)
> Add support for the `volatile_set_memory` intrinsic

- .gitpod.yml
At https://gitpod.io/#https://github.com/rust-lang/miri one can edit miri in the browser and run it and everything.
I'm experimenting with this here as a low-impact version of trying it out on the whole rustc repo. This .gitpod file should cause the user to land in a shell that can run ./miri test immediately without any additional prep
> Try out gitpod

- CONTRIBUTING.md
Reverts most of bb59980b2da10437ce1ee4d53bdb3feb1f4a9c5f.
See the discussion starting at https://github.com/rust-lang/miri/issues/1340#issuecomment-913043714 for more.
> Stage 2 seems to be required after all

- benches/helpers/miri_helper.rs
- src/bin/miri.rs
- src/eval.rs
- src/lib.rs
- tests/run-pass/start.rs
- tests/run-pass/start.stdout
This PR adds support for the `#[start]` attribute and fixes #1825.
It also renames `eval_main` to `eval_entry` to reflect that it can evaluate any entry function.
> add support for `#[start]`

- cargo-miri/bin.rs
- test-cargo-miri/run-test.py
The main `cargo` command supports `cargo r` as an alias for `cargo run`, and `cargo t` as an alias for `cargo test`. This adds support to them in `cargo-miri` for consistency.
> One character aliases for cargo-miri run/test

- src/eval.rs
Previously the command line string would have been incorrectly constructed if argv[0] contained a doublequote (`"`) or ended in a trailing backslash (`\`). This is a very rare edge case because, by convention, argv[0] is the path to the application and Windows file names cannot contain doublequotes.
Fixes #1881
> Correct Windows argument handling

- src/shims/foreign_items.rs
- src/shims/posix/foreign_items.rs
- src/shims/posix/linux/foreign_items.rs
- src/shims/posix/macos/foreign_items.rs
- src/shims/windows/foreign_items.rs
- tests/compile-fail/alloc/no_global_allocator.rs
- tests/run-pass/global_allocator.rs
- tests/run-pass/global_allocator.stdout
This PR adds support for custom global allocators. Unfortunately, the code given in #1207 still causes errors when used with box. I believe this is because Box is special-cased in miri and stacked borrows.
> add support for `#[global_allocator]`

- cargo-miri/bin.rs
- test-cargo-miri/src/lib.rs
- test-cargo-miri/test.default.stdout.ref
- test-cargo-miri/test.filter.stdout.ref
This is important to be able to control which doctests run with `cargo miri test`. In particular, this is required for https://github.com/rust-lang/rust/pull/90909 to work as intended.
> run rustdoc with the miri cfg flag

- .github/workflows/ci.yml
15:00 UTC is 16:00 in Europe and 10:00 on the US East Coast (during winter time, and 1h later during summer time), so a good time in both places to see the email and react quickly. No need to run this in the middle of the night if nobody will fix the problem anyway.
Move it 5min past the full hour to avoid what is probably a rush of cronjobs on the full hour.
> tweak cron job time

- README.md
- src/bin/miri.rs
- src/eval.rs
- src/machine.rs
- src/stacked_borrows.rs
- test-cargo-miri/run-test.py
- tests/compile-fail/box-cell-alias.rs
- tests/compile-fail/stacked_borrows/raw_tracking.rs
- tests/compile-fail/stacked_borrows/zst_slice.rs
- tests/run-pass/btreemap.rs
- tests/run-pass/concurrency/tls_lib_drop_single_thread.rs
- tests/run-pass/rc.rs
- tests/run-pass/slices.rs
- tests/run-pass/stacked-borrows/stacked-borrows.rs
- tests/run-pass/strings.rs
- tests/run-pass/vec.rs
- tests/run-pass/vecdeque.rs
The old flag name sounds too similar to `-Zmiri-track-pointer-tag`, which is a totally different kind of 'tracking'. This has lead to confusion in https://github.com/rust-lang/miri/issues/1907.
> rename track-raw-pointers flag to tag-raw-pointers

- tests/run-pass/overflow_checks_off.rs
Strangely, if we call the functions in `std::ops`, we still get the panics. I assume that is because we build the stdlib with `-Cdebug-assertions=on`; probably the magic attribute that makes stdlib functions inherit overflow checks from the calling crate only works one way (namely to enable them when the calling crate asks for them, but not to disable them when the calling crate does not want them).
> test for overflow-checks=off

- cargo-miri/miri
- miri
This is a gross hack to work around https://github.com/rust-analyzer/rust-analyzer/issues/10793: calling `cargo-miri/miri` does the same thing as calling `./miri`.
@oli-obk this is the best I could come up with... not sure if we want to have this in the repo. I am also okay with carrying `cargo-miri/miri` locally.
> hack to work around RA quirk

- src/intptrcast.rs
- tests/run-pass/adjacent-allocs.rs
When two objects directly follow each other in memory, what is the
provenance of an integer cast to a pointer that points directly between
them?  For a zero-size region, it could point into the end of the first
object, or the start of the second.
We can avoid answering this difficult question by simply never
allocating two objects directly beside each other.  This fixes some of
the false positives from #1866.
> intptrcast: Never allocate two objects directly adjecent

- miri
Make behavior consistent between Linux and macOS even though macOS lacks some basic shell tools
> macOS-compatible realpath

- src/diagnostics.rs
- src/stacked_borrows.rs
I slapped this in as a sort of advanced println-based debugging when trying to figure out a track-raw-pointers finding in `smallvec`. Perhaps this looks like a good idea to you all?
EDIT: User scenario
Run `MIRIFLAGS=-Ztag-raw-pointers cargo miri test`, get a diagnostic that looks like
```
error: Undefined Behavior: trying to reborrow for SharedReadOnly at alloc99465+0x9, but parent tag <265507> does not have an appropriate item in the borrow stack
```
So now run `MIRIFLAGS=-Ztag-raw-pointers -Zmiri-track-pointer-tag=265507 cargo miri test`
Old:
```
note: tracking was triggered
--> src/lib.rs:822:36
|
822 |                 vec: NonNull::from(self),
|                                    ^^^^ popped tracked tag for item [SharedReadOnly for <265507>]
```
New:
```
note: tracking was triggered …
```
> Provide slightly better notes when tracking a pointer tag

- CONTRIBUTING.md
- README.md
- cargo-miri/bin.rs
This is just an alias of `XARGO_RUST_SRC`, but avoids exposing how exactly we use xargo.
> add and document MIRI_LIB_SRC env var to set the source from which Miri builds the standard library

- cargo-miri/Cargo.lock
- cargo-miri/Cargo.toml
This removes some deps and pulls only one version of `rustc_version` crate.
> update crate rustc_version 0.3 -> 0.4 to remove some deps

- src/stacked_borrows.rs
- tests/run-pass/stacked-borrows/generators-self-referential.rs
This basically works around https://github.com/rust-lang/unsafe-code-guidelines/issues/148 by not requiring uniqueness any more for mutable references to self-referential generators. That corresponds to [the same work-around that was applied in rustc itself](https://github.com/rust-lang/rust/blob/b81553267437627af63c79c1a20c73af865a842a/compiler/rustc_middle/src/ty/layout.rs#L2482).
I am not entirely sure if this is a good idea since it might hide too many errors in case types are "accidentally" `!Unpin`. OTOH, our test suite still passes, and to my knowledge the vast majority of types is `Unpin`. (`place.layout.ty` is monomorphic, we should always exactly know which type this is.)
> exclude mutable references to !Unpin types from uniqueness guarantees

- src/bin/miri.rs
- src/diagnostics.rs
- src/eval.rs
- src/lib.rs
- src/machine.rs
This removes the majority of output from `cargo miri run` and `cargo miri test` in common usage.
~~I've copied the logic almost directly from `std`:
https://github.com/rust-lang/rust/blob/3b186511f62b0ce20e72ede0e8e13f8787155f02/library/std/src/sys_common/backtrace.rs#L76-L77~~
~~It might be nice to have the "some details were omitted" note and a fallback to a setting where we print everything just in case this logic goes sideways, but~~
~~1. I'm not sure where to put the note~~
~~2. `MIRI_BACKTRACE`, `RUST_BACKTRACE`, and `RUSTC_CTFE_BACKTRACE` already do something else. Should we repurpose or add on to the semantics of `MIRI_BACKTRACE`?~~
---
Based on this tiny silly crate:
```rust
fn main() {
some_function();
}
fn some_function() {
unsafe {
let _x: &u8 = core::mem::transmute(1usize);
} …
```
> Prune backtraces similar to RUST_BACKTRACE=1 logic

- README.md
What are the critera for adding SB entries to the trophy case?
> Add crossbeam-epoch and integer-encoding to the trophy case

- src/diagnostics.rs
In https://github.com/rust-lang/miri/pull/1977 we forgot to use the pruning logic when printing tag-tracking messages. I just saw this output before this PR which is very silly:
```
test sanity ... note: tracking was triggered
--> src/lib.rs:110:21
|
110 |         unsafe { &*(&self.value[range] as *const [T] as *const Aligned<A, [T]>) }
|                     ^^^^^^^^^^^^^^^^^^ created tag 160954
|
= note: inside `<Aligned<A4, [u8]> as std::ops::Index<std::ops::RangeTo<usize>>>::index` at src/lib.rs:110:21
note: inside `sanity` at src/lib.rs:261:30
--> src/lib.rs:261:30
|
261 |     let y: &Aligned<_, _> = &y[..2];
|                              ^^^^^^
note: inside closure at src/lib.rs:229:1
--> src/lib.rs:229:1
|
228 |   #[test]
|   ------- in this procedural macro expansion
229 | / fn …
```
> Prune stacktraces for tag-tracking diagnostics too

- src/diagnostics.rs
Per https://github.com/rust-lang/miri/pull/1987#discussion_r815337994
The only problem with this is that it looks like we can't emit the note about `-Zmiri-backtrace=full` if we also emit a tag-tracking diagnostic. The final note about the setting simply doesn't appear on the final error if it is printed before. I feel like we're running up against some diagnostic deduplication logic?
> Only print the pruning note if the trace was definitely pruned

- README.md
- src/bin/miri.rs
- src/eval.rs
- src/shims/env.rs
- tests/run-pass/env-forward.rs
The flag is called `-Zmiri-env-forward=<var>`, but I am open to bikeshedding. ;)
> add flag to forward specific env vars (while isolation remains enabled)

- src/shims/posix/foreign_items.rs
- src/shims/posix/fs.rs
- tests/compile-fail/fs/unix_open_missing_required_mode.rs
- tests/compile-fail/fs/unix_open_too_many_args.rs
- tests/run-pass/fs.rs
This PR allows `libc::open` to be called using two or three arguments as defined in https://man7.org/linux/man-pages/man2/open.2.html
The presence of the third argument depends on the value of the second argument.  If the second argument dictates that the third argument is *required* miri will emit an error if the argument is missing.  If the second argument does *not* require a third argument, then the argument is ignored and passed as 0 internally (it would be ignored by libc anyway)
> Allow varargs for libc::open when it is allowed by the second argument

- tests/run-pass/integer-ops.rs
Cc https://github.com/rust-lang/rust/pull/94659
> add extra tests for shifts with negative offsets

- src/data_race.rs
- src/machine.rs
- src/shims/env.rs
- src/shims/posix/fs.rs
- src/shims/posix/linux/foreign_items.rs
- src/stacked_borrows.rs
- tests/run-pass/fs.rs
> Implement a readdir64() shim for Linux

- README.md
If this snippet works as expected in https://github.com/rust-lang/portable-simd/pull/255 (which we can test tomorrow), then this adjusts our README to that nicer script.
> update recommended CI snippet, add GHA example

- src/shims/intrinsics.rs
- tests/compile-fail/intrinsics/simd-gather.rs
- tests/compile-fail/intrinsics/simd-scatter.rs
- tests/run-pass/portable-simd.rs
This makes portable-simd doctests pass. :)
Cc https://github.com/rust-lang/miri/issues/1912
> implement simd_{shuffle,gather,scatter}

- src/helpers.rs
- src/shims/posix/fs.rs
- src/shims/time.rs
This avoids having to explicitly list the types of all fields -- we derive them from the type of the struct instead.
Also add write_int_fields_named, to give the fields by name instead of ordered by index.
> add write_int_fields to replace write_packed_immediates

- README.md
- src/shims/env.rs
Fixes https://github.com/rust-lang/miri/issues/1702
r? @oli-obk
> exclude TERM env var by default

- tests/run-pass/portable-simd.rs
Blocked on portable-simd getting updated in rustc.
> test integer SIMD min/max

- src/diagnostics.rs
Just ran into this and figured I could fix it real quick 🙂
> missing backtick on miri-isolation warning help

- src/shims/intrinsics.rs
- tests/run-pass/portable-simd.rs
Cc https://github.com/rust-lang/miri/issues/1912
> implement SIMD sqrt and fma

- src/diagnostics.rs
- src/stacked_borrows.rs
- tests/compile-fail/box-cell-alias.rs
- tests/compile-fail/stacked_borrows/illegal_write3.rs
- tests/compile-fail/stacked_borrows/raw_tracking.rs
- tests/compile-fail/stacked_borrows/shr_frozen_violation1.rs
- tests/compile-fail/stacked_borrows/zst_slice.rs
In fatal errors, this clarifies the difference between a tag not being present in the borrow stack at all, and the tag being present but granting SRO. It also introduces a little notation for memory ranges so we can mention to the user that the span may point to code that operates on multiple memory locations, but we are reporting an error at a particular offset.
This also gets rid of the unqualified phrase "the borrow stack" in errors, and clarifies that it is the borrow stack _for some location_.
The crate `pdqselect` v0.1.1:
Before:
```
2103 |     unsafe { copy_nonoverlapping(src, dst, count) }
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no item granting read access to tag <2357> at alloc1029 found in borrow stack.
```
After:
```
2103 |     unsafe { copy_nonoverlapping(src, …
```
> Add a lot more information to SB fatal errors

- src/helpers.rs
- src/shims/intrinsics.rs
- tests/compile-fail/intrinsics/simd-select-bitmask-invalid.rs
- tests/compile-fail/intrinsics/simd-select-invalid-bool.rs
- tests/run-pass/portable-simd.rs
Cc https://github.com/rust-lang/miri/issues/1912
> implement simd bitmask intrinsics

- README.md
- cargo-miri/bin.rs
- src/diagnostics.rs
- src/helpers.rs
- src/machine.rs
`DefId::is_local` returns a result which is technically correct, but doesn't match the user's intuition when running integration tests or doctests. This incorporates the workspace crates mentioned in `cargo metadata` into the check for whether a frame is local to match user intuition.
For example, here is the backtrace you get from `MIRIFLAGS=-Zmiri-tag-raw-pointers cargo miri test` in `bytes` 1.1.0:
```
--> /home/ben/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/slice/raw.rs:131:14
|
131 |     unsafe { &mut *ptr::slice_from_raw_parts_mut(data, len) }
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ trying to reborrow for Unique at alloc67158, but parent tag <untagged> does not have an appropriate item in the borrow stack
|
= help: this indicates a potential …
```
> Consider the cargo workspace when checking if a frame is local

- tests/run-pass/vec.rs
Cc https://github.com/rust-lang/rust/pull/90821
> regression test for reverse() unsoundness

- README.md
- src/bin/miri.rs
- src/eval.rs
- src/intptrcast.rs
- src/machine.rs
- tests/compile-fail/box-cell-alias.rs
- tests/compile-fail/stacked_borrows/zst_slice.rs
- tests/compile-fail/strict-provenance-offset.rs
- tests/run-pass/btreemap.rs
- tests/run-pass/concurrency/channels.rs
- tests/run-pass/concurrency/sync.rs
- tests/run-pass/concurrency/thread_locals.rs
- tests/run-pass/concurrency/tls_lib_drop_single_thread.rs
- tests/run-pass/rc.rs
- tests/run-pass/slices.rs
- tests/run-pass/strings.rs
- tests/run-pass/vec.rs
- tests/run-pass/vecdeque.rs
This implements [strict provenance](https://github.com/rust-lang/rust/issues/95228) in Miri. The only change is that casting an integer to a pointer does not even attempt to produce a good provenance for the given address; instead, it always uses the invalid provenance. This stricter than even `-Zmiri-tag-raw-pointers` in that it also rejects the following example (which does not even involve Stacked Borrows):
```rust
fn main() {
let x = 22;
let ptr = &x as *const _ as *const u8;
let roundtrip = ptr as usize as *const u8;
let _ = unsafe { roundtrip.offset(1) };
}
```
The new flag also implies `-Zmiri-tag-raw-pointers` since the only reason one would *not* want to tag raw pointers is to support ptr-int-ptr roundtrips.
Note that the flag does *not* check against ptr-to-int *transmutes*; …
> add -Zmiri-strict-provenance

- README.md
- src/bin/miri.rs
- tests/compile-fail/strict_provenance_transmute.rs
- tests/run-pass/btreemap.rs
- tests/run-pass/concurrency/sync.rs
- tests/run-pass/concurrency/thread_locals.rs
- tests/run-pass/rc.rs
- tests/run-pass/slices.rs
- tests/run-pass/strings.rs
- tests/run-pass/vec.rs
- tests/run-pass/vecdeque.rs
I feel like Miri not catching [this example](https://github.com/rust-lang/unsafe-code-guidelines/issues/286#issuecomment-1085144431) with strict provenance checking enabled is surprising.
OTOH, Miri suddenly complaining about uninit data in integers with `-Zmiri-strict-provenance` also might be surprising. Which one is more surprising? I don't know. We *could* go out of our way and have a mode where uninit integers are okay but provenance is not, but I am not sure if that is truly worth it. It'd be quite annoying to implement.
> make strict-provenance imply check-number-validity

- Cargo.toml
- cargo-miri/Cargo.toml
- src/bin/miri.rs
- src/diagnostics.rs
- src/eval.rs
- src/helpers.rs
- src/shims/backtrace.rs
- src/shims/env.rs
- src/shims/foreign_items.rs
- src/shims/intrinsics.rs
- src/shims/os_str.rs
- src/shims/posix/fs.rs
- src/shims/posix/thread.rs
- src/shims/time.rs
- src/sync.rs
- src/thread.rs
- src/vector_clock.rs
`cargo fix --edition` didn't change anything for either of these crates, so this looks like a very simple port. And then we can remove a bunch of annoying imports. :)
I thought this also unlocks the named format string stuff, but it seems that works on all editions except for that problem around `panic!`. Whatever. ;)
> port Miri to edition 2021

- tests/run-pass/concurrency/sync.rs
This still sometimes fails on macOS, so let's increase the slack.
> increase slack for timeout test

- src/helpers.rs
- src/shims/posix/foreign_items.rs
- tests/run-pass/fs.rs
This isn't perfect; we end up using [this match](https://github.com/rust-lang/rust/blob/72a25d05bf1a4b155d74139ef700ff93af6d8e22/library/std/src/io/error.rs#L380) rather than the platform-specific messages, but at least we show something -- this is mostly informational anyway.
Cc https://github.com/rust-lang/miri/issues/2057
> implement strerror_r

- src/thread.rs
- tests/run-pass/concurrency/thread_locals.rs
They are not in read-only memory the way regular `static`s are.
Fixes https://github.com/rust-lang/rust/issues/96191
> do not consider thread-local allocations read-only

- .github/workflows/ci.yml
- README.md
The v2 implementation uses Node 12, which is end-of-life on April 30, 2022. See https://nodejs.org/en/about/releases/. Update to v3, which is based on Node 16 whose support lasts until April 30, 2024.
> Update GitHub Actions actions/checkout@v2 to v3

- src/bin/miri.rs
- src/data_race.rs
- src/diagnostics.rs
- src/helpers.rs
- src/lib.rs
- src/machine.rs
- src/range_map.rs
- src/shims/env.rs
- src/shims/foreign_items.rs
- src/shims/intrinsics.rs
- src/shims/os_str.rs
- src/shims/panic.rs
- src/shims/posix/fs.rs
- src/shims/posix/thread.rs
- src/shims/tls.rs
- src/stacked_borrows.rs
- src/sync.rs
- src/thread.rs
`cargo clippy` finishes cleanly after this. I stuck to only what I think are the least objectionable lints: cleaning up useless identity conversions that do `from`/`try_from`/`into` going from T-&gt;T, extraneous `&` on expressions that are already a reference, unused lifetime parameters, and similar.
Below in the \<details\> is the complete remaining output of `cargo clippy` with the `allow` attribute removed. I think all the lints left are fine to keep ignoring.
<details>
<summary><code>$ cargo clippy -- -Dclippy::all</code></summary>
```console
error: this `else { if .. }` block can be collapsed
--> src/data_race.rs:559:16
|
559 |           } else {
|  ________________^
560 | |             if lt { &rhs } else { &old }
561 | |         };
| |_________^ help: collapse nested if block: `if …
```
> Resolve some clippy lints, ignore the rest

- src/shims/foreign_items.rs
- tests/run-pass/intrinsics-x86.rs
This is the only new shim I need for https://github.com/dtolnay/precise/issues/2. It's used by the `num-bigint` crate for bigint addition.
> Implement llvm.x86.addcarry.64

- src/diagnostics.rs
- tests/compile-fail/erroneous_const.rs
- tests/compile-fail/type-too-large.rs
Fixes https://github.com/rust-lang/miri/issues/2088
> gracefully handle type-too-large layout errors

- Cargo.toml
- bench-cargo-miri/mse/src/main.rs
- rustup-toolchain
- tests/compile-fail/data_race/dangling_thread_async_race.rs
- tests/compile-fail/data_race/dealloc_read_race2.rs
- tests/compile-fail/data_race/read_write_race_stack.rs
- tests/compile-fail/data_race/write_write_race_stack.rs
- tests/compile-fail/panic/double_panic.rs
- tests/compile-fail/rc_as_ptr.rs
- tests/run-pass/backtrace-api-v1.rs
- tests/run-pass/concurrency/data_race.rs
- tests/run-pass/dyn-arbitrary-self.rs
- tests/run-pass/ptr_offset.rs
- tests/run-pass/stacked-borrows/stacked-borrows.rs
- tests/run-pass/threadleak_ignored.rs
Editors commonly strip trailing whitespace from source code on save, because it's almost always undesired, and that leads to spurious diffs in these files when working with them in such an editor.
> Clean up all trailing whitespace

- src/shims/backtrace.rs
- src/shims/foreign_items.rs
- src/shims/intrinsics.rs
- src/shims/mod.rs
- src/shims/panic.rs
- src/shims/posix/foreign_items.rs
- src/shims/posix/linux/foreign_items.rs
- src/shims/posix/macos/dlsym.rs
- src/shims/posix/macos/foreign_items.rs
- src/shims/windows/dlsym.rs
- src/shims/windows/foreign_items.rs
- tests/run-pass/vec-matching-fold.rs
The signature of `check_shim` is very amenable to this.
```rust
fn check_shim<'a, const N: usize>(…) -> InterpResult<'tcx, &'a [OpTy<'tcx, Tag>; N]>
```
Instead of:
```rust
let &[ref ptr, ref flags] = this.check_shim(…)?;
```
we can write it just as:
```rust
let [ptr, flags] = this.check_shim(…)?;
```
> Replace unneeded use of `ref` in favor of "match ergonomics"

- src/helpers.rs
- src/helpers/convert.rs
- src/shims/foreign_items.rs
Recommended in https://github.com/rust-lang/miri/pull/2090#pullrequestreview-958491177.
> Replace `as` casts in llvm.x86.addcarry.64 implementation

- src/diagnostics.rs
- tests/compile-fail/erroneous_const2.rs
Fixes https://github.com/rust-lang/miri/issues/2106
> test for "erroneous constant used" post-monomorphization error

- README.md
- src/bin/miri.rs
- src/eval.rs
- src/machine.rs
- src/shims/posix/fs.rs
- src/shims/windows/dlsym.rs
- tests/run-pass/hide_stdout.rs
This is practical for tests that don't actually care about the output and thus don't want it intermingled with miri's warnings, errors or ICEs
fixes #2083
> Add a command line flag to avoid printing to stdout and stderr

- miri
- src/machine.rs
Even Debian removed the package that provides `/usr/bin/python`; I guess it is time to move on.
> stop relying on python being in the PATH

- CONTRIBUTING.md
I came across these issues (see zulip threads [here](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/.E2.9C.94.20Changes.20not.20in.20effect) and [here](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Missing.20.2Elibrustc.2Estamp), issue [here](https://github.com/rust-lang/rust/issues/90244)) and would like to add this small bit to the docs. Feel free to change the wording.
> Clarified issues when building miri with a custom rustc

- src/bin/miri.rs
This will be useful once https://github.com/rust-lang/rust/pull/96898 landed.
> when MIRI_LOG is set, set RUSTC_LOG_ENTRY_EXIT

- src/data_race.rs
- src/helpers.rs
- src/shims/posix/sync.rs
- src/shims/windows/sync.rs
- src/sync.rs
This is required for #1963 
`{mutex, rwlock, cond, srwlock}_get_or_create_id()` currently checks whether an ID field is 0 using an atomic read, allocate one and get a new ID if it is, then write it in a separate atomic write. This is fine without weak memory. For instance, in `pthread_mutex_lock` which may be called by two threads concurrently, only one thread can read 0, create and then write a new ID, the later-run thread will always see the newly created ID and never 0.
```rust
fn pthread_mutex_lock(&mut self, mutex_op: &OpTy<'tcx, Tag>) -> InterpResult<'tcx, i32> {
let this = self.eval_context_mut();
let kind = mutex_get_kind(this, mutex_op)?.check_init()?;
let id = mutex_get_or_create_id(this, mutex_op)?;
let active_thread = this.get_active_thread();
```
However, with weak memory …
> Use atomic RMW for `{mutex, rwlock, cond, srwlock}_get_or_create_id` functions

- src/diagnostics.rs
- src/eval.rs
- src/helpers.rs
- src/machine.rs
- src/stacked_borrows.rs
- src/stacked_borrows/diagnostics.rs
- src/thread.rs
5225225 called this "automatic tag tracking" and I think that may be a reasonable description, but I would like to kill tag tracking as a primary use of Miri if possible. Tag tracking isn't always possible; for example if the UB is only detected with isolation off and the failing tag is made unstable by removing isolation. (also it's bad UX to run the tool twice)
This is just one of the things we can do with https://github.com/rust-lang/miri/pull/2024
The memory usage of this is _shockingly_ low, I think because the memory usage of Miri is driven by allocations where each byte ends up with its own very large stack. The memory usage in this change is linear with the number of tags, not tags * bytes. If memory usage gets out of control we can cap the number of events we save per allocation, …
> Print spans where tags are created and invalidated

- rustup-toolchain
This is a work-around for https://github.com/rust-lang/cargo/issues/10096.
> rustup-toolchain: also prepare toolchain for vscode

- src/stacked_borrows.rs
Fixes https://github.com/rust-lang/miri/issues/2127
I guess all I needed was a bit of sleep and reassurance that this diagnostic is the wrong part of that situation.
> Pass the correct size to the AllocRange for log_creation

- .github/workflows/ci.yml
- README.md
- ci.sh
This is basically documenting my policy so far: Linux is the target I know best and can spend most time on. Apple is so close to Linux that it can basically ride along without much extra work. I don't have a lot of time to spend on our Windows support.
Of course, if people commit to contributing and maintaining support for a target, we can promise more than what is documented here. :)  But this is what I am willing to promise.
Also reduce the amount of work we do on the Windows test runner, since that one currently takes 10min longer than the other two.
r? @oli-obk
> explain which targets we support to what extent

- src/machine.rs
- src/shims/windows/foreign_items.rs
- test-cargo-miri/Cargo.lock
- test-cargo-miri/Cargo.toml
- test-cargo-miri/test.cross-target.stdout.ref
- test-cargo-miri/test.default.stdout.ref
- test-cargo-miri/test.filter.cross-target.stdout.ref
- test-cargo-miri/test.filter.stdout.ref
- test-cargo-miri/test.test-target.stdout.ref
- test-cargo-miri/tests/test.rs
- Change logic in GetSystemInfo shim to take into account the two possible layouts of `SYSTEM_INFO`, the first-field-is-union used by [winapi::um::sysinfoapi::SYSTEM_INFO](https://docs.rs/winapi/latest/winapi/um/sysinfoapi/struct.SYSTEM_INFO.html), and first-two-fields-are-inlined-union used by [num_cpus](https://github.com/seanmonstar/num_cpus/blob/5f1b03332000b4c4274b5bd35fac516049ff1c6b/src/lib.rs#L206).
- Fill out the `dwPageSize` field with the `PAGE_SIZE` constant of `4096`.
Closes #2136
> Update GetSystemInfo to work with `page_size` (#2136)

- src/data_race.rs
- src/eval.rs
Fixes https://github.com/rust-lang/miri/issues/2020
I've tried for hours now to come up with a test case for this ICE with no luck. I suspect there's something about the way the data race detection works under these conditions that I just don't understand :weary:.
But I tried this change out on a handful of crates and I don't see any more ICEs of this form. For whatever reason it seems like `bastion==0.4.5` is a good way to run into this, with the flags
```
MIRIFLAGS="-Zmiri-tag-raw-pointers -Zmiri-panic-on-unsupported -Zmiri-disable-isolation" cargo +miri miri test --no-fail-fast --doc
```
I think all the cases I've run into with this involve both `-Zmiri-panic-on-unsupported` and `-Zmiri-tag-raw-pointers`, so it could be that the combination of an unexpected panic and a machine halt is …
> Make allow_data_races_* public and use it during EnvVars::cleanup

- src/eval.rs
- tests/run-pass/track-alloc-1.rs
- tests/run-pass/track-alloc-1.stderr
Fixes https://github.com/rust-lang/miri/issues/2076 just by handling diagnostics produced during setup. The tracking notes don't have any spans but it's better than an ICE.
It looks like we leak allocations 1..20, and allocations 13..19 don't have any creation notes, and 14 only has a `FreedAlloc` alloc tracking diagnostic.
> Adjust diagnostics assertion so we don't ICE in setup

- src/shims/posix/fs.rs
- tests/run-pass/hide_stdout.rs
should fix #2143
note: this is entirely untested, I was getting tons of errors on `cargo test` because of some missing setup.
I hope that CI can tell me if this works or not :see_no_evil: 
r? @oli-obk
> mute_stdout_stderr: mute stderr instead of stdin

- src/helpers.rs
- src/lib.rs
- src/machine.rs
- src/stacked_borrows.rs
- src/stacked_borrows/diagnostics.rs
After https://github.com/rust-lang/miri/pull/2030 and while working on https://github.com/rust-lang/miri/pull/1935 it became quite clear that we need to do some caching here, because some retag operations generate many calls to `log_invalidation`, and would thus search the current thread's stack _many_ times for a local crate. This caching fixes that. This handle type also has the nice benefit of tucking away all the `ThreadManager` + `CrateNum` logic.
> Factor current-span logic into a caching handle

- src/data_race.rs
Uh, I guess I got this backwards a long time ago 😓.
> Fix backwards `cmpxchg_weak_failure_rate` check

- README.md
- src/bin/miri.rs
- src/eval.rs
- src/helpers.rs
- src/intptrcast.rs
- src/lib.rs
- src/machine.rs
- src/stacked_borrows.rs
- tests/compile-fail/ptr_int_unexposed.rs
- tests/compile-fail/ptr_legacy_provenance.rs
- tests/run-pass/ptr_int_permissive_provenance.rs
Miri portions of the changes for portions of a permissive ptr-to-int model for Miri. This is more restrictive than what we currently have so it will probably need a flag once I figure out how to hook that up.
> This implements a form of permissive exposed-address provenance, wherein the only way to expose the address is with a cast to usize (ideally expose_addr). This is more restrictive than C in that stuff like reading the representation bytes (via unions, type-punning, transmute) does not expose the address, only expose_addr. This is less restrictive than C in that a pointer casted from an integer has union provenance of all exposed pointers, not any udi stuff.
There's a few TODOs here, namely related to `fn memory_read` and friends. We pass it the maybe/unreified provenance before …
> Initial work on Miri permissive-exposed-provenance

- src/intptrcast.rs
- src/machine.rs
Follow-up to https://github.com/rust-lang/miri/pull/2059
> clean up int2ptr code a bit

- tests/run-pass/atomic-compare-exchange-weak-never-fail.rs
Adds a test for https://github.com/rust-lang/miri/pull/2105
> test that compare-exchange-weak-failure-rate=0.0 means what it says

- README.md
As discussed with @oli-obk . However I was not always sure which flags to put where, so if you think some flags should be in the other category please let me know. :)
> split flag section into common and advanced flags

- tests/compile-fail/provenance/ptr_invalid.rs
(same for strict provenance, but there it is not surprising)
> with permissive-provenance set, we already treat ptr::invalid correctly

- tests/compiletest.rs
- ui_test/src/lib.rs
- Make the entire "## Running ui tests ..." green, including the target.
- Fix double-space in `testname.rs  .. ok`.
- Make the final summary a bit more like compiletest-rs, in particular the newlines around it
- Use the term "ignored" consistently, rather than "skipped"
r? @oli-obk
> tweak new test suite output

- src/shims/time.rs
- tests/run-pass/libc.rs
Original idea does not work, so I'm just going to try expanding support to include the `_COARSE` clocks.
The original motivation for this PR is that the test suite for the crate [`minstant`](https://crates.io/crates/minstant) reports UB, because it tries to use a clock type Miri didn't support, but never checked for an error code and so just used the uninit `libc::timespec`. So, that's technically a bug in `minstant`, but outside of Miri you'd have to be using an incredibly old Linux to ever see an `EINVAL` so the more helpful thing for Miri to do is behave like a newer Linux.
So now we don't detect UB in `minstant`, but we have a test failure:
```
failures:
---- src/instant.rs - instant::Instant::as_unix_nanos (line 150) stdout ----
Test executable failed (exit status: 101).
stderr: …
```
> Add support for _COARSE clocks

- src/stacked_borrows.rs
- tests/compile-fail/stacked_borrows/zst_slice.stderr
Currently, we don't save a created event for zero-sized reborrows. Attempting to use something from a zero-sized reborrow is surprisingly common, for example on `minimal-lexical==0.2.1` we previously just emit this:
```
Undefined Behavior: attempting a write access using <187021> at alloc72933[0x0], but that tag does not exist in the borrow stack for this location
--> /root/rust/library/core/src/ptr/mod.rs:1287:9
|
1287 |         copy_nonoverlapping(&src as *const T, dst, 1);
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|         |
|         attempting a write access using <187021> at alloc72933[0x0], but that tag does not exist in the borrow stack for this location
|         this error occurs as part of an access at alloc72933[0x0..0x8]
|
= help: this indicates a potential bug …
```
> Save a created event for zero-size reborrows

- ci.sh
- miri
- tests/compiletest.rs
- ui_test/src/lib.rs
- ui_test/src/tests.rs
- support multiple filters
- make `./miri check` also cover ui_test
- Run opt-level=4 tests again, but only the "run" tests
r? @oli-obk
> ui_test tweaks

- ui_test/src/lib.rs
compiletest does this and it is quite useful; see e.g. [here](https://github.com/rust-lang/rust/runs/6473917188?check_suite_focus=true). Example output:
> print list of failed tests in summary

- tests/fail/data_race/fence_after_load.rs
- tests/fail/data_race/fence_after_load.stderr
This interesting testcase came up in https://github.com/rust-lang/miri/issues/2192.
> add interesting data race test

- src/thread.rs
- tests/pass/concurrency/spin_loops.rs
- tests/pass/concurrency/spin_loops.stderr
When thread N blocks or yields, we activate thread N+1 next, rather than always activating thread 0. This should guarantee that as long as all threads regularly yield, each thread eventually takes a step again.
Fixes the "multiple loops that yield playing ping-pong" part of https://github.com/rust-lang/miri/issues/1388.
@cbeuw I hope this doesn't screw up the scheduler-dependent tests you are adding in your PR.
> make Miri's scheduler proper round-robin

- tests/fail/concurrency/thread-spawn.stderr
- ui_test/src/lib.rs
This hacks around https://github.com/rust-lang/miri/issues/2206. We don't currently use `only-32bit` or so, which is why this works.
> hotfix for incorrect only- logic

- src/lib.rs
- src/stacked_borrows.rs
The code before generated really bad code with a branch.
This nudges LLVM towards being smarter and simply comparing
the integers.
See https://github.com/rust-lang/miri/pull/2214#issuecomment-1150124617
> Optimize `SbTag::eq`

- src/helpers.rs
- src/shims/dlsym.rs
- src/shims/env.rs
- src/shims/foreign_items.rs
> Add unix helpers

- tests/compiletest.rs
@oli-obk when I just tried this locally (`./x.py test src/tools/miri --stage 0`), it worked fine. What differences had you seen before?
> test ui output also in rustc test suite

- ui_test/src/rustc_stderr.rs
Fixes https://github.com/rust-lang/miri/issues/2235
But I am not sure if anything else should be adjusted when adding a new error level...
> add ICE error level

- src/shims/unix/linux/sync.rs
- tests/pass/concurrency/linux-futex.rs
Fixes #2223
Two SC fences were placed in `futex_wake` (after the caller has changed `addr`), and in `futex_wait` (before we read `addr`). This guarantees that `futex_wait` sees the value written to `addr` before the last `futex_wake` call, should one exists, and avoid going into sleep with no one else to wake us up.
https://github.com/rust-lang/miri/blob/ada7b72a879d79aaa06f0a2a95edd520615da1a2/src/concurrency/weak_memory.rs#L324-L326
Earlier I proposed to use `fetch_add(0)` to read the latest value in MO, though this isn't the proper way to do it and breaks aliasing: syscall caller may pass in a `*const` from a `&` and Miri complains about write to a `SharedReadOnly` location, causing this test to fail.
https://github.com/rust-lang/miri/blob/ada7b72a879d79aaa06f0a2a95edd520615da1a2/tests/ …
> Prevent futex_wait from actually waiting if a concurrent waker was executed before us

- cargo-miri/bin.rs
Closes https://github.com/rust-lang/miri/issues/2037
I just implemented the fix suggested in that issue and it seems to work without issue.
> Pass --color=always through cargo-miri

- tests/fail/branchless-select-i128-pointer.rs
- tests/fail/branchless-select-i128-pointer.stderr
- tests/fail/data_race/dealloc_read_race1.rs
- tests/fail/data_race/dealloc_read_race1.stderr
- tests/fail/data_race/dealloc_write_race1.rs
- tests/fail/data_race/dealloc_write_race1.stderr
- tests/fail/function_calls/check_callback_abi.rs
- tests/fail/function_calls/check_callback_abi.stderr
- tests/fail/function_calls/exported_symbol_abi_mismatch.cache.stderr
- tests/fail/function_calls/exported_symbol_abi_mismatch.fn_ptr.stderr
- tests/fail/function_calls/exported_symbol_abi_mismatch.no_cache.stderr
- tests/fail/function_calls/exported_symbol_abi_mismatch.rs
- tests/fail/type-too-large.rs
- tests/fail/type-too-large.stderr
- tests/fail/validity/invalid_char.rs
- tests/pass/0weak_memory_consistency.rs
- tests/pass/concurrency/linux-futex.rs
- tests/pass/deriving-associated-types.rs
- tests/pass/heap_allocator.rs
- tests/pass/iter.rs
Extracted from #2097.
This is one half of the last 24 files (left for last because they require more unique attention than the first 275 "easy" files).
I'll comment below to call attention to cases where I exercised my own judgement in how to format the test.
https://github.com/rust-lang/rustfmt/issues/3255 is especially annoying: rustfmt does not like `…( //` and `…{ //`.
> Format tests with rustfmt (276-287 of 299)

- tests/fail/abort-terminator.rs
- tests/fail/concurrency/too_few_args.rs
- tests/fail/concurrency/too_many_args.rs
- tests/fail/concurrency/unwind_top_of_stack.rs
- tests/fail/concurrency/unwind_top_of_stack.stderr
- tests/fail/intrinsics/overflowing-unchecked-rsh.rs
- tests/fail/intrinsics/uninit_uninhabited_type.rs
- tests/fail/intrinsics/zero_fn_ptr.rs
- tests/fail/panic/bad_unwind.rs
- tests/fail/sync/libc_pthread_rwlock_read_write_deadlock_single_thread.rs
- tests/fail/sync/libc_pthread_rwlock_write_read_deadlock_single_thread.rs
- tests/fail/sync/libc_pthread_rwlock_write_write_deadlock_single_thread.rs
- tests/fail/transmute_fat1.rs
- tests/fail/transmute_fat1.stderr
- tests/fail/unaligned_pointers/alignment.rs
- tests/fail/unaligned_pointers/alignment.stderr
- ui_test/src/lib.rs
- ui_test/src/rustc_stderr.rs
if/when we get flaky diagnostics we can revisit and add more helpers for those
> Require local annotations for local diagnostics

- .github/workflows/ci.yml
Looks like this is what most people prefer/expect, and using a pinned toolchain for formatting avoids some (rare and so far mostly hypothetical) formatting inconsistency issues.
> make rustfmt mandatory and used pinned rustfmt

- Cargo.lock
- Cargo.toml
The major version number is different due to changes to the on-disk recording format but the core API is the same and miri continues to build on the latest version.
> Update measureme to the latest version

- README.md
- src/diagnostics.rs
- src/intptrcast.rs
- src/lib.rs
- src/machine.rs
- src/stacked_borrows.rs
- src/stacked_borrows/diagnostics.rs
- tests/fail/provenance/permissive_provenance_transmute.rs
- tests/fail/provenance/ptr_int_unexposed.rs
- tests/fail/stacked_borrows/exposed_only_ro.rs
- tests/fail/stacked_borrows/exposed_only_ro.stderr
- tests/fail/stacked_borrows/illegal_read_despite_exposed1.rs
- tests/fail/stacked_borrows/illegal_read_despite_exposed1.stderr
- tests/fail/stacked_borrows/illegal_read_despite_exposed2.rs
- tests/fail/stacked_borrows/illegal_read_despite_exposed2.stderr
- tests/fail/stacked_borrows/illegal_write_despite_exposed1.rs
- tests/fail/stacked_borrows/illegal_write_despite_exposed1.stderr
- tests/pass/ptr_int_from_exposed.rs
- tests/pass/stacked-borrows/int-to-ptr.rs
This uses an permissive `Unknown` implementation, where a wildcard pointer (and any SRW derived from a wildcard pointer) can access any previously-exposed SB tag. This is missing any meaningful test-cases, and all of the edge-cases have not yet been worked through.
I think there's also some bugs here with differing Unknowns in different ranges and having things behave really weirdly too, alongside some issues with retagging to `SRO` or `Unique`.
> Handle wildcard pointers in SB

- cargo-miri/bin.rs
https://github.com/rust-lang/miri/pull/2243 actually doesn't work :joy:
The suggestion to split on `,` was good but `arg` is actually the whole `--json=diagnostic-rendered-ansi,artifacts,future-incompat
`, and of course I didn't test that change locally and we have no test for this in CI.
Therefore, I would like some guidance on making a test for this because I'm going to rely on this working.
> Actually pass through the request for --color=always

- README.md
- src/bin/miri.rs
- src/diagnostics.rs
- src/eval.rs
- src/machine.rs
- test-cargo-miri/build.rs
Fixes https://github.com/rust-lang/miri/issues/910
The stacktrace is printed every N basic blocks. I picked the default (1 million) to take a few seconds on my machine, but it can be adjusted by the user.
> add -Zmiri-report-progress to regularly print a stacktrace of what we are executing

- tests/pass/concurrency/sync_nopreempt.rs
Not sure how that can fail given that preemption is disabled but whatever...
> make sure a thread is joined

- README.md
- src/intptrcast.rs
- test-cargo-miri/Cargo.lock
- test-cargo-miri/run-test.py
- tests/pass/adjacent-allocs.rs
- tests/pass/intptrcast.rs
Also `cargo update` in test-cargo-miri... no need to make a separate PR for that right?...
> Allow non-ZST allocations to be adjacent

- cargo-miri/bin.rs
They [cause problems](https://github.com/rust-lang/miri/issues/2277) and they completely break rendering on the playground:
```
Compiling playground v0.0.1 (/playground)
Finished dev [unoptimized + debuginfo] target(s) in 0.47s
Running `/playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri target/miri/x86_64-unknown-linux-gnu/debug/playground`
[0m[1m[38;5;9merror[E0277][0m[0m[1m: `*mut std::sync::atomic::AtomicUsize` cannot be sent between threads safely[0m
[0m   [0m[0m[1m[38;5;12m--> [0m[0msrc/main.rs:17:18[0m
[0m    [0m[0m[1m[38;5;12m|[0m
[0m[1m[38;5;12m17[0m[0m  [0m[0m[1m[38;5;12m|[0m[0m   [0m[0m        let j1 = spawn(move || {[0m
[0m    [0m[0m[1m[38;5;12m| [0m[0m …
```
> revert --color=always changes

- .github/workflows/ci.yml
- miri
- rustup-toolchain
- ui_test/src/comments.rs
- ui_test/src/lib.rs
- ui_test/src/rustc_stderr.rs
- ui_test/src/tests.rs
also make ui_test comply with clippy
> add ./miri clippy

- src/shims/time.rs
- src/shims/unix/foreign_items.rs
- src/shims/unix/macos/foreign_items.rs
- tests/pass/libc.rs
This appears to be in linux and in openbsd as well:
* https://github.com/torvalds/linux/blob/master/lib/vdso/gettimeofday.c
* https://github.com/openbsd/src/blob/master/sys/sys/time.h#L439
Note that std currently says [different syscalls are used on mac vs linux](https://doc.rust-lang.org/std/time/struct.SystemTime.html#platform-specific-behavior) but this is not part of[ std's contract](https://doc.rust-lang.org/std/io/index.html#platform-specific-behavior) and third party code could call the syscall directly on different platforms.
> Support `gettimeofday` on more than macos

- README.md
- src/shims/env.rs
Lets people experiment with the `TERM` env var.
> make -Zmiri-env-forward take precedence over -Zmiri-env-exclude

- ci.sh
- src/shims/unix/freebsd/foreign_items.rs
Signed-off-by: InfRandomness <infrandomness@gmail.com>
> Add `__error` to freebsd shims

- src/shims/unix/macos/foreign_items.rs
"In order to accommodate advanced capabilities of newer file systems,
the struct stat, struct statfs, and struct dirent data structures
were updated in Mac OSX 10.5."
"TRANSITIONAL DESCRIPTION (NOW DEPRECATED)
The fstat64, lstat64 and stat64 routines are equivalent to their
corresponding non-64-suffixed routine, when 64-bit inodes are in
effect.  They were added before there was support for the symbol
variants, and so are now deprecated.  Instead of using these, set
the _DARWIN_USE_64_BIT_INODE macro before including header files to
force 64-bit inode support. The stat64 structure used by these deprecated routines is the same
as the stat structure when 64-bit inodes are in effect (see above)."
"HISTORY
An lstat() function call appeared in 4.2BSD.  The stat64(),
fstat64(), and lstat64() …
> Support (stat/fstat/lstat)64 on macos

- ci.sh
- src/machine.rs
- tests/fail/environ-gets-deallocated.rs
This fixes the `env` test on freebsd, and enables the CI test
Signed-off-by: InfRandomness <infrandomness@gmail.com>
> Extend `environ` linux extern implementation to freebsd

- tests/pass/fs.rs
The shim got implemented a while ago but we never ensured that that is actually what std uses.
> test fs::read_link surface function

- miri
When using `cargo miri`, we otherwise have no way of even seeing which seed it is currently on.
> ./miri many-seeds: also print the seed before we try it

- README.md
Edit the README to explicitly say that the `-Zmiri-track-pointer-tag` flag also tracks the creation of tags, not just when they are popped/invalidated.
Related to https://github.com/rust-lang/miri/pull/2308 / https://github.com/Manishearth/triomphe/issues/38.
> Clarify the effect of the `-Zmiri-track-pointer-tag` flag in the README

- Cargo.toml
- src/lib.rs
- src/stacked_borrows.rs
- src/stacked_borrows/diagnostics.rs
- src/stacked_borrows/stack.rs
- ui_test/Cargo.toml
Before this PR, a profile of Miri under almost any workload points quite squarely at these regions of code as being incredibly hot (each being ~40% of cycles):
https://github.com/rust-lang/miri/blob/dadcbebfbd017aac2358cf652a4bd71a91694edc/src/stacked_borrows.rs#L259-L269
https://github.com/rust-lang/miri/blob/dadcbebfbd017aac2358cf652a4bd71a91694edc/src/stacked_borrows.rs#L362-L369
This code is one of at least three reasons that stacked borrows analysis is super-linear: These are both linear in the number of borrows in the stack and they are positioned along the most commonly-taken paths.
I'm addressing the first loop (which is in `Stack::find_granting`) by adding a very very simple sort of LRU cache implemented on a `VecDeque`, which maps recently-looked-up tags to their position in the …
> Optimizing Stacked Borrows (part 1?): Cache locations of Tags in a Borrow Stack

- ui_test/Cargo.toml
It tries to run doctests which leads to an error when testing against a locally built rustc (that has no rustdoc).
> there are no doctests in ui_test

- src/stacked_borrows.rs
- tests/pass/stacked-borrows/stacked-borrows.rs
Fixes a problem reported by @saethlin on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/269128-miri/topic/Stacked.20Borrows.20field.20retagging/near/288040048).
> fix retagging of vtable ptrs

- src/stacked_borrows.rs
- tests/pass/box-custom-alloc.rs
This is the Miri side of https://github.com/rust-lang/rust/pull/98847.
Thanks @DrMeepster for doing most of the work of getting this test case to pass in Miri. :)
> handle Box with allocators

- src/operator.rs
- tests/pass/pointers.rs
Fixes https://github.com/rust-lang/rust/issues/96169
However I am not sure if these are the correct semantics. Lexicographic comparison of the two wide ptr components?!? I'll wait for confirmation in that issue.
> fix comparing wide raw pointers

- miri
pointed out in https://github.com/rust-lang/miri/pull/2288#discussion_r915445912
> fix comment in ./miri

- src/lib.rs
- src/machine.rs
- src/stacked_borrows.rs
- src/stacked_borrows/diagnostics.rs
- src/stacked_borrows/item.rs
- src/stacked_borrows/stack.rs
- src/thread.rs
- tests/compiletest.rs
- tests/fail/stacked_borrows/aliasing_mut1.stderr
- tests/fail/stacked_borrows/aliasing_mut2.stderr
- tests/fail/stacked_borrows/aliasing_mut4.stderr
- tests/fail/stacked_borrows/deallocate_against_barrier1.rs
- tests/fail/stacked_borrows/deallocate_against_barrier1.stderr
- tests/fail/stacked_borrows/deallocate_against_barrier2.rs
- tests/fail/stacked_borrows/deallocate_against_barrier2.stderr
- tests/fail/stacked_borrows/illegal_write6.stderr
- tests/fail/stacked_borrows/invalidate_against_barrier1.stderr
- tests/fail/stacked_borrows/invalidate_against_barrier2.stderr
- tests/fail/stacked_borrows/newtype_retagging.rs
- tests/fail/stacked_borrows/newtype_retagging.stderr
This moves protectors out of `Item`, storing them both in a global `HashSet` which contains all currently-protected tags as well as a `Vec<SbTag>` on each `Frame` so that when we return from a function we know which tags to remove from the protected set.
This also bit-packs the 64-bit tag and the 2-bit permission together when they are stored in memory. This means we theoretically run out of tags sooner, but I doubt that limit will ever be hit.
Together these optimizations reduce the memory footprint of Miri when executing programs which stress Stacked Borrows by ~66%. For example, running a test with isolation off which only panics currently peaks at ~19 GB, with this PR it peaks at ~6.2 GB.
To-do
Benchmarks before:
```
Benchmark 1: cargo +miri miri run --manifest-path …
```
> Optimizing Stacked Borrows (part 2): Shrink Item

- src/stacked_borrows.rs
Before:
```
Benchmark 1: cargo miri run --manifest-path bench-cargo-miri/serde1/Cargo.toml
Time (mean ± σ):      6.729 s ±  0.050 s    [User: 6.608 s, System: 0.124 s]
Range (min … max):    6.665 s …  6.799 s    5 runs
Benchmark 2: cargo miri run --manifest-path bench-cargo-miri/unicode/Cargo.toml
Time (mean ± σ):     20.923 s ±  0.271 s    [User: 20.386 s, System: 0.537 s]
Range (min … max):   20.580 s … 21.165 s    5 runs
```
After:
```
Benchmark 1: cargo miri run --manifest-path bench-cargo-miri/serde1/Cargo.toml
Time (mean ± σ):      6.562 s ±  0.023 s    [User: 6.430 s, System: 0.135 s]
Range (min … max):    6.544 s …  6.594 s    5 runs
Benchmark 2: cargo miri run --manifest-path bench-cargo-miri/unicode/Cargo.toml
Time (mean ± σ):     20.375 s ±  0.228 s    [User: 19.964 s, System: …
```
> move checking ptr tracking on item pop into cold helper function

- Cargo.toml
- ci.sh
- miri
- src/concurrency/range_object_map.rs
- src/range_map.rs
- src/stacked_borrows/stack.rs
This makes `./miri run`/`./miri test` use the full set of debug assertions (including the rather expensive ones that check consistency of the Stacked Borrows cache), but `./miri install` installs a Miri *without* those debug assertions.
That's the same behavior as cargo, and helps catch Miri bugs with the test suite while making installed Miri usable for larger runs.
> Make "./miri {build,run,test}" use debug assertions but "./miri install" not

- src/stacked_borrows/mod.rs
I benchmarked this and as far as I can see the difference to the old code is totally within noise. And this makes the code a lot simpler and removes duplication so yay. :)
> use PlaceTy visitor and dedup sime retagging code

- src/shims/unix/foreign_items.rs
- src/shims/unix/fs.rs
- tests/pass/libc.rs
Per https://github.com/rust-lang/miri/issues/2292#issuecomment-1171858283, this is an attempt at
> do something more clever with Miri's `isatty` shim
Since Unix -> Unix is very simple, I'm starting with a patch that just does that. Happy to augment/rewrite this based on feedback.
The linked file in libtest specifically only supports stdout. If we're doing this to support terminal applications, I think it would be strange to support one but not all 3 of the standard streams.
The `atty` crate contains a bunch of extra logic that libtest does not contain, in order to support MSYS terminals: https://github.com/softprops/atty/commit/db8d55f88eabfcc22cde39533c2b1d688d1cdfc6 so I think if we're going to do Windows support, we should probably access all that logic somehow. I think it's pretty …
> Improve isatty support

- src/shims/unix/fs.rs
- tests/pass/libc.rs
@saethlin I realized we need to gate this behind the isolation flag, sorry. :/  The point of isolated mode is that it is 100% deterministic, so we cannot call host functions that might give different answers on different runs.
> isatty tweaks

- cargo-miri/bin.rs
- src/bin/miri.rs
- src/diagnostics.rs
- src/eval.rs
- detect when Miri got locally installed and is being run with the wrong toolchain
- when an ICE occurs, print a backtrace of where the interpreter was at the time
> fix some debugging papercuts

- ui_test/src/lib.rs
Currently we skip this if a stderr diff was printed, but the stderr diff is normalized, so e.g. one cannot learn line numbers from it.
Is there a way to get the diff to only print the parts the differ, like a usual `diff -u`? Currently it always seems to print the full output, so with a long stderr we now get doubly long test results even if the diff is actually rather small.
> on an error, always print the unnormalized stderr

- cargo-miri/bin.rs
This should help with https://github.com/rust-lang/miri/pull/2398.
> cargo-miri: reorder --target to after the user-defined commands

- src/concurrency/data_race.rs
- src/intptrcast.rs
- src/machine.rs
- src/shims/backtrace.rs
- src/stacked_borrows/mod.rs
- tests/fail/extern_static_wrong_size.rs
- tests/fail/extern_static_wrong_size.stderr
Also handle get_alloc_extra the same throughout Stacked Borrows. I don't think this `unwrap` can actually cause an ICE since another part of SB will raise an error before, but still, seems strange to do this inconsistently in retagging vs expose_ptr.
> check for extern static size mismatches

- .gitignore
- CONTRIBUTING.md
- miri
I keep forgetting to run rustup-toolchain on rebases across toolchain updates
I also keep forgetting to run rustfmt and clippy. The former isn't run by vscode if I don't explicitly save (I have autosave on).
> Add a scheme for always using the default toolchain, running clippy and fmt before running any other command

- cargo-miri/bin.rs
Add the ability to run `cargo miri nextest list` and `cargo miri nextest run`.
[cargo-nextest](https://nexte.st) is a new test runner for Rust maintained mostly by myself. It has several new features, but the most relevant to miri is the fact that it runs [each test in its own process](https://nexte.st/book/how-it-works.html#the-nextest-model). This gives miri users better leak detection (https://github.com/rust-lang/miri/issues/1481) for free, for example.
See https://github.com/nextest-rs/nextest/issues/181 for discussion, including comments by @eddyb and @RalfJung.
Future work might be to have miri read [the list of tests](https://docs.rs/nextest-metadata/latest/nextest_metadata/struct.TestListSummary.html) (or [test binaries](https://docs.rs/nextest-metadata/latest/nextest_metadata/str …
> [cargo-miri] support nextest

- tests/compiletest.rs
- ui_test/src/lib.rs
- ui_test/src/tests.rs
`./miri bless -- --quiet` now prints a dot per test, along with the regular Rust unit tests that listen to this flag
> Print one . character per test instead of one line

- miri
`rustup-toolchain` needs to be called in the right directory
> fix auto-toolchain pwd

- cargo-miri/bin.rs
- src/bin/miri.rs
Works around https://github.com/rust-lang/cargo/issues/10885.
> cargo-miri: set RUSTC to us

- tests/compiletest.rs
- tests/fail/crates/tokio_mvp.stderr
rustc CI has the cargo stuff in `/cargo/...`, so we also need to handle that path.
> normalize stronger

- README.md
- src/bin/miri.rs
- src/concurrency/data_race.rs
- src/concurrency/weak_memory.rs
- src/diagnostics.rs
- src/eval.rs
- src/machine.rs
Helps with https://github.com/rust-lang/miri/issues/2313. It can still be annoying to figure out *which* outdated load is the important one in case there are many of them (and the issue contains some ideas for how to help with that situation), but having this flag is better than nothing.
Thanks to @cbeuw for the [original patch](https://github.com/cbeuw/miri/commit/64d738cb00dbcfbe9cab29c77717f5af62c83ada) that I based this on.
The backtraces are currently a bit annoying, but https://github.com/rust-lang/rust/pull/98674 will help with that.
> add a flag to print a diagnostic when an outdated value is returned from an atomic load

- cargo-miri/bin.rs
- ci.sh
- src/machine.rs
- test-cargo-miri/run-test.py
The xargo invocation prints a lot of details users probably won't care about, so let's hide them (unless the user did `cargo miri setup`, then we still print everything).
> don't dump xargo output onto users of 'cargo miri test'

- src/stacked_borrows/stack.rs
Since `Item` is bitpacked now, the full `Item` is stored in the cache.
> Fix outdated docs in sb stack cache

- cargo-miri/bin.rs
- miri
That means we can properly escape spaces in our filename. This should fix https://github.com/rust-lang/miri/issues/2417, hopefully for real this time. We can also specify a "leading command" which makes it much easier to disambiguate runner invocations from rustdoc invocations!
Thanks to @ehuss for suggesting this.
> cargo-miri: use '--config target.runner' rather than the TARGET_RUNNER env vars

- cargo-miri/bin.rs
- ci.sh
Hopefully fixes https://github.com/rust-lang/miri/issues/2429
> attempt to overwrite globally set build.rustc-wrapper

- tests/fail/intrinsics/ptr_offset_from_unsigned_neg.rs
- tests/fail/intrinsics/ptr_offset_from_unsigned_neg.stderr
- tests/pass/intrinsics.rs
- tests/pass/pointers.rs
- tests/pass/ptr_offset.rs
We mostly rely on the CTFE tests in rustc that look at this intrinsic a lot, but let's have at least one test here as well.
> more tests for ptr_offset_from_unsinged

- ui_test/src/dependencies.rs
This should help ensure that tests are reproducible.
> ui_test: build dependencies in locked mode unless bless is enabled

- README.md
- cargo-miri/bin.rs
- miri
- src/bin/miri.rs
- test-cargo-miri/Cargo.lock
- test-cargo-miri/Cargo.toml
- test-cargo-miri/build.rs
- tests/compiletest.rs
This makes the Miri driver, when invokved via the RUSTC env var from inside a build script, behave almost entirely like rustc. I had to redo how we propagate sysroot information for this (which is actually back to how we used to do sysroot propagation many years ago).
Fixes https://github.com/rust-lang/miri/issues/2431
> fix build.rs invoking RUSTC to do check builds

- src/intptrcast.rs
- src/lib.rs
- src/shims/backtrace.rs
- src/shims/env.rs
- src/shims/foreign_items.rs
- src/shims/intrinsics/mod.rs
- src/shims/tls.rs
- src/shims/unix/fs.rs
- src/shims/windows/dlsym.rs
- src/shims/windows/foreign_items.rs
- src/stacked_borrows/item.rs
Cc https://github.com/rust-lang/miri/issues/1236
> enable clippy lints against integer casts

- src/shims/unix/fs.rs
- tests/fail/fs/close_stdout.rs
- tests/fail/fs/close_stdout.stderr
I felt like it was just noisy to have to write the "can't do this here" defaults
> Add default impls for `FileDescriptor` methods

- cargo-miri/bin.rs
Closes https://github.com/rust-lang/miri/issues/2421
The standard library has a platform extension trait that lets us get the behavior we want on cfg(unix), so why not use it?
I tried this out and it produces the correct behavior in concert with nextest.
> Use real exec on cfg(unix) targets
