rust-lang/miri

src/interpreter/mod.rs
src/interpreter/step.rs

rustup to rustc 1.14.0-nightly (3f4408347 2016-10-27)

---

benches/helpers/miri_helper.rs
benches/helpers/repeat.rs
benches/helpers/repeat_manual.rs
benches/repeat.rs
src/error.rs
src/interpreter/mod.rs
src/interpreter/step.rs
src/interpreter/terminator/intrinsics.rs
src/interpreter/terminator/mod.rs
src/interpreter/vtable.rs
src/memory.rs
tests/compile-fail/modifying_constants.rs
tests/compile-fail/repeat.rs
tests/compile-fail/repeat2.rs
tests/run-pass/move-arg-3-unique.rs

abort on huge repeat expressions

---

Cargo.lock
Cargo.toml
src/bin/miri.rs
src/error.rs
src/memory.rs
src/terminator/intrinsic.rs
src/terminator/mod.rs
tests/compiletest.rs
tests/run-pass/aux_test.rs
tests/run-pass/auxiliary/dep.rs

Reverts the revert, #94, bringing #93 back into master.

Revert "Revert "rustup to rustc 1.15.0-dev (ace092f56 2016-12-13)""

---

src/error.rs
src/eval_context.rs
src/terminator/mod.rs
tests/compile-fail/never_say_never.rs
tests/compile-fail/never_transmute_humans.rs
tests/compile-fail/never_transmute_void.rs
tests/run-pass/tuple_like_struct_constructor.rs

taken from https://github.com/rust-lang/rust/blob/05768690857636f27e17c825de791491a88784e7/src/librustc_trans/callee.rs#L92

allow the use of tuple struct constructors as functions

---

src/eval_context.rs
src/terminator/intrinsic.rs
src/terminator/mod.rs
tests/run-pass/union.rs

various small fixes

---

src/bin/miri.rs
src/step.rs

This should get it building again on nightly.
**Edit:** Or rather, get it building again on master. Doesn't look like the change has hit nightly yet.

TyCtxt's map renamed to hir

---

src/error.rs
src/eval_context.rs
src/memory.rs
src/terminator/mod.rs
src/vtable.rs
tests/compiletest.rs
tests/run-pass/fn_item_as_closure_trait_object.rs
tests/run-pass/fn_item_with_args_as_closure_trait_object.rs
tests/run-pass/fn_item_with_multiple_args_as_closure_trait_object.rs
tests/run-pass/fn_ptr_as_closure_trait_object.rs
tests/run-pass/mir_coercions.rs
tests/run-pass/multi_arg_closure.rs

fixes #111
fixes #112 
fixes #114

fix turning function items into closure trait objects

---

src/lvalue.rs
src/terminator/intrinsic.rs
tests/run-pass/dst-field-align.rs

compute the offset of dst fields by checking the vtable

---

src/terminator/drop.rs
tests/run-pass/zst_variant_drop.rs

drop zst fields of null pointer optimized structs and enums

---

src/eval_context.rs
src/lvalue.rs
src/operator.rs
src/terminator/drop.rs
src/terminator/intrinsic.rs
src/terminator/mod.rs
tests/run-pass/call_drop_on_array_elements.rs
tests/run-pass/call_drop_on_zst_array_elements.rs

The test suite will fail until <https://github.com/rust-lang/rust/pull/42369> gets merged.

remove our array drop glue and use rustc's instead

---

src/terminator/intrinsic.rs
tests/run-pass/issue-miri-184.rs

fix issue 184 by marking the destination as a packed struct

---

src/error.rs
src/eval_context.rs
src/memory.rs
src/terminator/intrinsic.rs
tests/compile-fail/out_of_bounds_ptr_2.rs
tests/compile-fail/ptr_offset_overflow.rs
tests/run-pass/aux_test.rs

Fixes #178
Also, remove a FIXME that was already fixed and extend a clarifying comment in memory.rs.

Bail out on overflow

---

src/eval_context.rs
src/traits.rs

Fixes breakage from https://github.com/rust-lang/rust/pull/42563.

update for latest nightly rustc

---

tests/compiletest.rs

Currently, one cannot even see if the tests being executed are from the run-pass or run-pass-fullmir directories.
For some odd reason, the `eprintln!` macro in Rust itself doesn't actually seem to print anything, so I re-implemented it locally...

run fullmir tests against rustc; add output explaining what is being tested

---

src/error.rs
src/eval_context.rs
src/operator.rs
src/terminator/mod.rs

cc #217 
These checks are hard to test, because rustc will do them for us before miri ever runs.

Initial work towards checking const eval rules in miri

---

tests/compile-fail/cast_fn_ptr_unsafe.rs
tests/compile-fail/cast_fn_ptr_unsafe2.rs

Fixes breakage introduced by https://github.com/rust-lang/rust/pull/42519.

update tests for new error message

---

src/eval_context.rs
src/operator.rs
src/terminator/mod.rs

previous PR: #218
cc @RalfJung

Address comments to previous PR

---

src/eval_context.rs
src/terminator/intrinsic.rs
tests/compile-fail/transmute-pair-undef.rs

Fix transmute on ByValPair

---

src/error.rs
src/eval_context.rs
src/memory.rs
src/terminator/mod.rs
tests/compile-fail/deallocate-bad-alignment.rs
tests/compile-fail/deallocate-bad-size.rs
tests/compile-fail/deallocate-twice.rs
tests/compile-fail/reallocate-bad-alignment.rs
tests/compile-fail/reallocate-bad-size.rs
tests/compile-fail/reallocate-change-alloc.rs

Make Reallocate & Deallocate less permissive

---

src/memory.rs
src/terminator/intrinsic.rs
src/terminator/mod.rs
tests/compile-fail/deallocate-bad-alignment.rs
tests/compile-fail/deallocate-bad-size.rs
tests/compile-fail/deallocate-twice.rs
tests/compile-fail/reallocate-bad-alignment.rs
tests/compile-fail/reallocate-bad-size.rs
tests/compile-fail/reallocate-change-alloc.rs
tests/run-pass/associated-const.rs
tests/run-pass/issue-31267-additional.rs

So nice to have a test suite :)

Update for allcator API, simplify reallocate

---

.travis.yml
tests/compile-fail/reallocate-bad-alignment-2.rs
tests/compile-fail/reallocate-bad-alignment.rs
xargo/build.sh

This is more convenient than having to `cd xargo`.
Also add a test I forgot to `git add`.

Add little script to build libstd

---

tests/compile-fail/transmute_fat.rs
tests/compile-fail/transmute_fat2.rs

Add tests for #113

---

src/lvalue.rs

IMHO this shows better what is going on; also reduces some code duplication.
(And happens to help me do more stuff with lvalues. ;)

lvalue: refactoring to permit applying a mir projection to a miri lvalue

---

src/const_eval.rs
src/error.rs
src/eval_context.rs
src/lvalue.rs
src/memory.rs
src/step.rs
src/terminator/mod.rs
src/traits.rs
tests/compile-fail/double_free.rs
tests/compile-fail/stack_free.rs

cc @RalfJung 
You had to write a workaround around my hack. Both are gone now :)

Ensure that it is not possible to explicitly free stack memory

---

src/bin/miri.rs
src/step.rs
tests/compiletest.rs
tests/run-pass-fullmir/integer-ops.rs
tests/run-pass/cast-rfc0401-vtable-kinds.rs

Also test optimized MIR

---

tests/run-pass/ref-invalid-ptr.rs

Test that &* of a dangling (and even unaligned) ptr is okay

---

Cargo.lock
src/librustc_mir/Cargo.toml
src/librustc_mir/interpret/bin/miri.rs
src/librustc_mir/interpret/error.rs
src/librustc_mir/interpret/eval_context.rs
src/librustc_mir/interpret/lvalue.rs
src/librustc_mir/interpret/memory.rs
src/librustc_mir/interpret/mod.rs
src/librustc_mir/interpret/step.rs
src/librustc_mir/interpret/terminator/mod.rs
src/librustc_mir/interpret/validation.rs
tests/run-pass/cast-rfc0401-vtable-kinds.rs

I rebased your branch and ripped out the "broken" code. When you continue working on it you should be able to simply revert 08dca1fbf47c68c63e5492948b756570d0a36152, git should take care of most of the other things.
r? @RalfJung

Mir validate

---

src/librustc_mir/interpret/eval_context.rs
src/librustc_mir/interpret/lvalue.rs
src/librustc_mir/interpret/memory.rs
src/librustc_mir/interpret/step.rs
src/librustc_mir/interpret/terminator/intrinsic.rs
src/librustc_mir/interpret/terminator/mod.rs
src/librustc_mir/interpret/validation.rs
src/librustc_mir/interpret/value.rs
tests/run-pass/packed_struct.rs

To make this work, I had to let `write_maybe_aligned` support proper nesting (rather than just asserting this does not happen).

make force_allocation handle packed ByValPair

---

.travis.yml
Cargo.toml
miri/fn_call.rs
rustc_tests/Cargo.lock
rustc_tests/Cargo.toml
rustc_tests/src/main.rs
src/librustc_mir/interpret/eval_context.rs
tests/run-pass-fullmir/unsized-tuple-impls.rs

and get the rustc test suite binary compiling again

Process untagged unions

---

src/librustc_mir/interpret/error.rs
src/librustc_mir/interpret/memory.rs
src/librustc_mir/interpret/mod.rs
src/librustc_mir/interpret/range_map.rs
src/librustc_mir/interpret/validation.rs
tests/run-pass/many_shr_bor.rs

Now with proper support for multiple independent shared borrows of the same mutable reference.

Re-do memory locking

---

xargo/build.sh

This should help with https://github.com/solson/miri/pull/253

make xargo/build.sh more cross-platform

---

.travis.yml
tests/compile-fail/validation_buggy_as_mut_slice.rs
tests/run-pass/validation_lifetime_resolution.rs

Still not hard enough, but well, we do what we can.
Also, more tests.

More validation tests

---

Cargo.lock
Cargo.toml
tests/compiletest.rs

update compiletest, use tempdir

---

tests/compile-fail/memleak_rc.rs
tests/compile-fail/panic.rs
tests/compile-fail/zst2.rs
tests/compile-fail/zst3.rs
tests/run-pass/rc.rs
tests/run-pass/send-is-not-static-par-for.rs
tests/run-pass/std.rs

https://github.com/rust-lang/rust/issues/43457 got fixed :)

Enable more validation tests

---

tests/run-pass/rc.rs

They do some interesting unsafe pointer arithmetic etc., certainly worth looking at.

test new From instances for Rc

---

src/librustc_mir/interpret/eval_context.rs

Storage{Live,Dead} in generators got fixed

---

src/librustc_mir/interpret/operator.rs

Use rustc's APFloat impl instead of interpreter host floats

---

appveyor.yml

No need to keep building every PR twice if the PRs branch is on this repository

Only run appveyor on the master branch and on PRs

---

src/librustc_mir/interpret/eval_context.rs

to match that of the latest rust nightly

update trans_fulfill_obligation call signature

---

miri/fn_call.rs
miri/intrinsic.rs
miri/lib.rs
miri/validation.rs

This updates the rustup branch to work on the latest nightly

Rustup to rustc 1.27.0-nightly (79252ff4e 2018-04-29)

---

miri/bin/miri.rs
miri/fn_call.rs
miri/lib.rs

Tests should pass when next nightly is out.

Fixed build for latest nightly (again)

---

.travis.yml
appveyor.yml

so any PRs after a working commit didn't pass.

cargo cache was messing up xargo/miri install

---

src/lib.rs

This prevents duplication with priroda

Split create_ecx out of eval_main

---

src/lib.rs

Add missing pub

---

src/fn_call.rs
src/helpers.rs
src/lib.rs
src/locks.rs
src/operator.rs
src/range_map.rs
src/tls.rs
src/validation.rs

Based on #388 and contains a workaround for rust-lang/rust#52128

Clippy fixes

---

README.md

Also move them further down because it is probably less relevant than some of
the other stuff.

update rustc build instructions to mention keep-stage

---

.travis.yml
README.md
rust-toolchain

Fixes https://github.com/solson/miri/issues/426

document and fully use rust-toolchain file

---

.travis.yml
README.md
xargo/Xargo.toml

Fixes https://github.com/solson/miri/issues/414

Cargo miri test

---

tests/run-pass/static_memory_modification.rs

I could not find any existing test for this.

Test mutating a non-mut static with interior mutability

---

src/intrinsic.rs

See for example https://doc.rust-lang.org/beta/std/sync/atomic/struct.AtomicU8.html#method.fetch_add.

atomics wrap around on overflow

---

src/fn_call.rs
src/intrinsic.rs
src/tls.rs

`is_null` is going to go away, and anyway we don't need it here.

Avoid using is_null

---

src/intrinsic.rs
tests/compile-fail/atomic_non_integer_arithmetic.rs

Reject atomic arithmetic on non-integer types

---

Cargo.toml
README.md
tests/compiletest.rs

use custom test runner so that we can get proper test filtering

---

README.md

Let's avoid too many people getting too frustrated because it does not work for them.

cargo miri test currently does not work

---

README.md
src/bin/cargo-miri.rs

Also always set up a proper libstd

update README to first describe the usual user setup

---

tests/run-pass/ptr_offset.rs

Adds a test for what got changed in https://github.com/solson/miri/pull/589

add test for offseting fn ptr

---

src/fn_call.rs

I finally figured out what is going on: the platform-independent code in `std::io` adds a buffer around `stdout()`, but not around `stderr()`.  This buffer is inside Rust, so Miri sees nothing of it -- when Miri sees a `write` syscall, that means the program flushed its buffer and we really want it to be sent out to the FD now.

we don't need to flush stderr

---

src/intrinsic.rs
tests/run-pass/volatile.rs

related: https://github.com/rust-lang/rust/issues/58645

use copy_op directly insteadof write_scalar

---

README.md

@gnzlbg would a comment like this about `cargo +nightly miri setup` have helped?
Fixes https://github.com/rust-lang/miri/issues/656

expand README

---

README.md

Fixes https://github.com/rust-lang/miri/issues/520

update README to suggest installing Miri as a component

---

src/fn_call.rs
tests/run-pass/calloc.rs

Add `calloc`

---

.appveyor.yml
.travis.yml
src/bin/cargo-miri.rs
test-cargo-miri/src/main.rs
tests/compile-fail/stacked_borrows/mut_exclusive_violation2.rs

Just to be extra sure we catch this kind of problem even when no accesses happen at all.

test that creating a 2nd mutable ref from a NonNull invalidates the first

---

Cargo.toml

Fixes https://github.com/rust-lang/miri/issues/685

bump compiletest

---

README.md

Fixes https://github.com/rust-lang/miri/issues/733

expand explanation of how we treat validity invariants

---

Cargo.toml

Bump cargo_metadata and directories dependencies

---

tests/compile-fail/generator-pinned-moved.rs

add a failing test where an immovable generator gets moved

---

src/intptrcast.rs
src/machine.rs
tests/run-pass/intptrcast_format.rs
tests/run-pass/intptrcast_format.stdout

fix comparing function pointers with intptrcast

---

.gitattributes

Let's see if this is the right setting for Windows...

be explicit about our line endings

---

src/shims/intrinsics.rs
tests/compiletest.rs

rustup https://github.com/rust-lang/rust/pull/62403
cc https://github.com/rust-lang/rust/issues/62347

Remove SliceConcatExt import

---

src/bin/miri.rs

I thought this crash was in my code at first because the error was so vague.

Give a useful error message if user gives invalid random seed

---

src/eval.rs
src/lib.rs
src/stacked_borrows.rs

As requested in https://github.com/rust-lang/miri/pull/852#issuecomment-514612244

build: Warn if not use 2018 idioms

---

README.md

also update paragraph on intptrcast

README: call out more clearly what we do not test

---

tests/compiletest.rs

test suite: be fine with warnings when running on rustc CI

---

tests/compile-fail/dangling_zst_deref.rs

Fixes https://github.com/rust-lang/miri/issues/582.

test dangling ZST deref

---

src/shims/foreign_items.rs
tests/run-pass/intrinsics-math.rs

Fixes https://github.com/rust-lang/miri/issues/821
r? @RalfJung

Add shim for ldexp

---

src/bin/cargo-miri.rs

This is so that once https://github.com/japaric/xargo/pull/246 landed, we can see if that helps with https://github.com/rust-lang/rust/pull/63162.

install xargo from git temporarily

---

src/bin/cargo-miri.rs

The experiment in https://github.com/rust-lang/rust/pull/63162 was successful, now we have to wait for a new xargo release.

go back to released xargo (the experiment is done)

---

src/bin/cargo-miri.rs

Fixes https://github.com/rust-lang/miri/issues/892
Cc @shepmaster

mention that we get the toolchain right

---

src/eval.rs
src/lib.rs
src/shims/env.rs
src/shims/foreign_items.rs

Move env shims to its own module

---

.travis.yml

This tests the rpath hackery in `./miri`.

travis: do not install cargo from master

---

README.md
benches/helpers/miri_helper.rs
src/bin/miri-rustc-tests.rs
src/bin/miri.rs
src/eval.rs
src/shims/env.rs
tests/run-pass/env-exclude.rs

related issue: #933
r? @RalfJung

Exclude environment variables from host communication

---

src/shims/env.rs

Just to simplify the logic behind `shims::env`

Rewrite alloc_env_var

---

tests/run-pass/atomic.rs

Missing from https://github.com/rust-lang/miri/pull/979

also test AcqRel fence

---

rust-version

Just because it has been a while since the last bump.

bump to latest nightly

---

tests/run-pass/fs.rs

use temp_dir for FS test

---

src/bin/cargo-miri.rs

Follow-up to https://github.com/rust-lang/miri/pull/980

explain our shell encoding

---

.appveyor.yml
.travis.yml
README.md

Avoid downloading some stuff we really don't care about.

install minimal profile by default

---

.appveyor.yml
.travis.yml
src/bin/cargo-miri.rs

We temporarily disabled the cache just to get it updated.

Cache rustup-toolchain-install-master again

---

src/shims/fs.rs

also check full buffers for validity

use new isize_max method in FS accesses

---

src/shims/foreign_items.rs
tests/run-pass/intrinsics-math.rs

I copied the tests from the docs pages

Add acos, asin, and atan foreign functions

---

tests/run-pass/catch_panic.rs
tests/run-pass/catch_panic.stderr

Add some tests for https://github.com/rust-lang/miri/issues/1071.
Blocked on https://github.com/rust-lang/rust/pull/66844.

test more panics

---

CONTRIBUTING.md
rustup-toolchain
toolchain

I've been using a variant of this script for some time now, and figured others might find it useful as well.

add toolchain mgmt script

---

tests/run-pass/track-caller-attribute.rs

The CTFE implementation seems to also work fine in Miri -- thanks a lot @anp :)

add caller_location tests to Miri

---

src/bin/cargo-miri.rs

This should help with https://github.com/mozilla/nixpkgs-mozilla/issues/198.

disable sysroot checks for distributed binaries

---

src/helpers.rs

use new try_from methods

---

tests/run-pass/c_enums.rs

note a FIXME

---

src/shims/foreign_items.rs
src/shims/fs.rs
tests/run-pass/fs.rs

Add shim for symbolic link creation

---

tests/run-pass/track-caller-attribute.rs

Looks like we already use `ReifyShim` the right way, let's just make sure we test that!

test track_caller with fn ptrs

---

src/lib.rs
tests/compile-fail/copy_null.rs
tests/compile-fail/copy_overlapping.rs
tests/compile-fail/copy_unaligned.rs
tests/run-pass/panic/catch_panic.rs
tests/run-pass/panic/catch_panic.stderr

Fixes https://github.com/rust-lang/miri/issues/1126

Make sure we evaluate debug assertions in local crate and libstd

---

src/eval.rs
src/helpers.rs
src/shims/foreign_items.rs
src/shims/foreign_items/posix.rs
src/shims/foreign_items/posix/linux.rs
src/shims/fs.rs

some foreign_items cleanup

---

README.md
benches/helpers/miri_helper.rs
src/bin/miri-rustc-tests.rs
src/bin/miri.rs
src/eval.rs
src/lib.rs
src/machine.rs
src/shims/panic.rs
src/stacked_borrows.rs
tests/compile-fail/modifying_constants.rs
tests/compile-fail/reference_to_packed.rs
tests/compile-fail/stack_free.rs
tests/compile-fail/static_memory_modification1.rs
tests/compile-fail/static_memory_modification2.rs
tests/compile-fail/static_memory_modification3.rs
tests/run-pass/observed_local_mut.rs
tests/run-pass/transmute_fat.rs

while keeping validation enabled. Fixes https://github.com/rust-lang/miri/issues/1183.

add an option to disable Stacked Borrows

---

src/intptrcast.rs
src/machine.rs
src/mono_hash_map.rs
src/shims/env.rs
src/shims/fs.rs
src/stacked_borrows.rs

switch extern_statics map to symbols, and use FxHashMap everywhere

---

Cargo.toml

downgrade serde_json to match rustc workspace

---

src/shims/env.rs

@christianpoveda I thought of a way to simplify initialization a bit. :)

move environ init to update_environ

---

src/machine.rs
src/shims/env.rs
src/shims/foreign_items/posix/macos.rs

move environ place to EnvVars

---

src/shims/foreign_items.rs
src/shims/intrinsics.rs

Also makes sure we don't accidentally call some normal intrinsics diverging -- which it turns out we did.

refactor handling of diverging intrinsics/foreign functions

---

src/eval.rs

**"initialziation"** => **"initialization"**

Minor typo fix

---

miri
src/shims/intrinsics.rs
tests/compile-fail/copy_null.rs
tests/compile-fail/copy_overflow.rs
tests/compile-fail/write_bytes_null.rs
tests/compile-fail/write_bytes_overflow.rs

Fixes https://github.com/rust-lang/miri/issues/1234

detect UB: overflow in copy/write_bytes

---

src/helpers.rs
src/shims/env.rs

Moving some of the changes submitted in PR #1225, in order to prevent the original PR from bloating too much.

helper functions for env_var emulation in Windows

---

src/machine.rs
src/shims/fs.rs
src/shims/intrinsics.rs
tests/compile-fail/unreachable.rs

Fixes https://github.com/rust-lang/miri/issues/1254

Implement unreachable intrinsic

---

src/bin/cargo-miri.rs
travis.sh

Fixes https://github.com/rust-lang/miri/issues/1198

cross-running windows-gnu should now also work

---

src/eval.rs
src/helpers.rs
src/machine.rs
src/shims/foreign_items.rs
src/shims/foreign_items/posix.rs
src/shims/foreign_items/windows.rs
src/shims/intrinsics.rs
src/shims/tls.rs

Mostly fixes https://github.com/rust-lang/miri/issues/442

run Windows TLS dtor function

---

src/helpers.rs
src/shims/env.rs
src/shims/foreign_items/windows.rs
src/shims/time.rs
tests/run-pass/time.rs

Implement `GetSystemTimeAsFileTime` shim for Windows.
Closes #997

Implement 'GetSystemTimeAsFileTime' shim for Windows

---

.appveyor.yml
.travis.yml
miri

it's just a waste of time there

set CARGO_INCREMENTAL=0 on CI

---

README.md

Thanks @Firstyear for letting me know about this :)

add EbrCell to trophy case

---

CONTRIBUTING.md
miri

@ssomers does this help, or do you think there is more we should say?
Fixes https://github.com/rust-lang/miri/issues/1306

More explicit build instructions

---

src/bin/cargo-miri.rs
src/diagnostics.rs
src/machine.rs
src/mono_hash_map.rs
src/shims/panic.rs
src/shims/tls.rs

Inspired by https://internals.rust-lang.org/t/is-ref-more-powerful-than-match-ergonomics/12111

avoid ref in matches

---

tests/run-pass/time.rs

Let's see if we can get away with this...

tighten Instance sanity check

---

src/diagnostics.rs

ReadBytesAsPointer is always supported

---

README.md
src/bin/cargo-miri.rs

Disable interactive prompts in CI

---

src/bin/miri.rs
tests/compile-fail/rustc-error.rs

Fixes https://github.com/rust-lang/miri/issues/1352

fix exit code on rustc errors

---

README.md
src/shims/foreign_items/posix/macos.rs
src/shims/tls.rs

make sure macos function has 'macos' in its name

---

README.md

@RalfJung please update it with whatever language is most correct :)

Add another tikv stacked borrowing error to trophy case

---

tests/run-pass/float.rs

copy some float cast tests from rustc

---

src/bin/cargo-miri.rs

With this, `cargo miri test -- -- --help` should behave as expected and pass `--help` to the test runner.
Thanks to @brson for the report.

fix cargo-miri intercepting --help/--version arguments

---

ci.sh

This accidentally got lost in https://github.com/rust-lang/miri/pull/1407

test Linux on macOS host

---

tests/compile-fail/concurrency/libc_pthread_create_main_terminate.rs
tests/compile-fail/concurrency/libc_pthread_join_detached.rs
tests/compile-fail/concurrency/libc_pthread_join_joined.rs
tests/compile-fail/concurrency/libc_pthread_join_main.rs
tests/compile-fail/concurrency/libc_pthread_join_multiple.rs
tests/compile-fail/concurrency/libc_pthread_join_self.rs
tests/compile-fail/environ-gets-deallocated.rs
tests/run-pass/calloc.rs
tests/run-pass/malloc.rs
tests/run-pass/thread-local.rs

fix some ignore-windows comments

---

cargo-miri/bin.rs

better way to get an absolute path

---

src/shims/posix/foreign_items.rs

Handle `read`s on STDIN

---

tests/run-pass/track-caller-attribute.rs

Adds a Miri-side test for https://github.com/rust-lang/rust/issues/74764.

test track_caller on trait objects

---

cargo-miri/bin.rs

also detect Azure CI environments

---

cargo-miri/bin.rs

This came up in https://github.com/hsivonen/encoding_rs/pull/57.

support non-rlib extern files

---

README.md

Cc @brson thanks for the ping!

another TiKV bug for the trophy case :)

---

README.md

and mention cross-interpretation already in the intro

readme: mention data races

---

.github/workflows/ci.yml

> Please be kind and courteous. There’s no need to be mean or rude.
― Rust Code of conduct

Teach the miri cronjobs to speak politely

---

README.md
cargo-miri/bin.rs

Fixes https://github.com/rust-lang/miri/issues/1661

prefer build-time env vars over run-time values

---

test-cargo-miri/Cargo.lock
test-cargo-miri/Cargo.toml
test-cargo-miri/issue-1567/Cargo.toml
test-cargo-miri/issue-1567/src/lib.rs

Adds a regression test for #1567.

add regression test for #1567

---

cargo-miri/bin.rs
test-cargo-miri/run-test.py

Fixes https://github.com/rust-lang/miri/issues/1722

cargo-miri: avoid unnecessary rebuilds

---

cargo-miri/bin.rs
test-cargo-miri/run-test.py

Thanks @RalfJung for the discovery: https://github.com/rust-lang/miri/issues/1724#issuecomment-787115693 :heart:
Fixes #1724.

cargo-miri: create stub .d files

---

.github/workflows/ci.yml

We sometimes have discussions in those threads; let's make sure we have a new thread for each new day (which likely means a new problem... or nobody got around to fixing things yet^^).

add date to Zulip notification subject

---

src/eval.rs
src/helpers.rs
src/machine.rs
src/shims/panic.rs
src/shims/posix/thread.rs
src/shims/tls.rs
tests/compile-fail/concurrency/too_few_args.rs
tests/compile-fail/concurrency/too_many_args.rs
tests/compile-fail/concurrency/unwind_top_of_stack.rs

Fixes https://github.com/rust-lang/miri/issues/1741

Check callee ABI when Miri calls closures

---

README.md

Also update the "unsupported" example to something that is actually unsupported.

mention 'cargo miri test filter' in README

---

src/thread.rs

As discussed on issue #1763, just try asking the scheduler to try again.
Fixes https://github.com/rust-lang/miri/issues/1763

Attempt to fix #1763

---

CONTRIBUTING.md

Fixes https://github.com/rust-lang/miri/issues/1773

fix CONTRIBUTING example

---

cargo-miri/bin.rs

Fixes https://github.com/rust-lang/miri/issues/1939

require xargo 0.3.23

---

README.md

Fixes https://github.com/rust-lang/miri/issues/1942
@robamler would this have helped?

readme: be more explicit about the toolchain

---

tests/run-pass/stacked-borrows/interior_mutability.rs

Signed-off-by: Miguel Ojeda <ojeda@kernel.org>

Remove spurious `maybe_uninit_extra`

---

src/data_race.rs
src/lib.rs
src/shims/intrinsics.rs
tests/run-pass/portable-simd.rs

This lets us run the puny portable-simd smoke test in the core test suite. ;)

implement simd_neg and simd_fabs

---

src/machine.rs
src/shims/intrinsics.rs
tests/run-pass/portable-simd.rs

This makes large parts of the portable-simd test suite work. :D
Cc https://github.com/rust-lang/portable-simd/pull/255

add more simd_reduce intrinsics

---

tests/run-pass/portable-simd.rs

Forgot to include this in https://github.com/rust-lang/miri/pull/2001

also test f32/f64 simd_reduce

---

Cargo.lock
Cargo.toml
README.md
src/bin/miri.rs

also accept odd number of hex digits
@saethlin you mentioned that you liked this snippet, do you think it'd make sense to put it in the README?

add README section on randomized alignment testing

---

src/shims/intrinsics.rs
tests/run-pass/portable-simd.rs

Cc https://github.com/rust-lang/miri/issues/1912

implement SIMD float rounding functions

---

.gitignore

Add `.vscode` directory to `.gitignore` for configuring `rust-analyzer`

Add `.vscode` directory to `.gitignore`

---

src/shims/foreign_items.rs

Taken from review in https://github.com/rust-lang/miri/pull/2101

Update a path to libstd source in our comments

---

src/eval.rs
src/helpers.rs

Fixes https://github.com/rust-lang/miri/issues/2120

don't ICE when libcore is missing

---

src/helpers.rs
src/stacked_borrows.rs

@saethlin this is what I meant. I had to fiddle a bit to make the lifetimes work, but now it passes rustc. :)

reduce some code duplication

---

.github/workflows/ci.yml
cargo-miri/bin.rs
cargo-miri/version.rs

Also use that as a clue to refresh our CI caches.
Fixes https://github.com/rust-lang/miri/issues/705

bump Xargo

---

.github/workflows/ci.yml
benches/helpers/fibonacci_helper_iterative.rs
cargo-miri/bin.rs
rustup-toolchain
src/lib.rs
src/machine.rs
src/shims/intrinsics.rs
src/shims/posix/sync.rs

and fix some things it complains about. Also use `rustup-toolchain` script on CI (reduces code duplication, and good thing to make sure it keeps working, since we recommend it in the docs).
I left `ui_test` out for now; I'll leave those nits to @oli-obk. ;)

run Clippy on CI

---

src/data_race.rs
src/shims/tls.rs
src/stacked_borrows.rs

This fixes the rustdoc warnings presented by the tool

Fix rustdoc warnings

---

.github/workflows/ci.yml
src/lib.rs
tests/pass/concurrency/linux-futex.rs

We don't currently trigger this but I saw it in a PR and I'd rather evaluate this on a case-by-case basis during review, thank you clippy.

make clippy mandatory for bors, and silence another clippy lint

---

src/helpers.rs

@InfRandomness this should help with your trouble in https://github.com/rust-lang/miri/pull/2215

make frame_in_std check work with inlining

---

ui_test/src/comments.rs
ui_test/src/lib.rs

Fixes https://github.com/rust-lang/miri/issues/2206

fix behavior of only-Nbits comments

---

cargo-miri/bin.rs

Fixes https://github.com/rust-lang/miri/issues/2238

avoid setting both RUSTC and RUSTC_WRAPPER

---

tests/pass/concurrency/linux-futex.rs

This fails when I remove the `validate_lock_acquire` or `validate_lock_release` from `futex_wake`. So finally we got those code paths actually covered in tests. :)

test that futexes induce appropriate synchronization

---

README.md
src/machine.rs
src/shims/panic.rs

This looks like a refactoring accident.

put call to stacked borrows end_call in a more sensible place

---

Cargo.toml
ui_test/Cargo.toml
ui_test/src/comments.rs
ui_test/src/rustc_stderr.rs

Helps with the issue I [mentioned on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/269128-miri/topic/Miri.20rebuilds/near/287442340).

reduce regex features to reduce rebuilds

---

CONTRIBUTING.md

Following [this recommendation](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/.22target.22.20directory.20in.20rustc.20tree.3F/near/288428273)
Cc https://github.com/rust-lang/rustc-dev-guide/pull/1384

update vscode settings

---

triagebot.toml

@Mark-Simulacrum does this look like a sensible configuration?

set up triagebot

---

tests/fail/stacked_borrows/deallocate_against_barrier1.rs
tests/fail/stacked_borrows/deallocate_against_barrier2.rs
ui_test/README.md
ui_test/src/lib.rs
ui_test/src/parser.rs
ui_test/src/parser/tests.rs

Error patterns can be regexes

---

ui_test/README.md

I forgot to do that when changing the ignore/only syntax.

update ui_test readme

---

cargo-miri/bin.rs

@matthiaskrgr this should help with https://github.com/rust-lang/miri/issues/2340. Any chance you could test this before we land it?

cargo-miri: write the Xargo project files atomically

---

tests/pass/upcast.rs

Copied from the rustc test suite.

add some dyn upcasting tests

---

src/concurrency/data_race.rs
src/eval.rs

Hopefully fixes https://github.com/rust-lang/miri/issues/2396

only do env var cleanup if all threads have stopped

---

cargo-miri/bin.rs
ui_test/src/dependencies.rs
ui_test/src/lib.rs

Fix for https://github.com/rust-lang/rust/pull/99530#issuecomment-1191768658
Also make the debugging output consistent.

cargo-miri x.py fix

---

tests/pass/track-caller-attribute.rs

add more track_caller tests

---

src/lib.rs
src/shims/unix/foreign_items.rs
src/shims/unix/fs.rs
src/shims/unix/linux/foreign_items.rs
src/shims/unix/mod.rs
src/shims/windows/foreign_items.rs
tests/pass/home.rs

add support for env::home_dir

---

cargo-miri/src/arg.rs
cargo-miri/src/main.rs
cargo-miri/src/phases.rs
cargo-miri/src/util.rs
ci.sh
miri

and then I went on to refactor the argument flag splitting thing a bit, and, uh, that snowballed...

also forward --manifest-path to 'cargo metadata'

---

cargo-miri/src/main.rs
cargo-miri/src/phases.rs
cargo-miri/src/setup.rs
cargo-miri/src/util.rs
src/bin/miri.rs

Panicking on incorrect `-Zmiri` flags is a bit embarrassing, so let's finally fix that.

don't make it quite so easy to get Miri to panic

---

.gitignore

found in https://github.com/rust-lang/miri/pull/2363#discussion_r956100939

Fix merge conflict

---

.github/workflows/ci.yml
src/concurrency/thread.rs

CI spends a few minutes downloading the index so this could help.

CI: use cargo sparse registry

---

README.md
src/bin/miri.rs
src/eval.rs
src/lib.rs
src/machine.rs
src/shims/unix/foreign_items.rs
src/shims/windows/foreign_items.rs
tests/pass/available-parallelism-miri-num-cpus.rs

Apparently you can't rename a branch from github's website without it closing all your PRs with that branch. So this is  just #2545

Add flag to specify the number of cpus

---

.github/workflows/ci.yml
cargo-miri/Cargo.lock
cargo-miri/Cargo.toml

This should fix sysroot build problems on nix.

bump rustc-build-sysroot

---

cargo-miri/Cargo.lock

Cc https://github.com/rust-lang/rust-clippy/issues/9553

bump rustc_tools_util

---

src/shims/windows/foreign_items.rs

because I'm planning to break miri again https://github.com/rust-lang/rust/pull/103360
See [GetFileType](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfiletype)

add GetFileType stub

---

CONTRIBUTING.md

This is the version of josh that I used to create https://github.com/rust-lang/rust/pull/103392.

point to my fork of josh for now

---

.github/workflows/ci.yml

This way it is again in my morning.

change cronjob time

---

tests/fail/data_race/stack_pop_race.rs
tests/fail/panic/no_std.rs
tests/pass/concurrency/sync.rs
tests/pass/concurrency/sync_nopreempt.rs
tests/pass/no_std.rs
tests/pass/shims/env/current_exe.rs
tests/pass/shims/sleep_long.rs

Turns out 2 of these tests can actually be enabled. :)

update ignore-windows comments

---

cargo-miri/src/phases.rs

Followup for pr 2640

---

miri

Fixes https://github.com/rust-lang/miri/issues/2643

fix ./miri bench

---

Cargo.lock
Cargo.toml
tests/fail/function_calls/exported_symbol_abi_mismatch.rs
tests/fail/function_calls/exported_symbol_bad_unwind2.rs

All commands can now be revisioned: https://github.com/oli-obk/ui_test/pull/33

Bump ui_test crate

---

src/borrow_tracker/mod.rs
src/borrow_tracker/stacked_borrows/mod.rs
src/concurrency/data_race.rs
src/concurrency/thread.rs
src/concurrency/weak_memory.rs
src/helpers.rs
src/lib.rs
src/machine.rs
src/shims/panic.rs

and some renaming for consistency

slight simplifications for borrow tracking

---

src/helpers.rs
src/shims/env.rs
src/shims/time.rs
src/shims/tls.rs
src/shims/unix/foreign_items.rs
src/shims/unix/fs.rs
src/shims/unix/linux/foreign_items.rs
src/shims/unix/linux/sync.rs
src/shims/unix/macos/foreign_items.rs
src/shims/unix/sync.rs
src/shims/unix/thread.rs
src/shims/windows/foreign_items.rs
src/shims/windows/sync.rs
src/shims/windows/thread.rs

and make eval_libc functions ICE on any problem

make flag checks reobust against multi-bit flags

---

CONTRIBUTING.md

Fixes https://github.com/rust-lang/miri/issues/2730
r\? @oli-obk

update josh instructions

---

Cargo.lock
cargo-miri/Cargo.lock
cargo-miri/Cargo.toml
cargo-miri/src/setup.rs
ci.sh
test-cargo-miri/Cargo.lock
test_dependencies/Cargo.lock
test_dependencies/Cargo.toml
tests/avr.json

Fixes https://github.com/rust-lang/miri/issues/2053

support using a JSON target file

---

tests/pass/0weak_memory_consistency.rs

I'm not sure if we currently *guarantee* to pass this test, but at least I was unable to get it to fail.
Cc @cbeuw

add scfix test

---

CONTRIBUTING.md

Without this I was unable to push, even though pushing directly to https without josh works.

Explain how to make josh authenticate with github via ssh

---

README.md

Inspired by this question: https://github.com/rust-lang/miri/issues/2805

Add a section on using nextest

---

README.md

@Vanille-N does it look ok to you?

Add link for tree borrows similar to stacked borrows

---

src/machine.rs
src/shims/unix/linux/foreign_items.rs
tests/pass-dep/shims/libc-misc.rs

Fixes https://github.com/rust-lang/miri/issues/2832.

Add shim for SIGRTMIN

---

src/shims/unix/fs.rs
src/shims/unix/linux/fd/event.rs

Fixes https://github.com/rust-lang/miri/issues/2800

fix endianess handling in eventfd::write

---

tests/compiletest.rs

Emit the compiler flags in CI again

---

cargo-miri/src/arg.rs
cargo-miri/src/phases.rs
test-cargo-miri/run-test.py

Fixes https://github.com/rust-lang/miri/issues/2829

cargo-miri: fix forwarding arguments to cargo

---

src/borrow_tracker/tree_borrows/diagnostics.rs

Revert error in doc comment

---

Cargo.lock
Cargo.toml
tests/compiletest.rs

address review from https://github.com/rust-lang/miri/pull/2941#discussion_r1242038723

Make `--quiet` actually do something

---

.github/workflows/ci.yml

The main tests use `bash` several times, maybe that is the issue here, too?

Try to fix cronjob PR creation

---

.github/workflows/ci.yml
miri

Also run this every hour to speed up testing

cronjob auto-PR: make sure we are on a branch

---

tests/fail/function_calls/arg_inplace_observe_after.rs
tests/fail/function_calls/arg_inplace_observe_after.stderr

Cc https://github.com/rust-lang/rust/issues/113549

work around custom_mir span

---

miri-script/src/commands.rs

I got stack overflows after I fixed the `-`/`_` typo 😆

Avoid infinite recursion for auto-fmt and auto-clippy

---

cargo-miri/src/main.rs
cargo-miri/src/phases.rs
cargo-miri/src/setup.rs
miri-script/src/commands.rs
src/helpers.rs
src/machine.rs

I noticed the one error in miri-script and took care of a few more shallow ones.

A bit of spell-checking

---

CONTRIBUTING.md
README.md
miri-script/src/commands.rs

Looks like rust-analyzer.checkOnSave.overrideCommand got renamed to rust-analyzer.check.overrideCommand.

update recommended RA config

---

Cargo.lock
Cargo.toml
cargo-miri/Cargo.lock
cargo-miri/Cargo.toml
ci.sh
miri
miri-script/src/commands.rs
test-cargo-miri/Cargo.lock
test-cargo-miri/Cargo.toml
test-cargo-miri/run-test.py
tests/compiletest.rs

bump to a version with the binary blob removed
also, respect CARGO_EXTRA_FLAGS in more places

bump serde

---

miri-script/src/commands.rs

add subtree-sync label to rustc update PRs

---

.github/workflows/ci.yml
triagebot.toml

enforce no-merge policy via triagebot

---

src/shims/intrinsics/mod.rs
tests/pass/float.rs
tests/pass/intrinsics-math.rs

Fixes https://github.com/rust-lang/miri/issues/2649

add some float tests

---

tests/fail/function_calls/simd_feature_flag_difference.rs
tests/fail/function_calls/simd_feature_flag_difference.stderr

Cc https://github.com/rust-lang/miri/issues/3095

add test for a function ABI mismatch due to target features

---

README.md
src/diagnostics.rs

Add -Zmiri-track-alloc-accesses to readme and fix its wording

---

.github/workflows/ci.yml

Same as https://github.com/rust-lang/miri-test-libstd/pull/44

Conjob → Cronjob

---

tests/fail/alloc/no_global_allocator.rs
tests/fail/panic/no_std.rs
tests/pass/miri-alloc.rs
tests/pass/no_std.rs
tests/pass/overloaded-calls-simple.rs

set panic=abort so that we do not need this eh_personality thing

simplify no-std tests

---

tests/pass/intptrcast.rs

add exposed-provenance example where we miss UB

---

Cargo.toml
ci/ci.sh
src/borrow_tracker/stacked_borrows/stack.rs

Fixes https://github.com/rust-lang/miri/issues/3431

cotrol stacked borrows consistency check with its own feature flag

---

src/shims/unix/foreign_items.rs
src/shims/unix/freebsd/foreign_items.rs
src/shims/unix/linux/foreign_items.rs

also remove duplicate socketpair

linux/foreign_items: reorder things to make more sense

---

src/helpers.rs
src/lib.rs
src/shims/env.rs
src/shims/os_str.rs
src/shims/windows/foreign_items.rs
tests/pass/shims/path.rs

This is the last missing piece to make std `path::` tests work on Windows.

add some basic support for GetFullPathNameW

---

src/shims/x86/mod.rs

It will allow more flexible uses in the future. This makes `split_simd_to_128bit_chunks` simpler, moving some of the complexity to its callers.

Make `split_simd_to_128bit_chunks` take only one operand

---

cargo-miri/Cargo.lock
cargo-miri/Cargo.toml

Bump rustc-build-sysroot to 0.4.6

---

tests/pass/drop_type_without_drop_glue.rs

Fixes https://github.com/rust-lang/miri/issues/2737

add test for Drop terminator on non-drop type

---

src/shims/alloc.rs
src/shims/foreign_items.rs
src/shims/mod.rs
src/shims/unix/foreign_items.rs
src/shims/unix/fs.rs
src/shims/windows/foreign_items.rs
tests/fail-dep/realloc-zero.rs
tests/fail-dep/realloc-zero.stderr
tests/pass-dep/malloc.rs

Fixes https://github.com/rust-lang/miri/issues/2774

make realloc with a size of zero fail

---

.github/workflows/ci.yml

bump actions/cache to v4

---

.github/workflows/ci.yml

Fixes https://github.com/rust-lang/miri/issues/3324

run clippy on a Windows host

---

src/concurrency/sync.rs
src/shims/unix/sync.rs
tests/pass-dep/shims/libc-rsfs.stdout
tests/pass-dep/shims/pthread-sync.rs

@devnexen this should fix the ICE in your PR (but it won't fix the code, it will just report proper UB instead).

sync: better error in invalid synchronization primitive ID

---

README.md
ci/ci.sh
src/shims/unix/mem.rs
src/shims/unix/solarish/foreign_items.rs
tests/pass-dep/shims/libc-misc.rs

Fixes https://github.com/rust-lang/miri/issues/3566

Solaris: make pre-main code work

---

CONTRIBUTING.md
README.md
ci/ci.sh
miri-script/src/commands.rs
miri-script/src/main.rs

Fixes #3584
I'm not a pro shell script reader as I am a Windows user, but we shall see if the CI script broke.

Allow test targets to be set via CLI args

---

src/intrinsics/atomic.rs
src/shims/x86/avx2.rs
src/shims/x86/mod.rs

This is already what we do most of the time, so do it consistently.

intrinsics: just panic when they get used incorrectly

---

.gitignore

Ignore the Helix configuration directory

---

ci/ci.sh
src/shims/extern_static.rs
src/shims/unix/android/foreign_items.rs
src/shims/unix/android/mod.rs
src/shims/unix/foreign_items.rs
src/shims/unix/mod.rs
tests/fail/environ-gets-deallocated.rs
tests/pass-dep/libc/libc-misc.rs
tests/pass/shims/env/home.rs

Fixes https://github.com/rust-lang/miri/issues/3608

make basic things work on Android

---

src/intrinsics/simd.rs

simd_select_bitmask: fix intrinsic name in error

---

src/helpers.rs

Fixes https://github.com/rust-lang/miri/issues/3692

don't rely on libc existing on Windows

---

src/shims/unix/foreign_items.rs
src/shims/unix/linux/epoll.rs
src/shims/unix/mod.rs
src/shims/unix/unnamed_socket.rs
tests/pass-dep/libc/libc-pipe.rs
tests/pass-dep/libc/libc-socketpair.rs

Fixes https://github.com/rust-lang/miri/issues/3746

implement pipe and pipe2

---

src/shims/unix/linux/epoll.rs
tests/pass-dep/libc/libc-epoll.rs

Set EINVAL for epoll_wait maxevent value 0

---

tests/pass-dep/libc/libc-epoll.rs

Turns out `let data = MaybeUninit::<u64>::uninit().as_ptr();` is a dangling pointer, the memory gets freed at the end of that line. For these cases we don't care as we don't actually access the pointer, but let's not do such subtle things.

epoll test: avoid some subtly dangling pointers

---

src/borrow_tracker/tree_borrows/tree.rs

Fixes the FIXME introduced in #3833. Thanks to @dmitrii-ubskii for the idea :slightly_smiling_face:

Avoid extra copy by using `retain_mut` and moving the deletion into the closure

---

miri.bat

Hopefully fixes https://github.com/rust-lang/miri/issues/3863 (but I can't test that)

miri.bat: use nightly toolchain

---

ci/ci.sh

I don't actually know if this works on Windows.^^

smoke-test './miri run --dep'

---

.github/workflows/ci.yml

Copied from https://github.com/rust-lang/docs.rs/pull/2611

fix workflow permissions

---

Cargo.lock
Cargo.toml
miri-script/Cargo.lock
miri-script/Cargo.toml

Bumps few things around `miri-script` reducing deps; bump `chrono-tz`.

bump few deps

---

src/shims/unix/linux/epoll.rs

@tiif does `return_ready_list` seem like a reasonable name?

epoll: rename blocking_epoll_callback since it is not just called after unblocking

---

src/shims/unix/fs.rs

I pushed this into https://github.com/rust-lang/miri/pull/3990 after the approval, seems it got simply ignored.

indicate more explicitly where we close host file/dir handles

---

src/shims/unix/linux/epoll.rs
src/shims/unix/linux/eventfd.rs
tests/fail-dep/libc/eventfd_block_read_twice.rs
tests/fail-dep/libc/eventfd_block_write_twice.rs

eventfd: comment tweaks

---

miri-script/src/commands.rs

Fixes https://github.com/rust-lang/miri/issues/4086

./miri bench: set toolchain explicitly

---

tests/pass/0weak_memory_consistency.rs
tests/pass/0weak_memory_consistency_sc.rs

add more tests for SC access/fence consistency

---

triagebot.toml

See https://forge.rust-lang.org/triagebot/merge-conflicts.html

triagebot: enable merge conflict notification

---

src/helpers.rs
src/shims/unix/macos/foreign_items.rs
tests/pass-dep/libc/libc-fs.rs
tests/pass/shims/pipe.rs

Supported fioclex for ioctl on macos

---

src/math.rs

@eduardosm does this make sense?

clarify apply_random_float_error logic

---

src/eval.rs

If the program has UB, go straight to diagnostics and then quit, don't even try to do cleanup -- who knows what happened with the program state.

do not run EnvVars::cleanup if there was an interpreter error

---

src/shims/windows/foreign_items.rs
tests/pass/path.rs

Check that these tests pass on a Windows host. They will still fail on Unix hosts.

path: add more Windows tests

---

src/alloc_addresses/mod.rs

We need to have access to `alloc_id_from_addr` and `addr_from_alloc_id` for some ongoing work in Miri, so this change makes them available.
The `MemoryKind` argument to `addr_from_alloc_id` is only required if the result is not cached, and we don't have easy access to the `MemoryKind` in the location where we want to call the function, so it is now optional.
We need to be able to get `AllocId`s for allocations that were not exposed, so there is now a parameter to `alloc_id_from_addr` to get results for all allocations vs only exposed ones.
r? @RalfJung

Expose Pointer to/from AllocId conversion functions, make some arguments optional

---

src/shims/windows/foreign_items.rs
src/shims/windows/fs.rs
tests/pass-dep/shims/windows-fs.rs
tests/pass/shims/fs.rs

This adds a shim for DeleteFileW, and both std and Windows API tests for it

Implement file deletion on Windows

---

.github/workflows/ci.yml

remove test trigger fron cron job

---

tests/pass/tree_borrows/interior_mutability.rs

In preparation for https://github.com/rust-lang/miri/pull/4273.

TB: add missing interior_mutability test file

---

src/shims/files.rs

@CraftSpider is this clear enough, or should we go into more detail?

FileDescription: improve read/write docs

---

miri-script/src/commands.rs

Also stop (accidentally) putting temporary files into `bench/`, and only show the basename of the benchmarks rather than the full path in the output.
Thanks to @nia-e for pointing out the issue regarding the lack of sorting.

./miri bench: sort results alphabetically

---

src/diagnostics.rs
tests/fail-dep/libc/unsupported_incomplete_function.stderr
tests/fail/alloc/no_global_allocator.stderr
tests/fail/unsupported_foreign_function.stderr
tests/native-lib/fail/function_not_in_so.stderr
tests/native-lib/fail/private_function.stderr

As discussed in [#miri > Stop saying "please file an issue" when we hit unsupported?](https://rust-lang.zulipchat.com/#narrow/channel/269128-miri/topic/Stop.20saying.20.22please.20file.20an.20issue.22.20when.20we.20hit.20unsupported.3F/with/508503802)

Change unsupported diagnostic wording

---

etc/rust_analyzer_helix.toml

Follows 828d41f7b91287f2242ed657cd5d42ca3a09e8bd.

Synced rust-analyzer configs

---

src/shims/unix/linux_like/sync.rs
tests/pass-dep/concurrency/linux-futex.rs

Fixes https://github.com/rust-lang/miri/issues/4427

linux futex: fix for val > i32::MAX

---

Cargo.toml
etc/rust_analyzer_helix.toml
etc/rust_analyzer_vscode.json
src/alloc/alloc_bytes.rs
src/alloc/mod.rs
src/bin/miri.rs
src/lib.rs
src/machine.rs
src/shims/foreign_items.rs
src/shims/mod.rs
tests/ui.rs

A step towards https://github.com/rust-lang/miri/issues/4461

make native-lib support compile-time-optional, and centralize cfg usage

---

Cargo.toml
src/alloc/isolated_alloc.rs
src/lib.rs
src/shims/native_lib/mod.rs
src/shims/native_lib/trace/child.rs
src/shims/native_lib/trace/messages.rs

I wanted to put this into the previous PR but forgot that I had left the auto-merge on there. :joy:

move page protection logic inside native_lib

---

src/concurrency/thread.rs
src/shims/time.rs
src/shims/unix/freebsd/sync.rs
src/shims/unix/sync.rs

Fixes https://github.com/rust-lang/miri/issues/4446

centralize clockid_t interpretation

---

src/helpers.rs
tests/pass/shims/ctor.rs

Fixes https://github.com/rust-lang/miri/issues/4501

lookup_link_section: support arrays of function pointers

---

.github/workflows/ci.yml

We don't actually need to close and reopen these any more.

update rustup PR message

---

.github/workflows/ci.yml

We might as well test on all targets that [Ubuntu supports](https://help.ubuntu.com/community/SupportedArchitectures).

CI: also test build on powerpc

---

src/shims/native_lib/trace/parent.rs

native-lib: more resilient grabbing of instruction bytes

---

cargo-miri/src/phases.rs

This now prints something like
```
$ cargo +miri miri test --help
`cargo miri test` supports the same flags as `cargo test`:
Execute all unit and integration tests and build examples of a local package
Usage: cargo test [OPTIONS] [TESTNAME] [-- [ARGS]...]
Arguments:
[TESTNAME]  If specified, only run tests containing this string in their names
[ARGS]...   Arguments for the test binary
Options:
...
```

improve output for 'cargo miri test --help'

---

src/intrinsics/mod.rs
src/machine.rs
src/math.rs
tests/pass/float.rs
tests/pass/float_extra_rounding_error.rs
tests/pass/shims/x86/rounding-error.rs

Fixes https://github.com/rust-lang/miri/issues/4556.
I honestly don't understand where this off-by-1 comes from, though...

fix mangitude of applied float error

---

src/alloc_addresses/mod.rs
src/borrow_tracker/stacked_borrows/mod.rs
src/concurrency/genmc/helper.rs
src/concurrency/genmc/mod.rs
src/concurrency/genmc/run.rs
src/diagnostics.rs
src/helpers.rs
src/lib.rs
src/machine.rs
src/shims/native_lib/mod.rs
tests/genmc/pass/std/thread_locals.stderr

Fixes https://github.com/rust-lang/miri/issues/4597

deduplicate warnings globally
